// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, aboutBarqMilestonesControllerCreate, aboutBarqMilestonesControllerRead, aboutBarqMilestonesControllerReadOne, aboutBarqMilestonesControllerUpdate, aboutBarqMilestonesControllerDelete } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { AboutBarqMilestonesControllerCreateData, AboutBarqMilestonesControllerCreateError, AboutBarqMilestonesControllerCreateResponse, AboutBarqMilestonesControllerReadData, AboutBarqMilestonesControllerReadResponse, AboutBarqMilestonesControllerReadOneData, AboutBarqMilestonesControllerReadOneResponse, AboutBarqMilestonesControllerUpdateData, AboutBarqMilestonesControllerUpdateError, AboutBarqMilestonesControllerUpdateResponse, AboutBarqMilestonesControllerDeleteData, AboutBarqMilestonesControllerDeleteError, AboutBarqMilestonesControllerDeleteResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const aboutBarqMilestonesControllerCreateMutation = <TResponse = AboutBarqMilestonesControllerCreateResponse>(options?: Partial<OptionsLegacyParser<AboutBarqMilestonesControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, AboutBarqMilestonesControllerCreateError, OptionsLegacyParser<AboutBarqMilestonesControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AboutBarqMilestonesControllerCreateError, OptionsLegacyParser<AboutBarqMilestonesControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await aboutBarqMilestonesControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAboutBarqMilestonesControllerCreate = <TResponse = AboutBarqMilestonesControllerCreateResponse>(dataOptions?: OptionsLegacyParser<AboutBarqMilestonesControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, AboutBarqMilestonesControllerCreateError, OptionsLegacyParser<AboutBarqMilestonesControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...aboutBarqMilestonesControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const aboutBarqMilestonesControllerReadQueryKey = (options: OptionsLegacyParser<AboutBarqMilestonesControllerReadData>) => [
    createQueryKey('aboutBarqMilestonesControllerRead', options)
];
export const aboutBarqMilestonesControllerReadOptions = <TResponse = AboutBarqMilestonesControllerReadResponse>(options?: OptionsLegacyParser<AboutBarqMilestonesControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await aboutBarqMilestonesControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: aboutBarqMilestonesControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useAboutBarqMilestonesControllerReadQuery = <TResponse = AboutBarqMilestonesControllerReadResponse>(dataOptions?: OptionsLegacyParser<AboutBarqMilestonesControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...aboutBarqMilestonesControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const aboutBarqMilestonesControllerReadOneQueryKey = (options: OptionsLegacyParser<AboutBarqMilestonesControllerReadOneData>) => [
    createQueryKey('aboutBarqMilestonesControllerReadOne', options)
];
export const aboutBarqMilestonesControllerReadOneOptions = <TResponse = AboutBarqMilestonesControllerReadOneResponse>(options?: OptionsLegacyParser<AboutBarqMilestonesControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await aboutBarqMilestonesControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: aboutBarqMilestonesControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useAboutBarqMilestonesControllerReadOneQuery = <TResponse = AboutBarqMilestonesControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<AboutBarqMilestonesControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...aboutBarqMilestonesControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};
export const aboutBarqMilestonesControllerUpdateMutation = <TResponse = AboutBarqMilestonesControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<AboutBarqMilestonesControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, AboutBarqMilestonesControllerUpdateError, OptionsLegacyParser<AboutBarqMilestonesControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AboutBarqMilestonesControllerUpdateError, OptionsLegacyParser<AboutBarqMilestonesControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await aboutBarqMilestonesControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAboutBarqMilestonesControllerUpdate = <TResponse = AboutBarqMilestonesControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<AboutBarqMilestonesControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, AboutBarqMilestonesControllerUpdateError, OptionsLegacyParser<AboutBarqMilestonesControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...aboutBarqMilestonesControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const aboutBarqMilestonesControllerDeleteMutation = <TResponse = AboutBarqMilestonesControllerDeleteResponse>(options?: Partial<OptionsLegacyParser<AboutBarqMilestonesControllerDeleteData>>, hookOptions?: Omit<MutationOptions<TResponse, AboutBarqMilestonesControllerDeleteError, OptionsLegacyParser<AboutBarqMilestonesControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AboutBarqMilestonesControllerDeleteError, OptionsLegacyParser<AboutBarqMilestonesControllerDeleteData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await aboutBarqMilestonesControllerDelete({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAboutBarqMilestonesControllerDelete = <TResponse = AboutBarqMilestonesControllerDeleteResponse>(dataOptions?: OptionsLegacyParser<AboutBarqMilestonesControllerDeleteData>, hookOptions?: Omit<MutationOptions<TResponse, AboutBarqMilestonesControllerDeleteError, OptionsLegacyParser<AboutBarqMilestonesControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...aboutBarqMilestonesControllerDeleteMutation(dataOptions ?? {}, hookOptions)
    });
};