// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, aboutBarqMissionVisionControllerCreate, aboutBarqMissionVisionControllerRead, aboutBarqMissionVisionControllerReadOne, aboutBarqMissionVisionControllerUpdate, aboutBarqMissionVisionControllerDelete } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { AboutBarqMissionVisionControllerCreateData, AboutBarqMissionVisionControllerCreateError, AboutBarqMissionVisionControllerCreateResponse, AboutBarqMissionVisionControllerReadData, AboutBarqMissionVisionControllerReadResponse, AboutBarqMissionVisionControllerReadOneData, AboutBarqMissionVisionControllerReadOneResponse, AboutBarqMissionVisionControllerUpdateData, AboutBarqMissionVisionControllerUpdateError, AboutBarqMissionVisionControllerUpdateResponse, AboutBarqMissionVisionControllerDeleteData, AboutBarqMissionVisionControllerDeleteError, AboutBarqMissionVisionControllerDeleteResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const aboutBarqMissionVisionControllerCreateMutation = <TResponse = AboutBarqMissionVisionControllerCreateResponse>(options?: Partial<OptionsLegacyParser<AboutBarqMissionVisionControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, AboutBarqMissionVisionControllerCreateError, OptionsLegacyParser<AboutBarqMissionVisionControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AboutBarqMissionVisionControllerCreateError, OptionsLegacyParser<AboutBarqMissionVisionControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await aboutBarqMissionVisionControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAboutBarqMissionVisionControllerCreate = <TResponse = AboutBarqMissionVisionControllerCreateResponse>(dataOptions?: OptionsLegacyParser<AboutBarqMissionVisionControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, AboutBarqMissionVisionControllerCreateError, OptionsLegacyParser<AboutBarqMissionVisionControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...aboutBarqMissionVisionControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const aboutBarqMissionVisionControllerReadQueryKey = (options: OptionsLegacyParser<AboutBarqMissionVisionControllerReadData>) => [
    createQueryKey('aboutBarqMissionVisionControllerRead', options)
];
export const aboutBarqMissionVisionControllerReadOptions = <TResponse = AboutBarqMissionVisionControllerReadResponse>(options?: OptionsLegacyParser<AboutBarqMissionVisionControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await aboutBarqMissionVisionControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: aboutBarqMissionVisionControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useAboutBarqMissionVisionControllerReadQuery = <TResponse = AboutBarqMissionVisionControllerReadResponse>(dataOptions?: OptionsLegacyParser<AboutBarqMissionVisionControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...aboutBarqMissionVisionControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const aboutBarqMissionVisionControllerReadOneQueryKey = (options: OptionsLegacyParser<AboutBarqMissionVisionControllerReadOneData>) => [
    createQueryKey('aboutBarqMissionVisionControllerReadOne', options)
];
export const aboutBarqMissionVisionControllerReadOneOptions = <TResponse = AboutBarqMissionVisionControllerReadOneResponse>(options?: OptionsLegacyParser<AboutBarqMissionVisionControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await aboutBarqMissionVisionControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: aboutBarqMissionVisionControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useAboutBarqMissionVisionControllerReadOneQuery = <TResponse = AboutBarqMissionVisionControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<AboutBarqMissionVisionControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...aboutBarqMissionVisionControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};
export const aboutBarqMissionVisionControllerUpdateMutation = <TResponse = AboutBarqMissionVisionControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<AboutBarqMissionVisionControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, AboutBarqMissionVisionControllerUpdateError, OptionsLegacyParser<AboutBarqMissionVisionControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AboutBarqMissionVisionControllerUpdateError, OptionsLegacyParser<AboutBarqMissionVisionControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await aboutBarqMissionVisionControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAboutBarqMissionVisionControllerUpdate = <TResponse = AboutBarqMissionVisionControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<AboutBarqMissionVisionControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, AboutBarqMissionVisionControllerUpdateError, OptionsLegacyParser<AboutBarqMissionVisionControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...aboutBarqMissionVisionControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const aboutBarqMissionVisionControllerDeleteMutation = <TResponse = AboutBarqMissionVisionControllerDeleteResponse>(options?: Partial<OptionsLegacyParser<AboutBarqMissionVisionControllerDeleteData>>, hookOptions?: Omit<MutationOptions<TResponse, AboutBarqMissionVisionControllerDeleteError, OptionsLegacyParser<AboutBarqMissionVisionControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AboutBarqMissionVisionControllerDeleteError, OptionsLegacyParser<AboutBarqMissionVisionControllerDeleteData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await aboutBarqMissionVisionControllerDelete({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAboutBarqMissionVisionControllerDelete = <TResponse = AboutBarqMissionVisionControllerDeleteResponse>(dataOptions?: OptionsLegacyParser<AboutBarqMissionVisionControllerDeleteData>, hookOptions?: Omit<MutationOptions<TResponse, AboutBarqMissionVisionControllerDeleteError, OptionsLegacyParser<AboutBarqMissionVisionControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...aboutBarqMissionVisionControllerDeleteMutation(dataOptions ?? {}, hookOptions)
    });
};