// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, aboutBarqGroupAffiliationControllerCreate, aboutBarqGroupAffiliationControllerRead, aboutBarqGroupAffiliationControllerReadOne, aboutBarqGroupAffiliationControllerUpdate } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { AboutBarqGroupAffiliationControllerCreateData, AboutBarqGroupAffiliationControllerCreateError, AboutBarqGroupAffiliationControllerCreateResponse, AboutBarqGroupAffiliationControllerReadData, AboutBarqGroupAffiliationControllerReadResponse, AboutBarqGroupAffiliationControllerReadOneData, AboutBarqGroupAffiliationControllerReadOneResponse, AboutBarqGroupAffiliationControllerUpdateData, AboutBarqGroupAffiliationControllerUpdateError, AboutBarqGroupAffiliationControllerUpdateResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const aboutBarqGroupAffiliationControllerCreateMutation = <TResponse = AboutBarqGroupAffiliationControllerCreateResponse>(options?: Partial<OptionsLegacyParser<AboutBarqGroupAffiliationControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, AboutBarqGroupAffiliationControllerCreateError, OptionsLegacyParser<AboutBarqGroupAffiliationControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AboutBarqGroupAffiliationControllerCreateError, OptionsLegacyParser<AboutBarqGroupAffiliationControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await aboutBarqGroupAffiliationControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAboutBarqGroupAffiliationControllerCreate = <TResponse = AboutBarqGroupAffiliationControllerCreateResponse>(dataOptions?: OptionsLegacyParser<AboutBarqGroupAffiliationControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, AboutBarqGroupAffiliationControllerCreateError, OptionsLegacyParser<AboutBarqGroupAffiliationControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...aboutBarqGroupAffiliationControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const aboutBarqGroupAffiliationControllerReadQueryKey = (options: OptionsLegacyParser<AboutBarqGroupAffiliationControllerReadData>) => [
    createQueryKey('aboutBarqGroupAffiliationControllerRead', options)
];
export const aboutBarqGroupAffiliationControllerReadOptions = <TResponse = AboutBarqGroupAffiliationControllerReadResponse>(options?: OptionsLegacyParser<AboutBarqGroupAffiliationControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await aboutBarqGroupAffiliationControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: aboutBarqGroupAffiliationControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useAboutBarqGroupAffiliationControllerReadQuery = <TResponse = AboutBarqGroupAffiliationControllerReadResponse>(dataOptions?: OptionsLegacyParser<AboutBarqGroupAffiliationControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...aboutBarqGroupAffiliationControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const aboutBarqGroupAffiliationControllerReadOneQueryKey = (options: OptionsLegacyParser<AboutBarqGroupAffiliationControllerReadOneData>) => [
    createQueryKey('aboutBarqGroupAffiliationControllerReadOne', options)
];
export const aboutBarqGroupAffiliationControllerReadOneOptions = <TResponse = AboutBarqGroupAffiliationControllerReadOneResponse>(options?: OptionsLegacyParser<AboutBarqGroupAffiliationControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await aboutBarqGroupAffiliationControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: aboutBarqGroupAffiliationControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useAboutBarqGroupAffiliationControllerReadOneQuery = <TResponse = AboutBarqGroupAffiliationControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<AboutBarqGroupAffiliationControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...aboutBarqGroupAffiliationControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};
export const aboutBarqGroupAffiliationControllerUpdateMutation = <TResponse = AboutBarqGroupAffiliationControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<AboutBarqGroupAffiliationControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, AboutBarqGroupAffiliationControllerUpdateError, OptionsLegacyParser<AboutBarqGroupAffiliationControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AboutBarqGroupAffiliationControllerUpdateError, OptionsLegacyParser<AboutBarqGroupAffiliationControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await aboutBarqGroupAffiliationControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAboutBarqGroupAffiliationControllerUpdate = <TResponse = AboutBarqGroupAffiliationControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<AboutBarqGroupAffiliationControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, AboutBarqGroupAffiliationControllerUpdateError, OptionsLegacyParser<AboutBarqGroupAffiliationControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...aboutBarqGroupAffiliationControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};