// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, additionalManagedServicesOneControllerCreate, additionalManagedServicesOneControllerRead, additionalManagedServicesOneControllerReadOne, additionalManagedServicesOneControllerUpdate, additionalManagedServicesOneControllerDelete } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { AdditionalManagedServicesOneControllerCreateData, AdditionalManagedServicesOneControllerCreateError, AdditionalManagedServicesOneControllerCreateResponse, AdditionalManagedServicesOneControllerReadData, AdditionalManagedServicesOneControllerReadResponse, AdditionalManagedServicesOneControllerReadOneData, AdditionalManagedServicesOneControllerReadOneResponse, AdditionalManagedServicesOneControllerUpdateData, AdditionalManagedServicesOneControllerUpdateError, AdditionalManagedServicesOneControllerUpdateResponse, AdditionalManagedServicesOneControllerDeleteData, AdditionalManagedServicesOneControllerDeleteError, AdditionalManagedServicesOneControllerDeleteResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const additionalManagedServicesOneControllerCreateMutation = <TResponse = AdditionalManagedServicesOneControllerCreateResponse>(options?: Partial<OptionsLegacyParser<AdditionalManagedServicesOneControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, AdditionalManagedServicesOneControllerCreateError, OptionsLegacyParser<AdditionalManagedServicesOneControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AdditionalManagedServicesOneControllerCreateError, OptionsLegacyParser<AdditionalManagedServicesOneControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await additionalManagedServicesOneControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAdditionalManagedServicesOneControllerCreate = <TResponse = AdditionalManagedServicesOneControllerCreateResponse>(dataOptions?: OptionsLegacyParser<AdditionalManagedServicesOneControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, AdditionalManagedServicesOneControllerCreateError, OptionsLegacyParser<AdditionalManagedServicesOneControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...additionalManagedServicesOneControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const additionalManagedServicesOneControllerReadQueryKey = (options: OptionsLegacyParser<AdditionalManagedServicesOneControllerReadData>) => [
    createQueryKey('additionalManagedServicesOneControllerRead', options)
];
export const additionalManagedServicesOneControllerReadOptions = <TResponse = AdditionalManagedServicesOneControllerReadResponse>(options?: OptionsLegacyParser<AdditionalManagedServicesOneControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await additionalManagedServicesOneControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: additionalManagedServicesOneControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useAdditionalManagedServicesOneControllerReadQuery = <TResponse = AdditionalManagedServicesOneControllerReadResponse>(dataOptions?: OptionsLegacyParser<AdditionalManagedServicesOneControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...additionalManagedServicesOneControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const additionalManagedServicesOneControllerReadOneQueryKey = (options: OptionsLegacyParser<AdditionalManagedServicesOneControllerReadOneData>) => [
    createQueryKey('additionalManagedServicesOneControllerReadOne', options)
];
export const additionalManagedServicesOneControllerReadOneOptions = <TResponse = AdditionalManagedServicesOneControllerReadOneResponse>(options?: OptionsLegacyParser<AdditionalManagedServicesOneControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await additionalManagedServicesOneControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: additionalManagedServicesOneControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useAdditionalManagedServicesOneControllerReadOneQuery = <TResponse = AdditionalManagedServicesOneControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<AdditionalManagedServicesOneControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...additionalManagedServicesOneControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};
export const additionalManagedServicesOneControllerUpdateMutation = <TResponse = AdditionalManagedServicesOneControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<AdditionalManagedServicesOneControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, AdditionalManagedServicesOneControllerUpdateError, OptionsLegacyParser<AdditionalManagedServicesOneControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AdditionalManagedServicesOneControllerUpdateError, OptionsLegacyParser<AdditionalManagedServicesOneControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await additionalManagedServicesOneControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAdditionalManagedServicesOneControllerUpdate = <TResponse = AdditionalManagedServicesOneControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<AdditionalManagedServicesOneControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, AdditionalManagedServicesOneControllerUpdateError, OptionsLegacyParser<AdditionalManagedServicesOneControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...additionalManagedServicesOneControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const additionalManagedServicesOneControllerDeleteMutation = <TResponse = AdditionalManagedServicesOneControllerDeleteResponse>(options?: Partial<OptionsLegacyParser<AdditionalManagedServicesOneControllerDeleteData>>, hookOptions?: Omit<MutationOptions<TResponse, AdditionalManagedServicesOneControllerDeleteError, OptionsLegacyParser<AdditionalManagedServicesOneControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AdditionalManagedServicesOneControllerDeleteError, OptionsLegacyParser<AdditionalManagedServicesOneControllerDeleteData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await additionalManagedServicesOneControllerDelete({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAdditionalManagedServicesOneControllerDelete = <TResponse = AdditionalManagedServicesOneControllerDeleteResponse>(dataOptions?: OptionsLegacyParser<AdditionalManagedServicesOneControllerDeleteData>, hookOptions?: Omit<MutationOptions<TResponse, AdditionalManagedServicesOneControllerDeleteError, OptionsLegacyParser<AdditionalManagedServicesOneControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...additionalManagedServicesOneControllerDeleteMutation(dataOptions ?? {}, hookOptions)
    });
};