// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, alliancesVendorsControllerCreate, alliancesVendorsControllerRead, alliancesVendorsControllerUpdate, alliancesVendorsControllerReadOne, alliancesVendorsControllerDelete } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { AlliancesVendorsControllerCreateData, AlliancesVendorsControllerCreateError, AlliancesVendorsControllerCreateResponse, AlliancesVendorsControllerReadData, AlliancesVendorsControllerReadResponse, AlliancesVendorsControllerUpdateData, AlliancesVendorsControllerUpdateError, AlliancesVendorsControllerUpdateResponse, AlliancesVendorsControllerReadOneData, AlliancesVendorsControllerReadOneResponse, AlliancesVendorsControllerDeleteData, AlliancesVendorsControllerDeleteError, AlliancesVendorsControllerDeleteResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const alliancesVendorsControllerCreateMutation = <TResponse = AlliancesVendorsControllerCreateResponse>(options?: Partial<OptionsLegacyParser<AlliancesVendorsControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, AlliancesVendorsControllerCreateError, OptionsLegacyParser<AlliancesVendorsControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AlliancesVendorsControllerCreateError, OptionsLegacyParser<AlliancesVendorsControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await alliancesVendorsControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAlliancesVendorsControllerCreate = <TResponse = AlliancesVendorsControllerCreateResponse>(dataOptions?: OptionsLegacyParser<AlliancesVendorsControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, AlliancesVendorsControllerCreateError, OptionsLegacyParser<AlliancesVendorsControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...alliancesVendorsControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const alliancesVendorsControllerReadQueryKey = (options: OptionsLegacyParser<AlliancesVendorsControllerReadData>) => [
    createQueryKey('alliancesVendorsControllerRead', options)
];
export const alliancesVendorsControllerReadOptions = <TResponse = AlliancesVendorsControllerReadResponse>(options?: OptionsLegacyParser<AlliancesVendorsControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await alliancesVendorsControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: alliancesVendorsControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useAlliancesVendorsControllerReadQuery = <TResponse = AlliancesVendorsControllerReadResponse>(dataOptions?: OptionsLegacyParser<AlliancesVendorsControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...alliancesVendorsControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const alliancesVendorsControllerUpdateMutation = <TResponse = AlliancesVendorsControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<AlliancesVendorsControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, AlliancesVendorsControllerUpdateError, OptionsLegacyParser<AlliancesVendorsControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AlliancesVendorsControllerUpdateError, OptionsLegacyParser<AlliancesVendorsControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await alliancesVendorsControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAlliancesVendorsControllerUpdate = <TResponse = AlliancesVendorsControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<AlliancesVendorsControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, AlliancesVendorsControllerUpdateError, OptionsLegacyParser<AlliancesVendorsControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...alliancesVendorsControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const alliancesVendorsControllerReadOneQueryKey = (options: OptionsLegacyParser<AlliancesVendorsControllerReadOneData>) => [
    createQueryKey('alliancesVendorsControllerReadOne', options)
];
export const alliancesVendorsControllerReadOneOptions = <TResponse = AlliancesVendorsControllerReadOneResponse>(options?: OptionsLegacyParser<AlliancesVendorsControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await alliancesVendorsControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: alliancesVendorsControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useAlliancesVendorsControllerReadOneQuery = <TResponse = AlliancesVendorsControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<AlliancesVendorsControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...alliancesVendorsControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};
export const alliancesVendorsControllerDeleteMutation = <TResponse = AlliancesVendorsControllerDeleteResponse>(options?: Partial<OptionsLegacyParser<AlliancesVendorsControllerDeleteData>>, hookOptions?: Omit<MutationOptions<TResponse, AlliancesVendorsControllerDeleteError, OptionsLegacyParser<AlliancesVendorsControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AlliancesVendorsControllerDeleteError, OptionsLegacyParser<AlliancesVendorsControllerDeleteData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await alliancesVendorsControllerDelete({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAlliancesVendorsControllerDelete = <TResponse = AlliancesVendorsControllerDeleteResponse>(dataOptions?: OptionsLegacyParser<AlliancesVendorsControllerDeleteData>, hookOptions?: Omit<MutationOptions<TResponse, AlliancesVendorsControllerDeleteError, OptionsLegacyParser<AlliancesVendorsControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...alliancesVendorsControllerDeleteMutation(dataOptions ?? {}, hookOptions)
    });
};