// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, alliancesHeadControllerCreate, alliancesHeadControllerRead, alliancesHeadControllerUpdate, alliancesHeadControllerReadOne } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { AlliancesHeadControllerCreateData, AlliancesHeadControllerCreateError, AlliancesHeadControllerCreateResponse, AlliancesHeadControllerReadData, AlliancesHeadControllerReadResponse, AlliancesHeadControllerUpdateData, AlliancesHeadControllerUpdateError, AlliancesHeadControllerUpdateResponse, AlliancesHeadControllerReadOneData, AlliancesHeadControllerReadOneResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const alliancesHeadControllerCreateMutation = <TResponse = AlliancesHeadControllerCreateResponse>(options?: Partial<OptionsLegacyParser<AlliancesHeadControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, AlliancesHeadControllerCreateError, OptionsLegacyParser<AlliancesHeadControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AlliancesHeadControllerCreateError, OptionsLegacyParser<AlliancesHeadControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await alliancesHeadControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAlliancesHeadControllerCreate = <TResponse = AlliancesHeadControllerCreateResponse>(dataOptions?: OptionsLegacyParser<AlliancesHeadControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, AlliancesHeadControllerCreateError, OptionsLegacyParser<AlliancesHeadControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...alliancesHeadControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const alliancesHeadControllerReadQueryKey = (options: OptionsLegacyParser<AlliancesHeadControllerReadData>) => [
    createQueryKey('alliancesHeadControllerRead', options)
];
export const alliancesHeadControllerReadOptions = <TResponse = AlliancesHeadControllerReadResponse>(options?: OptionsLegacyParser<AlliancesHeadControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await alliancesHeadControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: alliancesHeadControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useAlliancesHeadControllerReadQuery = <TResponse = AlliancesHeadControllerReadResponse>(dataOptions?: OptionsLegacyParser<AlliancesHeadControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...alliancesHeadControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const alliancesHeadControllerUpdateMutation = <TResponse = AlliancesHeadControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<AlliancesHeadControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, AlliancesHeadControllerUpdateError, OptionsLegacyParser<AlliancesHeadControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AlliancesHeadControllerUpdateError, OptionsLegacyParser<AlliancesHeadControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await alliancesHeadControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAlliancesHeadControllerUpdate = <TResponse = AlliancesHeadControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<AlliancesHeadControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, AlliancesHeadControllerUpdateError, OptionsLegacyParser<AlliancesHeadControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...alliancesHeadControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const alliancesHeadControllerReadOneQueryKey = (options: OptionsLegacyParser<AlliancesHeadControllerReadOneData>) => [
    createQueryKey('alliancesHeadControllerReadOne', options)
];
export const alliancesHeadControllerReadOneOptions = <TResponse = AlliancesHeadControllerReadOneResponse>(options?: OptionsLegacyParser<AlliancesHeadControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await alliancesHeadControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: alliancesHeadControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useAlliancesHeadControllerReadOneQuery = <TResponse = AlliancesHeadControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<AlliancesHeadControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...alliancesHeadControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};