// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, authControllerVerifyOtp, authControllerResendOtp, authControllerSignin, authControllerForgetPassword, authControllerCompleteForgetPassword, authControllerLogout, authControllerRefreshToken, authControllerVerifyLink, authControllerResendLink, authControllerCompletePassword } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions } from '@tanstack/react-query';
import type { AuthControllerVerifyOtpError, AuthControllerVerifyOtpResponse, AuthControllerResendOtpError, AuthControllerResendOtpResponse, AuthControllerSigninError, AuthControllerSigninResponse, AuthControllerForgetPasswordError, AuthControllerForgetPasswordResponse, AuthControllerCompleteForgetPasswordError, AuthControllerCompleteForgetPasswordResponse, AuthControllerLogoutError, AuthControllerLogoutResponse, AuthControllerRefreshTokenError, AuthControllerRefreshTokenResponse, AuthControllerVerifyLinkError, AuthControllerVerifyLinkResponse, AuthControllerResendLinkError, AuthControllerResendLinkResponse, AuthControllerCompletePasswordError, AuthControllerCompletePasswordResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const authControllerVerifyOtpMutation = <TResponse = AuthControllerVerifyOtpResponse>(options?: Partial<OptionsLegacyParser>, hookOptions?: Omit<MutationOptions<TResponse, AuthControllerVerifyOtpError, OptionsLegacyParser>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AuthControllerVerifyOtpError, OptionsLegacyParser> = {
        mutationFn: async (localOptions) => {
            const { data } = await authControllerVerifyOtp({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAuthControllerVerifyOtp = <TResponse = AuthControllerVerifyOtpResponse>(dataOptions?: OptionsLegacyParser, hookOptions?: Omit<MutationOptions<TResponse, AuthControllerVerifyOtpError, OptionsLegacyParser>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...authControllerVerifyOtpMutation(dataOptions ?? {}, hookOptions)
    });
};
export const authControllerResendOtpMutation = <TResponse = AuthControllerResendOtpResponse>(options?: Partial<OptionsLegacyParser>, hookOptions?: Omit<MutationOptions<TResponse, AuthControllerResendOtpError, OptionsLegacyParser>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AuthControllerResendOtpError, OptionsLegacyParser> = {
        mutationFn: async (localOptions) => {
            const { data } = await authControllerResendOtp({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAuthControllerResendOtp = <TResponse = AuthControllerResendOtpResponse>(dataOptions?: OptionsLegacyParser, hookOptions?: Omit<MutationOptions<TResponse, AuthControllerResendOtpError, OptionsLegacyParser>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...authControllerResendOtpMutation(dataOptions ?? {}, hookOptions)
    });
};
export const authControllerSigninMutation = <TResponse = AuthControllerSigninResponse>(options?: Partial<OptionsLegacyParser>, hookOptions?: Omit<MutationOptions<TResponse, AuthControllerSigninError, OptionsLegacyParser>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AuthControllerSigninError, OptionsLegacyParser> = {
        mutationFn: async (localOptions) => {
            const { data } = await authControllerSignin({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAuthControllerSignin = <TResponse = AuthControllerSigninResponse>(dataOptions?: OptionsLegacyParser, hookOptions?: Omit<MutationOptions<TResponse, AuthControllerSigninError, OptionsLegacyParser>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...authControllerSigninMutation(dataOptions ?? {}, hookOptions)
    });
};
export const authControllerForgetPasswordMutation = <TResponse = AuthControllerForgetPasswordResponse>(options?: Partial<OptionsLegacyParser>, hookOptions?: Omit<MutationOptions<TResponse, AuthControllerForgetPasswordError, OptionsLegacyParser>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AuthControllerForgetPasswordError, OptionsLegacyParser> = {
        mutationFn: async (localOptions) => {
            const { data } = await authControllerForgetPassword({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAuthControllerForgetPassword = <TResponse = AuthControllerForgetPasswordResponse>(dataOptions?: OptionsLegacyParser, hookOptions?: Omit<MutationOptions<TResponse, AuthControllerForgetPasswordError, OptionsLegacyParser>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...authControllerForgetPasswordMutation(dataOptions ?? {}, hookOptions)
    });
};
export const authControllerCompleteForgetPasswordMutation = <TResponse = AuthControllerCompleteForgetPasswordResponse>(options?: Partial<OptionsLegacyParser>, hookOptions?: Omit<MutationOptions<TResponse, AuthControllerCompleteForgetPasswordError, OptionsLegacyParser>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AuthControllerCompleteForgetPasswordError, OptionsLegacyParser> = {
        mutationFn: async (localOptions) => {
            const { data } = await authControllerCompleteForgetPassword({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAuthControllerCompleteForgetPassword = <TResponse = AuthControllerCompleteForgetPasswordResponse>(dataOptions?: OptionsLegacyParser, hookOptions?: Omit<MutationOptions<TResponse, AuthControllerCompleteForgetPasswordError, OptionsLegacyParser>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...authControllerCompleteForgetPasswordMutation(dataOptions ?? {}, hookOptions)
    });
};
export const authControllerLogoutMutation = <TResponse = AuthControllerLogoutResponse>(options?: Partial<OptionsLegacyParser>, hookOptions?: Omit<MutationOptions<TResponse, AuthControllerLogoutError, OptionsLegacyParser>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AuthControllerLogoutError, OptionsLegacyParser> = {
        mutationFn: async (localOptions) => {
            const { data } = await authControllerLogout({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAuthControllerLogout = <TResponse = AuthControllerLogoutResponse>(dataOptions?: OptionsLegacyParser, hookOptions?: Omit<MutationOptions<TResponse, AuthControllerLogoutError, OptionsLegacyParser>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...authControllerLogoutMutation(dataOptions ?? {}, hookOptions)
    });
};
export const authControllerRefreshTokenMutation = <TResponse = AuthControllerRefreshTokenResponse>(options?: Partial<OptionsLegacyParser>, hookOptions?: Omit<MutationOptions<TResponse, AuthControllerRefreshTokenError, OptionsLegacyParser>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AuthControllerRefreshTokenError, OptionsLegacyParser> = {
        mutationFn: async (localOptions) => {
            const { data } = await authControllerRefreshToken({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAuthControllerRefreshToken = <TResponse = AuthControllerRefreshTokenResponse>(dataOptions?: OptionsLegacyParser, hookOptions?: Omit<MutationOptions<TResponse, AuthControllerRefreshTokenError, OptionsLegacyParser>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...authControllerRefreshTokenMutation(dataOptions ?? {}, hookOptions)
    });
};
export const authControllerVerifyLinkMutation = <TResponse = AuthControllerVerifyLinkResponse>(options?: Partial<OptionsLegacyParser>, hookOptions?: Omit<MutationOptions<TResponse, AuthControllerVerifyLinkError, OptionsLegacyParser>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AuthControllerVerifyLinkError, OptionsLegacyParser> = {
        mutationFn: async (localOptions) => {
            const { data } = await authControllerVerifyLink({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAuthControllerVerifyLink = <TResponse = AuthControllerVerifyLinkResponse>(dataOptions?: OptionsLegacyParser, hookOptions?: Omit<MutationOptions<TResponse, AuthControllerVerifyLinkError, OptionsLegacyParser>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...authControllerVerifyLinkMutation(dataOptions ?? {}, hookOptions)
    });
};
export const authControllerResendLinkMutation = <TResponse = AuthControllerResendLinkResponse>(options?: Partial<OptionsLegacyParser>, hookOptions?: Omit<MutationOptions<TResponse, AuthControllerResendLinkError, OptionsLegacyParser>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AuthControllerResendLinkError, OptionsLegacyParser> = {
        mutationFn: async (localOptions) => {
            const { data } = await authControllerResendLink({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAuthControllerResendLink = <TResponse = AuthControllerResendLinkResponse>(dataOptions?: OptionsLegacyParser, hookOptions?: Omit<MutationOptions<TResponse, AuthControllerResendLinkError, OptionsLegacyParser>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...authControllerResendLinkMutation(dataOptions ?? {}, hookOptions)
    });
};
export const authControllerCompletePasswordMutation = <TResponse = AuthControllerCompletePasswordResponse>(options?: Partial<OptionsLegacyParser>, hookOptions?: Omit<MutationOptions<TResponse, AuthControllerCompletePasswordError, OptionsLegacyParser>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AuthControllerCompletePasswordError, OptionsLegacyParser> = {
        mutationFn: async (localOptions) => {
            const { data } = await authControllerCompletePassword({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAuthControllerCompletePassword = <TResponse = AuthControllerCompletePasswordResponse>(dataOptions?: OptionsLegacyParser, hookOptions?: Omit<MutationOptions<TResponse, AuthControllerCompletePasswordError, OptionsLegacyParser>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...authControllerCompletePasswordMutation(dataOptions ?? {}, hookOptions)
    });
};