// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, awardsCardsControllerCreate, awardsCardsControllerRead, awardsCardsControllerUpdate, awardsCardsControllerReadOne, awardsCardsControllerDelete } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { AwardsCardsControllerCreateData, AwardsCardsControllerCreateError, AwardsCardsControllerCreateResponse, AwardsCardsControllerReadData, AwardsCardsControllerReadResponse, AwardsCardsControllerUpdateData, AwardsCardsControllerUpdateError, AwardsCardsControllerUpdateResponse, AwardsCardsControllerReadOneData, AwardsCardsControllerReadOneResponse, AwardsCardsControllerDeleteData, AwardsCardsControllerDeleteError, AwardsCardsControllerDeleteResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const awardsCardsControllerCreateMutation = <TResponse = AwardsCardsControllerCreateResponse>(options?: Partial<OptionsLegacyParser<AwardsCardsControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, AwardsCardsControllerCreateError, OptionsLegacyParser<AwardsCardsControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AwardsCardsControllerCreateError, OptionsLegacyParser<AwardsCardsControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await awardsCardsControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAwardsCardsControllerCreate = <TResponse = AwardsCardsControllerCreateResponse>(dataOptions?: OptionsLegacyParser<AwardsCardsControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, AwardsCardsControllerCreateError, OptionsLegacyParser<AwardsCardsControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...awardsCardsControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const awardsCardsControllerReadQueryKey = (options: OptionsLegacyParser<AwardsCardsControllerReadData>) => [
    createQueryKey('awardsCardsControllerRead', options)
];
export const awardsCardsControllerReadOptions = <TResponse = AwardsCardsControllerReadResponse>(options?: OptionsLegacyParser<AwardsCardsControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await awardsCardsControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: awardsCardsControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useAwardsCardsControllerReadQuery = <TResponse = AwardsCardsControllerReadResponse>(dataOptions?: OptionsLegacyParser<AwardsCardsControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...awardsCardsControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const awardsCardsControllerUpdateMutation = <TResponse = AwardsCardsControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<AwardsCardsControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, AwardsCardsControllerUpdateError, OptionsLegacyParser<AwardsCardsControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AwardsCardsControllerUpdateError, OptionsLegacyParser<AwardsCardsControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await awardsCardsControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAwardsCardsControllerUpdate = <TResponse = AwardsCardsControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<AwardsCardsControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, AwardsCardsControllerUpdateError, OptionsLegacyParser<AwardsCardsControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...awardsCardsControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const awardsCardsControllerReadOneQueryKey = (options: OptionsLegacyParser<AwardsCardsControllerReadOneData>) => [
    createQueryKey('awardsCardsControllerReadOne', options)
];
export const awardsCardsControllerReadOneOptions = <TResponse = AwardsCardsControllerReadOneResponse>(options?: OptionsLegacyParser<AwardsCardsControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await awardsCardsControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: awardsCardsControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useAwardsCardsControllerReadOneQuery = <TResponse = AwardsCardsControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<AwardsCardsControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...awardsCardsControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};
export const awardsCardsControllerDeleteMutation = <TResponse = AwardsCardsControllerDeleteResponse>(options?: Partial<OptionsLegacyParser<AwardsCardsControllerDeleteData>>, hookOptions?: Omit<MutationOptions<TResponse, AwardsCardsControllerDeleteError, OptionsLegacyParser<AwardsCardsControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, AwardsCardsControllerDeleteError, OptionsLegacyParser<AwardsCardsControllerDeleteData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await awardsCardsControllerDelete({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useAwardsCardsControllerDelete = <TResponse = AwardsCardsControllerDeleteResponse>(dataOptions?: OptionsLegacyParser<AwardsCardsControllerDeleteData>, hookOptions?: Omit<MutationOptions<TResponse, AwardsCardsControllerDeleteError, OptionsLegacyParser<AwardsCardsControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...awardsCardsControllerDeleteMutation(dataOptions ?? {}, hookOptions)
    });
};