// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, barqAcademyFoundationTracksFormControllerCreate, barqAcademyFoundationTracksFormControllerRead, barqAcademyFoundationTracksFormControllerUpdate, barqAcademyFoundationTracksFormControllerReadOne } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { BarqAcademyFoundationTracksFormControllerCreateData, BarqAcademyFoundationTracksFormControllerCreateError, BarqAcademyFoundationTracksFormControllerCreateResponse, BarqAcademyFoundationTracksFormControllerReadData, BarqAcademyFoundationTracksFormControllerReadResponse, BarqAcademyFoundationTracksFormControllerUpdateData, BarqAcademyFoundationTracksFormControllerUpdateError, BarqAcademyFoundationTracksFormControllerUpdateResponse, BarqAcademyFoundationTracksFormControllerReadOneData, BarqAcademyFoundationTracksFormControllerReadOneResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const barqAcademyFoundationTracksFormControllerCreateMutation = <TResponse = BarqAcademyFoundationTracksFormControllerCreateResponse>(options?: Partial<OptionsLegacyParser<BarqAcademyFoundationTracksFormControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, BarqAcademyFoundationTracksFormControllerCreateError, OptionsLegacyParser<BarqAcademyFoundationTracksFormControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, BarqAcademyFoundationTracksFormControllerCreateError, OptionsLegacyParser<BarqAcademyFoundationTracksFormControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await barqAcademyFoundationTracksFormControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useBarqAcademyFoundationTracksFormControllerCreate = <TResponse = BarqAcademyFoundationTracksFormControllerCreateResponse>(dataOptions?: OptionsLegacyParser<BarqAcademyFoundationTracksFormControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, BarqAcademyFoundationTracksFormControllerCreateError, OptionsLegacyParser<BarqAcademyFoundationTracksFormControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...barqAcademyFoundationTracksFormControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const barqAcademyFoundationTracksFormControllerReadQueryKey = (options: OptionsLegacyParser<BarqAcademyFoundationTracksFormControllerReadData>) => [
    createQueryKey('barqAcademyFoundationTracksFormControllerRead', options)
];
export const barqAcademyFoundationTracksFormControllerReadOptions = <TResponse = BarqAcademyFoundationTracksFormControllerReadResponse>(options?: OptionsLegacyParser<BarqAcademyFoundationTracksFormControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await barqAcademyFoundationTracksFormControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: barqAcademyFoundationTracksFormControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useBarqAcademyFoundationTracksFormControllerReadQuery = <TResponse = BarqAcademyFoundationTracksFormControllerReadResponse>(dataOptions?: OptionsLegacyParser<BarqAcademyFoundationTracksFormControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...barqAcademyFoundationTracksFormControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const barqAcademyFoundationTracksFormControllerUpdateMutation = <TResponse = BarqAcademyFoundationTracksFormControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<BarqAcademyFoundationTracksFormControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, BarqAcademyFoundationTracksFormControllerUpdateError, OptionsLegacyParser<BarqAcademyFoundationTracksFormControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, BarqAcademyFoundationTracksFormControllerUpdateError, OptionsLegacyParser<BarqAcademyFoundationTracksFormControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await barqAcademyFoundationTracksFormControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useBarqAcademyFoundationTracksFormControllerUpdate = <TResponse = BarqAcademyFoundationTracksFormControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<BarqAcademyFoundationTracksFormControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, BarqAcademyFoundationTracksFormControllerUpdateError, OptionsLegacyParser<BarqAcademyFoundationTracksFormControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...barqAcademyFoundationTracksFormControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const barqAcademyFoundationTracksFormControllerReadOneQueryKey = (options: OptionsLegacyParser<BarqAcademyFoundationTracksFormControllerReadOneData>) => [
    createQueryKey('barqAcademyFoundationTracksFormControllerReadOne', options)
];
export const barqAcademyFoundationTracksFormControllerReadOneOptions = <TResponse = BarqAcademyFoundationTracksFormControllerReadOneResponse>(options?: OptionsLegacyParser<BarqAcademyFoundationTracksFormControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await barqAcademyFoundationTracksFormControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: barqAcademyFoundationTracksFormControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useBarqAcademyFoundationTracksFormControllerReadOneQuery = <TResponse = BarqAcademyFoundationTracksFormControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<BarqAcademyFoundationTracksFormControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...barqAcademyFoundationTracksFormControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};