// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, barqAcademyFoundationTracksFormDataControllerCreate, barqAcademyFoundationTracksFormDataControllerRead, barqAcademyFoundationTracksFormDataControllerUpdate, barqAcademyFoundationTracksFormDataControllerReadOne } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { BarqAcademyFoundationTracksFormDataControllerCreateData, BarqAcademyFoundationTracksFormDataControllerCreateError, BarqAcademyFoundationTracksFormDataControllerCreateResponse, BarqAcademyFoundationTracksFormDataControllerReadData, BarqAcademyFoundationTracksFormDataControllerReadResponse, BarqAcademyFoundationTracksFormDataControllerUpdateData, BarqAcademyFoundationTracksFormDataControllerUpdateError, BarqAcademyFoundationTracksFormDataControllerUpdateResponse, BarqAcademyFoundationTracksFormDataControllerReadOneData, BarqAcademyFoundationTracksFormDataControllerReadOneResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const barqAcademyFoundationTracksFormDataControllerCreateMutation = <TResponse = BarqAcademyFoundationTracksFormDataControllerCreateResponse>(options?: Partial<OptionsLegacyParser<BarqAcademyFoundationTracksFormDataControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, BarqAcademyFoundationTracksFormDataControllerCreateError, OptionsLegacyParser<BarqAcademyFoundationTracksFormDataControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, BarqAcademyFoundationTracksFormDataControllerCreateError, OptionsLegacyParser<BarqAcademyFoundationTracksFormDataControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await barqAcademyFoundationTracksFormDataControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useBarqAcademyFoundationTracksFormDataControllerCreate = <TResponse = BarqAcademyFoundationTracksFormDataControllerCreateResponse>(dataOptions?: OptionsLegacyParser<BarqAcademyFoundationTracksFormDataControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, BarqAcademyFoundationTracksFormDataControllerCreateError, OptionsLegacyParser<BarqAcademyFoundationTracksFormDataControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...barqAcademyFoundationTracksFormDataControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const barqAcademyFoundationTracksFormDataControllerReadQueryKey = (options: OptionsLegacyParser<BarqAcademyFoundationTracksFormDataControllerReadData>) => [
    createQueryKey('barqAcademyFoundationTracksFormDataControllerRead', options)
];
export const barqAcademyFoundationTracksFormDataControllerReadOptions = <TResponse = BarqAcademyFoundationTracksFormDataControllerReadResponse>(options?: OptionsLegacyParser<BarqAcademyFoundationTracksFormDataControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await barqAcademyFoundationTracksFormDataControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: barqAcademyFoundationTracksFormDataControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useBarqAcademyFoundationTracksFormDataControllerReadQuery = <TResponse = BarqAcademyFoundationTracksFormDataControllerReadResponse>(dataOptions?: OptionsLegacyParser<BarqAcademyFoundationTracksFormDataControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...barqAcademyFoundationTracksFormDataControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const barqAcademyFoundationTracksFormDataControllerUpdateMutation = <TResponse = BarqAcademyFoundationTracksFormDataControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<BarqAcademyFoundationTracksFormDataControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, BarqAcademyFoundationTracksFormDataControllerUpdateError, OptionsLegacyParser<BarqAcademyFoundationTracksFormDataControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, BarqAcademyFoundationTracksFormDataControllerUpdateError, OptionsLegacyParser<BarqAcademyFoundationTracksFormDataControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await barqAcademyFoundationTracksFormDataControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useBarqAcademyFoundationTracksFormDataControllerUpdate = <TResponse = BarqAcademyFoundationTracksFormDataControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<BarqAcademyFoundationTracksFormDataControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, BarqAcademyFoundationTracksFormDataControllerUpdateError, OptionsLegacyParser<BarqAcademyFoundationTracksFormDataControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...barqAcademyFoundationTracksFormDataControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const barqAcademyFoundationTracksFormDataControllerReadOneQueryKey = (options: OptionsLegacyParser<BarqAcademyFoundationTracksFormDataControllerReadOneData>) => [
    createQueryKey('barqAcademyFoundationTracksFormDataControllerReadOne', options)
];
export const barqAcademyFoundationTracksFormDataControllerReadOneOptions = <TResponse = BarqAcademyFoundationTracksFormDataControllerReadOneResponse>(options?: OptionsLegacyParser<BarqAcademyFoundationTracksFormDataControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await barqAcademyFoundationTracksFormDataControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: barqAcademyFoundationTracksFormDataControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useBarqAcademyFoundationTracksFormDataControllerReadOneQuery = <TResponse = BarqAcademyFoundationTracksFormDataControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<BarqAcademyFoundationTracksFormDataControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...barqAcademyFoundationTracksFormDataControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};