// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, barqAcademyHighlightsControllerCreate, barqAcademyHighlightsControllerRead, barqAcademyHighlightsControllerReadOne, barqAcademyHighlightsControllerUpdate } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { BarqAcademyHighlightsControllerCreateData, BarqAcademyHighlightsControllerCreateError, BarqAcademyHighlightsControllerCreateResponse, BarqAcademyHighlightsControllerReadData, BarqAcademyHighlightsControllerReadResponse, BarqAcademyHighlightsControllerReadOneData, BarqAcademyHighlightsControllerReadOneResponse, BarqAcademyHighlightsControllerUpdateData, BarqAcademyHighlightsControllerUpdateError, BarqAcademyHighlightsControllerUpdateResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const barqAcademyHighlightsControllerCreateMutation = <TResponse = BarqAcademyHighlightsControllerCreateResponse>(options?: Partial<OptionsLegacyParser<BarqAcademyHighlightsControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, BarqAcademyHighlightsControllerCreateError, OptionsLegacyParser<BarqAcademyHighlightsControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, BarqAcademyHighlightsControllerCreateError, OptionsLegacyParser<BarqAcademyHighlightsControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await barqAcademyHighlightsControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useBarqAcademyHighlightsControllerCreate = <TResponse = BarqAcademyHighlightsControllerCreateResponse>(dataOptions?: OptionsLegacyParser<BarqAcademyHighlightsControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, BarqAcademyHighlightsControllerCreateError, OptionsLegacyParser<BarqAcademyHighlightsControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...barqAcademyHighlightsControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const barqAcademyHighlightsControllerReadQueryKey = (options: OptionsLegacyParser<BarqAcademyHighlightsControllerReadData>) => [
    createQueryKey('barqAcademyHighlightsControllerRead', options)
];
export const barqAcademyHighlightsControllerReadOptions = <TResponse = BarqAcademyHighlightsControllerReadResponse>(options?: OptionsLegacyParser<BarqAcademyHighlightsControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await barqAcademyHighlightsControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: barqAcademyHighlightsControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useBarqAcademyHighlightsControllerReadQuery = <TResponse = BarqAcademyHighlightsControllerReadResponse>(dataOptions?: OptionsLegacyParser<BarqAcademyHighlightsControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...barqAcademyHighlightsControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const barqAcademyHighlightsControllerReadOneQueryKey = (options: OptionsLegacyParser<BarqAcademyHighlightsControllerReadOneData>) => [
    createQueryKey('barqAcademyHighlightsControllerReadOne', options)
];
export const barqAcademyHighlightsControllerReadOneOptions = <TResponse = BarqAcademyHighlightsControllerReadOneResponse>(options?: OptionsLegacyParser<BarqAcademyHighlightsControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await barqAcademyHighlightsControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: barqAcademyHighlightsControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useBarqAcademyHighlightsControllerReadOneQuery = <TResponse = BarqAcademyHighlightsControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<BarqAcademyHighlightsControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...barqAcademyHighlightsControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};
export const barqAcademyHighlightsControllerUpdateMutation = <TResponse = BarqAcademyHighlightsControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<BarqAcademyHighlightsControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, BarqAcademyHighlightsControllerUpdateError, OptionsLegacyParser<BarqAcademyHighlightsControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, BarqAcademyHighlightsControllerUpdateError, OptionsLegacyParser<BarqAcademyHighlightsControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await barqAcademyHighlightsControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useBarqAcademyHighlightsControllerUpdate = <TResponse = BarqAcademyHighlightsControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<BarqAcademyHighlightsControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, BarqAcademyHighlightsControllerUpdateError, OptionsLegacyParser<BarqAcademyHighlightsControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...barqAcademyHighlightsControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};