// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, barqAcademyHeroControllerCreate, barqAcademyHeroControllerRead, barqAcademyHeroControllerUpdate, barqAcademyHeroControllerReadOne } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { BarqAcademyHeroControllerCreateData, BarqAcademyHeroControllerCreateError, BarqAcademyHeroControllerCreateResponse, BarqAcademyHeroControllerReadData, BarqAcademyHeroControllerReadResponse, BarqAcademyHeroControllerUpdateData, BarqAcademyHeroControllerUpdateError, BarqAcademyHeroControllerUpdateResponse, BarqAcademyHeroControllerReadOneData, BarqAcademyHeroControllerReadOneResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const barqAcademyHeroControllerCreateMutation = <TResponse = BarqAcademyHeroControllerCreateResponse>(options?: Partial<OptionsLegacyParser<BarqAcademyHeroControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, BarqAcademyHeroControllerCreateError, OptionsLegacyParser<BarqAcademyHeroControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, BarqAcademyHeroControllerCreateError, OptionsLegacyParser<BarqAcademyHeroControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await barqAcademyHeroControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useBarqAcademyHeroControllerCreate = <TResponse = BarqAcademyHeroControllerCreateResponse>(dataOptions?: OptionsLegacyParser<BarqAcademyHeroControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, BarqAcademyHeroControllerCreateError, OptionsLegacyParser<BarqAcademyHeroControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...barqAcademyHeroControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const barqAcademyHeroControllerReadQueryKey = (options: OptionsLegacyParser<BarqAcademyHeroControllerReadData>) => [
    createQueryKey('barqAcademyHeroControllerRead', options)
];
export const barqAcademyHeroControllerReadOptions = <TResponse = BarqAcademyHeroControllerReadResponse>(options?: OptionsLegacyParser<BarqAcademyHeroControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await barqAcademyHeroControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: barqAcademyHeroControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useBarqAcademyHeroControllerReadQuery = <TResponse = BarqAcademyHeroControllerReadResponse>(dataOptions?: OptionsLegacyParser<BarqAcademyHeroControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...barqAcademyHeroControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const barqAcademyHeroControllerUpdateMutation = <TResponse = BarqAcademyHeroControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<BarqAcademyHeroControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, BarqAcademyHeroControllerUpdateError, OptionsLegacyParser<BarqAcademyHeroControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, BarqAcademyHeroControllerUpdateError, OptionsLegacyParser<BarqAcademyHeroControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await barqAcademyHeroControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useBarqAcademyHeroControllerUpdate = <TResponse = BarqAcademyHeroControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<BarqAcademyHeroControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, BarqAcademyHeroControllerUpdateError, OptionsLegacyParser<BarqAcademyHeroControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...barqAcademyHeroControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const barqAcademyHeroControllerReadOneQueryKey = (options: OptionsLegacyParser<BarqAcademyHeroControllerReadOneData>) => [
    createQueryKey('barqAcademyHeroControllerReadOne', options)
];
export const barqAcademyHeroControllerReadOneOptions = <TResponse = BarqAcademyHeroControllerReadOneResponse>(options?: OptionsLegacyParser<BarqAcademyHeroControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await barqAcademyHeroControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: barqAcademyHeroControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useBarqAcademyHeroControllerReadOneQuery = <TResponse = BarqAcademyHeroControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<BarqAcademyHeroControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...barqAcademyHeroControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};