// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, careerCategoryControllerCreate, careerCategoryControllerRead, careerCategoryControllerUpdate, careerCategoryControllerReadOne, careerCategoryControllerDelete } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { CareerCategoryControllerCreateData, CareerCategoryControllerCreateError, CareerCategoryControllerCreateResponse, CareerCategoryControllerReadData, CareerCategoryControllerReadResponse, CareerCategoryControllerUpdateData, CareerCategoryControllerUpdateError, CareerCategoryControllerUpdateResponse, CareerCategoryControllerReadOneData, CareerCategoryControllerReadOneResponse, CareerCategoryControllerDeleteData, CareerCategoryControllerDeleteError, CareerCategoryControllerDeleteResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const careerCategoryControllerCreateMutation = <TResponse = CareerCategoryControllerCreateResponse>(options?: Partial<OptionsLegacyParser<CareerCategoryControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, CareerCategoryControllerCreateError, OptionsLegacyParser<CareerCategoryControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, CareerCategoryControllerCreateError, OptionsLegacyParser<CareerCategoryControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await careerCategoryControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useCareerCategoryControllerCreate = <TResponse = CareerCategoryControllerCreateResponse>(dataOptions?: OptionsLegacyParser<CareerCategoryControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, CareerCategoryControllerCreateError, OptionsLegacyParser<CareerCategoryControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...careerCategoryControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const careerCategoryControllerReadQueryKey = (options: OptionsLegacyParser<CareerCategoryControllerReadData>) => [
    createQueryKey('careerCategoryControllerRead', options)
];
export const careerCategoryControllerReadOptions = <TResponse = CareerCategoryControllerReadResponse>(options?: OptionsLegacyParser<CareerCategoryControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await careerCategoryControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: careerCategoryControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useCareerCategoryControllerReadQuery = <TResponse = CareerCategoryControllerReadResponse>(dataOptions?: OptionsLegacyParser<CareerCategoryControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...careerCategoryControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const careerCategoryControllerUpdateMutation = <TResponse = CareerCategoryControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<CareerCategoryControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, CareerCategoryControllerUpdateError, OptionsLegacyParser<CareerCategoryControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, CareerCategoryControllerUpdateError, OptionsLegacyParser<CareerCategoryControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await careerCategoryControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useCareerCategoryControllerUpdate = <TResponse = CareerCategoryControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<CareerCategoryControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, CareerCategoryControllerUpdateError, OptionsLegacyParser<CareerCategoryControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...careerCategoryControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const careerCategoryControllerReadOneQueryKey = (options: OptionsLegacyParser<CareerCategoryControllerReadOneData>) => [
    createQueryKey('careerCategoryControllerReadOne', options)
];
export const careerCategoryControllerReadOneOptions = <TResponse = CareerCategoryControllerReadOneResponse>(options?: OptionsLegacyParser<CareerCategoryControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await careerCategoryControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: careerCategoryControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useCareerCategoryControllerReadOneQuery = <TResponse = CareerCategoryControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<CareerCategoryControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...careerCategoryControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};
export const careerCategoryControllerDeleteMutation = <TResponse = CareerCategoryControllerDeleteResponse>(options?: Partial<OptionsLegacyParser<CareerCategoryControllerDeleteData>>, hookOptions?: Omit<MutationOptions<TResponse, CareerCategoryControllerDeleteError, OptionsLegacyParser<CareerCategoryControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, CareerCategoryControllerDeleteError, OptionsLegacyParser<CareerCategoryControllerDeleteData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await careerCategoryControllerDelete({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useCareerCategoryControllerDelete = <TResponse = CareerCategoryControllerDeleteResponse>(dataOptions?: OptionsLegacyParser<CareerCategoryControllerDeleteData>, hookOptions?: Omit<MutationOptions<TResponse, CareerCategoryControllerDeleteError, OptionsLegacyParser<CareerCategoryControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...careerCategoryControllerDeleteMutation(dataOptions ?? {}, hookOptions)
    });
};