// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, careerOpenPositionHeroControllerCreate, careerOpenPositionHeroControllerRead, careerOpenPositionHeroControllerUpdate, careerOpenPositionHeroControllerReadOne } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { CareerOpenPositionHeroControllerCreateData, CareerOpenPositionHeroControllerCreateError, CareerOpenPositionHeroControllerCreateResponse, CareerOpenPositionHeroControllerReadData, CareerOpenPositionHeroControllerReadResponse, CareerOpenPositionHeroControllerUpdateData, CareerOpenPositionHeroControllerUpdateError, CareerOpenPositionHeroControllerUpdateResponse, CareerOpenPositionHeroControllerReadOneData, CareerOpenPositionHeroControllerReadOneResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const careerOpenPositionHeroControllerCreateMutation = <TResponse = CareerOpenPositionHeroControllerCreateResponse>(options?: Partial<OptionsLegacyParser<CareerOpenPositionHeroControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, CareerOpenPositionHeroControllerCreateError, OptionsLegacyParser<CareerOpenPositionHeroControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, CareerOpenPositionHeroControllerCreateError, OptionsLegacyParser<CareerOpenPositionHeroControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await careerOpenPositionHeroControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useCareerOpenPositionHeroControllerCreate = <TResponse = CareerOpenPositionHeroControllerCreateResponse>(dataOptions?: OptionsLegacyParser<CareerOpenPositionHeroControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, CareerOpenPositionHeroControllerCreateError, OptionsLegacyParser<CareerOpenPositionHeroControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...careerOpenPositionHeroControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const careerOpenPositionHeroControllerReadQueryKey = (options: OptionsLegacyParser<CareerOpenPositionHeroControllerReadData>) => [
    createQueryKey('careerOpenPositionHeroControllerRead', options)
];
export const careerOpenPositionHeroControllerReadOptions = <TResponse = CareerOpenPositionHeroControllerReadResponse>(options?: OptionsLegacyParser<CareerOpenPositionHeroControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await careerOpenPositionHeroControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: careerOpenPositionHeroControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useCareerOpenPositionHeroControllerReadQuery = <TResponse = CareerOpenPositionHeroControllerReadResponse>(dataOptions?: OptionsLegacyParser<CareerOpenPositionHeroControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...careerOpenPositionHeroControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const careerOpenPositionHeroControllerUpdateMutation = <TResponse = CareerOpenPositionHeroControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<CareerOpenPositionHeroControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, CareerOpenPositionHeroControllerUpdateError, OptionsLegacyParser<CareerOpenPositionHeroControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, CareerOpenPositionHeroControllerUpdateError, OptionsLegacyParser<CareerOpenPositionHeroControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await careerOpenPositionHeroControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useCareerOpenPositionHeroControllerUpdate = <TResponse = CareerOpenPositionHeroControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<CareerOpenPositionHeroControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, CareerOpenPositionHeroControllerUpdateError, OptionsLegacyParser<CareerOpenPositionHeroControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...careerOpenPositionHeroControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const careerOpenPositionHeroControllerReadOneQueryKey = (options: OptionsLegacyParser<CareerOpenPositionHeroControllerReadOneData>) => [
    createQueryKey('careerOpenPositionHeroControllerReadOne', options)
];
export const careerOpenPositionHeroControllerReadOneOptions = <TResponse = CareerOpenPositionHeroControllerReadOneResponse>(options?: OptionsLegacyParser<CareerOpenPositionHeroControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await careerOpenPositionHeroControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: careerOpenPositionHeroControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useCareerOpenPositionHeroControllerReadOneQuery = <TResponse = CareerOpenPositionHeroControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<CareerOpenPositionHeroControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...careerOpenPositionHeroControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};