// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, careerOpportunityControllerCreate, careerOpportunityControllerRead, careerOpportunityControllerUpdate, careerOpportunityControllerReadOne, careerOpportunityControllerDelete } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { CareerOpportunityControllerCreateData, CareerOpportunityControllerCreateError, CareerOpportunityControllerCreateResponse, CareerOpportunityControllerReadData, CareerOpportunityControllerReadResponse, CareerOpportunityControllerUpdateData, CareerOpportunityControllerUpdateError, CareerOpportunityControllerUpdateResponse, CareerOpportunityControllerReadOneData, CareerOpportunityControllerReadOneResponse, CareerOpportunityControllerDeleteData, CareerOpportunityControllerDeleteError, CareerOpportunityControllerDeleteResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const careerOpportunityControllerCreateMutation = <TResponse = CareerOpportunityControllerCreateResponse>(options?: Partial<OptionsLegacyParser<CareerOpportunityControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, CareerOpportunityControllerCreateError, OptionsLegacyParser<CareerOpportunityControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, CareerOpportunityControllerCreateError, OptionsLegacyParser<CareerOpportunityControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await careerOpportunityControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useCareerOpportunityControllerCreate = <TResponse = CareerOpportunityControllerCreateResponse>(dataOptions?: OptionsLegacyParser<CareerOpportunityControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, CareerOpportunityControllerCreateError, OptionsLegacyParser<CareerOpportunityControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...careerOpportunityControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const careerOpportunityControllerReadQueryKey = (options: OptionsLegacyParser<CareerOpportunityControllerReadData>) => [
    createQueryKey('careerOpportunityControllerRead', options)
];
export const careerOpportunityControllerReadOptions = <TResponse = CareerOpportunityControllerReadResponse>(options?: OptionsLegacyParser<CareerOpportunityControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await careerOpportunityControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: careerOpportunityControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useCareerOpportunityControllerReadQuery = <TResponse = CareerOpportunityControllerReadResponse>(dataOptions?: OptionsLegacyParser<CareerOpportunityControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...careerOpportunityControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const careerOpportunityControllerUpdateMutation = <TResponse = CareerOpportunityControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<CareerOpportunityControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, CareerOpportunityControllerUpdateError, OptionsLegacyParser<CareerOpportunityControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, CareerOpportunityControllerUpdateError, OptionsLegacyParser<CareerOpportunityControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await careerOpportunityControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useCareerOpportunityControllerUpdate = <TResponse = CareerOpportunityControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<CareerOpportunityControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, CareerOpportunityControllerUpdateError, OptionsLegacyParser<CareerOpportunityControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...careerOpportunityControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const careerOpportunityControllerReadOneQueryKey = (options: OptionsLegacyParser<CareerOpportunityControllerReadOneData>) => [
    createQueryKey('careerOpportunityControllerReadOne', options)
];
export const careerOpportunityControllerReadOneOptions = <TResponse = CareerOpportunityControllerReadOneResponse>(options?: OptionsLegacyParser<CareerOpportunityControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await careerOpportunityControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: careerOpportunityControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useCareerOpportunityControllerReadOneQuery = <TResponse = CareerOpportunityControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<CareerOpportunityControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...careerOpportunityControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};
export const careerOpportunityControllerDeleteMutation = <TResponse = CareerOpportunityControllerDeleteResponse>(options?: Partial<OptionsLegacyParser<CareerOpportunityControllerDeleteData>>, hookOptions?: Omit<MutationOptions<TResponse, CareerOpportunityControllerDeleteError, OptionsLegacyParser<CareerOpportunityControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, CareerOpportunityControllerDeleteError, OptionsLegacyParser<CareerOpportunityControllerDeleteData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await careerOpportunityControllerDelete({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useCareerOpportunityControllerDelete = <TResponse = CareerOpportunityControllerDeleteResponse>(dataOptions?: OptionsLegacyParser<CareerOpportunityControllerDeleteData>, hookOptions?: Omit<MutationOptions<TResponse, CareerOpportunityControllerDeleteError, OptionsLegacyParser<CareerOpportunityControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...careerOpportunityControllerDeleteMutation(dataOptions ?? {}, hookOptions)
    });
};