// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, contactUsOfficesControllerCreate, contactUsOfficesControllerRead, contactUsOfficesControllerUpdate, contactUsOfficesControllerReadOne } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { ContactUsOfficesControllerCreateData, ContactUsOfficesControllerCreateError, ContactUsOfficesControllerCreateResponse, ContactUsOfficesControllerReadData, ContactUsOfficesControllerReadResponse, ContactUsOfficesControllerUpdateData, ContactUsOfficesControllerUpdateError, ContactUsOfficesControllerUpdateResponse, ContactUsOfficesControllerReadOneData, ContactUsOfficesControllerReadOneResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const contactUsOfficesControllerCreateMutation = <TResponse = ContactUsOfficesControllerCreateResponse>(options?: Partial<OptionsLegacyParser<ContactUsOfficesControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, ContactUsOfficesControllerCreateError, OptionsLegacyParser<ContactUsOfficesControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, ContactUsOfficesControllerCreateError, OptionsLegacyParser<ContactUsOfficesControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await contactUsOfficesControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useContactUsOfficesControllerCreate = <TResponse = ContactUsOfficesControllerCreateResponse>(dataOptions?: OptionsLegacyParser<ContactUsOfficesControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, ContactUsOfficesControllerCreateError, OptionsLegacyParser<ContactUsOfficesControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...contactUsOfficesControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const contactUsOfficesControllerReadQueryKey = (options: OptionsLegacyParser<ContactUsOfficesControllerReadData>) => [
    createQueryKey('contactUsOfficesControllerRead', options)
];
export const contactUsOfficesControllerReadOptions = <TResponse = ContactUsOfficesControllerReadResponse>(options?: OptionsLegacyParser<ContactUsOfficesControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await contactUsOfficesControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: contactUsOfficesControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useContactUsOfficesControllerReadQuery = <TResponse = ContactUsOfficesControllerReadResponse>(dataOptions?: OptionsLegacyParser<ContactUsOfficesControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...contactUsOfficesControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const contactUsOfficesControllerUpdateMutation = <TResponse = ContactUsOfficesControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<ContactUsOfficesControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, ContactUsOfficesControllerUpdateError, OptionsLegacyParser<ContactUsOfficesControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, ContactUsOfficesControllerUpdateError, OptionsLegacyParser<ContactUsOfficesControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await contactUsOfficesControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useContactUsOfficesControllerUpdate = <TResponse = ContactUsOfficesControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<ContactUsOfficesControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, ContactUsOfficesControllerUpdateError, OptionsLegacyParser<ContactUsOfficesControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...contactUsOfficesControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const contactUsOfficesControllerReadOneQueryKey = (options: OptionsLegacyParser<ContactUsOfficesControllerReadOneData>) => [
    createQueryKey('contactUsOfficesControllerReadOne', options)
];
export const contactUsOfficesControllerReadOneOptions = <TResponse = ContactUsOfficesControllerReadOneResponse>(options?: OptionsLegacyParser<ContactUsOfficesControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await contactUsOfficesControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: contactUsOfficesControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useContactUsOfficesControllerReadOneQuery = <TResponse = ContactUsOfficesControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<ContactUsOfficesControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...contactUsOfficesControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};