// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, contactUsRequestTypeControllerCreate, contactUsRequestTypeControllerRead, contactUsRequestTypeControllerUpdate, contactUsRequestTypeControllerReadOne, contactUsRequestTypeControllerSoftDelete } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { ContactUsRequestTypeControllerCreateData, ContactUsRequestTypeControllerCreateError, ContactUsRequestTypeControllerCreateResponse, ContactUsRequestTypeControllerReadData, ContactUsRequestTypeControllerReadResponse, ContactUsRequestTypeControllerUpdateData, ContactUsRequestTypeControllerUpdateError, ContactUsRequestTypeControllerUpdateResponse, ContactUsRequestTypeControllerReadOneData, ContactUsRequestTypeControllerReadOneResponse, ContactUsRequestTypeControllerSoftDeleteData, ContactUsRequestTypeControllerSoftDeleteError, ContactUsRequestTypeControllerSoftDeleteResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const contactUsRequestTypeControllerCreateMutation = <TResponse = ContactUsRequestTypeControllerCreateResponse>(options?: Partial<OptionsLegacyParser<ContactUsRequestTypeControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, ContactUsRequestTypeControllerCreateError, OptionsLegacyParser<ContactUsRequestTypeControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, ContactUsRequestTypeControllerCreateError, OptionsLegacyParser<ContactUsRequestTypeControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await contactUsRequestTypeControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useContactUsRequestTypeControllerCreate = <TResponse = ContactUsRequestTypeControllerCreateResponse>(dataOptions?: OptionsLegacyParser<ContactUsRequestTypeControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, ContactUsRequestTypeControllerCreateError, OptionsLegacyParser<ContactUsRequestTypeControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...contactUsRequestTypeControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const contactUsRequestTypeControllerReadQueryKey = (options: OptionsLegacyParser<ContactUsRequestTypeControllerReadData>) => [
    createQueryKey('contactUsRequestTypeControllerRead', options)
];
export const contactUsRequestTypeControllerReadOptions = <TResponse = ContactUsRequestTypeControllerReadResponse>(options?: OptionsLegacyParser<ContactUsRequestTypeControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await contactUsRequestTypeControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: contactUsRequestTypeControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useContactUsRequestTypeControllerReadQuery = <TResponse = ContactUsRequestTypeControllerReadResponse>(dataOptions?: OptionsLegacyParser<ContactUsRequestTypeControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...contactUsRequestTypeControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const contactUsRequestTypeControllerUpdateMutation = <TResponse = ContactUsRequestTypeControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<ContactUsRequestTypeControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, ContactUsRequestTypeControllerUpdateError, OptionsLegacyParser<ContactUsRequestTypeControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, ContactUsRequestTypeControllerUpdateError, OptionsLegacyParser<ContactUsRequestTypeControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await contactUsRequestTypeControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useContactUsRequestTypeControllerUpdate = <TResponse = ContactUsRequestTypeControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<ContactUsRequestTypeControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, ContactUsRequestTypeControllerUpdateError, OptionsLegacyParser<ContactUsRequestTypeControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...contactUsRequestTypeControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const contactUsRequestTypeControllerReadOneQueryKey = (options: OptionsLegacyParser<ContactUsRequestTypeControllerReadOneData>) => [
    createQueryKey('contactUsRequestTypeControllerReadOne', options)
];
export const contactUsRequestTypeControllerReadOneOptions = <TResponse = ContactUsRequestTypeControllerReadOneResponse>(options?: OptionsLegacyParser<ContactUsRequestTypeControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await contactUsRequestTypeControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: contactUsRequestTypeControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useContactUsRequestTypeControllerReadOneQuery = <TResponse = ContactUsRequestTypeControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<ContactUsRequestTypeControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...contactUsRequestTypeControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};
export const contactUsRequestTypeControllerSoftDeleteMutation = <TResponse = ContactUsRequestTypeControllerSoftDeleteResponse>(options?: Partial<OptionsLegacyParser<ContactUsRequestTypeControllerSoftDeleteData>>, hookOptions?: Omit<MutationOptions<TResponse, ContactUsRequestTypeControllerSoftDeleteError, OptionsLegacyParser<ContactUsRequestTypeControllerSoftDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, ContactUsRequestTypeControllerSoftDeleteError, OptionsLegacyParser<ContactUsRequestTypeControllerSoftDeleteData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await contactUsRequestTypeControllerSoftDelete({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useContactUsRequestTypeControllerSoftDelete = <TResponse = ContactUsRequestTypeControllerSoftDeleteResponse>(dataOptions?: OptionsLegacyParser<ContactUsRequestTypeControllerSoftDeleteData>, hookOptions?: Omit<MutationOptions<TResponse, ContactUsRequestTypeControllerSoftDeleteError, OptionsLegacyParser<ContactUsRequestTypeControllerSoftDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...contactUsRequestTypeControllerSoftDeleteMutation(dataOptions ?? {}, hookOptions)
    });
};