// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, eventsSpeakersControllerCreate, eventsSpeakersControllerRead, eventsSpeakersControllerReadOne, eventsSpeakersControllerUpdate } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { EventsSpeakersControllerCreateData, EventsSpeakersControllerCreateError, EventsSpeakersControllerCreateResponse, EventsSpeakersControllerReadData, EventsSpeakersControllerReadResponse, EventsSpeakersControllerReadOneData, EventsSpeakersControllerReadOneResponse, EventsSpeakersControllerUpdateData, EventsSpeakersControllerUpdateError, EventsSpeakersControllerUpdateResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const eventsSpeakersControllerCreateMutation = <TResponse = EventsSpeakersControllerCreateResponse>(options?: Partial<OptionsLegacyParser<EventsSpeakersControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, EventsSpeakersControllerCreateError, OptionsLegacyParser<EventsSpeakersControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, EventsSpeakersControllerCreateError, OptionsLegacyParser<EventsSpeakersControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await eventsSpeakersControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useEventsSpeakersControllerCreate = <TResponse = EventsSpeakersControllerCreateResponse>(dataOptions?: OptionsLegacyParser<EventsSpeakersControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, EventsSpeakersControllerCreateError, OptionsLegacyParser<EventsSpeakersControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...eventsSpeakersControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const eventsSpeakersControllerReadQueryKey = (options: OptionsLegacyParser<EventsSpeakersControllerReadData>) => [
    createQueryKey('eventsSpeakersControllerRead', options)
];
export const eventsSpeakersControllerReadOptions = <TResponse = EventsSpeakersControllerReadResponse>(options?: OptionsLegacyParser<EventsSpeakersControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await eventsSpeakersControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: eventsSpeakersControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useEventsSpeakersControllerReadQuery = <TResponse = EventsSpeakersControllerReadResponse>(dataOptions?: OptionsLegacyParser<EventsSpeakersControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...eventsSpeakersControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const eventsSpeakersControllerReadOneQueryKey = (options: OptionsLegacyParser<EventsSpeakersControllerReadOneData>) => [
    createQueryKey('eventsSpeakersControllerReadOne', options)
];
export const eventsSpeakersControllerReadOneOptions = <TResponse = EventsSpeakersControllerReadOneResponse>(options?: OptionsLegacyParser<EventsSpeakersControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await eventsSpeakersControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: eventsSpeakersControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useEventsSpeakersControllerReadOneQuery = <TResponse = EventsSpeakersControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<EventsSpeakersControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...eventsSpeakersControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};
export const eventsSpeakersControllerUpdateMutation = <TResponse = EventsSpeakersControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<EventsSpeakersControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, EventsSpeakersControllerUpdateError, OptionsLegacyParser<EventsSpeakersControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, EventsSpeakersControllerUpdateError, OptionsLegacyParser<EventsSpeakersControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await eventsSpeakersControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useEventsSpeakersControllerUpdate = <TResponse = EventsSpeakersControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<EventsSpeakersControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, EventsSpeakersControllerUpdateError, OptionsLegacyParser<EventsSpeakersControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...eventsSpeakersControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};