// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, footerTermsControllerCreate, footerTermsControllerRead, footerTermsControllerUpdate, footerTermsControllerReadOne, footerTermsControllerDelete } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { FooterTermsControllerCreateData, FooterTermsControllerCreateError, FooterTermsControllerCreateResponse, FooterTermsControllerReadData, FooterTermsControllerReadResponse, FooterTermsControllerUpdateData, FooterTermsControllerUpdateError, FooterTermsControllerUpdateResponse, FooterTermsControllerReadOneData, FooterTermsControllerReadOneResponse, FooterTermsControllerDeleteData, FooterTermsControllerDeleteError, FooterTermsControllerDeleteResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const footerTermsControllerCreateMutation = <TResponse = FooterTermsControllerCreateResponse>(options?: Partial<OptionsLegacyParser<FooterTermsControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, FooterTermsControllerCreateError, OptionsLegacyParser<FooterTermsControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, FooterTermsControllerCreateError, OptionsLegacyParser<FooterTermsControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await footerTermsControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useFooterTermsControllerCreate = <TResponse = FooterTermsControllerCreateResponse>(dataOptions?: OptionsLegacyParser<FooterTermsControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, FooterTermsControllerCreateError, OptionsLegacyParser<FooterTermsControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...footerTermsControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const footerTermsControllerReadQueryKey = (options: OptionsLegacyParser<FooterTermsControllerReadData>) => [
    createQueryKey('footerTermsControllerRead', options)
];
export const footerTermsControllerReadOptions = <TResponse = FooterTermsControllerReadResponse>(options?: OptionsLegacyParser<FooterTermsControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await footerTermsControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: footerTermsControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useFooterTermsControllerReadQuery = <TResponse = FooterTermsControllerReadResponse>(dataOptions?: OptionsLegacyParser<FooterTermsControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...footerTermsControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const footerTermsControllerUpdateMutation = <TResponse = FooterTermsControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<FooterTermsControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, FooterTermsControllerUpdateError, OptionsLegacyParser<FooterTermsControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, FooterTermsControllerUpdateError, OptionsLegacyParser<FooterTermsControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await footerTermsControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useFooterTermsControllerUpdate = <TResponse = FooterTermsControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<FooterTermsControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, FooterTermsControllerUpdateError, OptionsLegacyParser<FooterTermsControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...footerTermsControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const footerTermsControllerReadOneQueryKey = (options: OptionsLegacyParser<FooterTermsControllerReadOneData>) => [
    createQueryKey('footerTermsControllerReadOne', options)
];
export const footerTermsControllerReadOneOptions = <TResponse = FooterTermsControllerReadOneResponse>(options?: OptionsLegacyParser<FooterTermsControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await footerTermsControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: footerTermsControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useFooterTermsControllerReadOneQuery = <TResponse = FooterTermsControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<FooterTermsControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...footerTermsControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};
export const footerTermsControllerDeleteMutation = <TResponse = FooterTermsControllerDeleteResponse>(options?: Partial<OptionsLegacyParser<FooterTermsControllerDeleteData>>, hookOptions?: Omit<MutationOptions<TResponse, FooterTermsControllerDeleteError, OptionsLegacyParser<FooterTermsControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, FooterTermsControllerDeleteError, OptionsLegacyParser<FooterTermsControllerDeleteData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await footerTermsControllerDelete({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useFooterTermsControllerDelete = <TResponse = FooterTermsControllerDeleteResponse>(dataOptions?: OptionsLegacyParser<FooterTermsControllerDeleteData>, hookOptions?: Omit<MutationOptions<TResponse, FooterTermsControllerDeleteError, OptionsLegacyParser<FooterTermsControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...footerTermsControllerDeleteMutation(dataOptions ?? {}, hookOptions)
    });
};