// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, globalCommitmentControllerCreate, globalCommitmentControllerRead, globalCommitmentControllerUpdate, globalCommitmentControllerReadOne } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { GlobalCommitmentControllerCreateData, GlobalCommitmentControllerCreateError, GlobalCommitmentControllerCreateResponse, GlobalCommitmentControllerReadData, GlobalCommitmentControllerReadResponse, GlobalCommitmentControllerUpdateData, GlobalCommitmentControllerUpdateError, GlobalCommitmentControllerUpdateResponse, GlobalCommitmentControllerReadOneData, GlobalCommitmentControllerReadOneResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const globalCommitmentControllerCreateMutation = <TResponse = GlobalCommitmentControllerCreateResponse>(options?: Partial<OptionsLegacyParser<GlobalCommitmentControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, GlobalCommitmentControllerCreateError, OptionsLegacyParser<GlobalCommitmentControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, GlobalCommitmentControllerCreateError, OptionsLegacyParser<GlobalCommitmentControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await globalCommitmentControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useGlobalCommitmentControllerCreate = <TResponse = GlobalCommitmentControllerCreateResponse>(dataOptions?: OptionsLegacyParser<GlobalCommitmentControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, GlobalCommitmentControllerCreateError, OptionsLegacyParser<GlobalCommitmentControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...globalCommitmentControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const globalCommitmentControllerReadQueryKey = (options: OptionsLegacyParser<GlobalCommitmentControllerReadData>) => [
    createQueryKey('globalCommitmentControllerRead', options)
];
export const globalCommitmentControllerReadOptions = <TResponse = GlobalCommitmentControllerReadResponse>(options?: OptionsLegacyParser<GlobalCommitmentControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await globalCommitmentControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: globalCommitmentControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useGlobalCommitmentControllerReadQuery = <TResponse = GlobalCommitmentControllerReadResponse>(dataOptions?: OptionsLegacyParser<GlobalCommitmentControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...globalCommitmentControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const globalCommitmentControllerUpdateMutation = <TResponse = GlobalCommitmentControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<GlobalCommitmentControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, GlobalCommitmentControllerUpdateError, OptionsLegacyParser<GlobalCommitmentControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, GlobalCommitmentControllerUpdateError, OptionsLegacyParser<GlobalCommitmentControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await globalCommitmentControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useGlobalCommitmentControllerUpdate = <TResponse = GlobalCommitmentControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<GlobalCommitmentControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, GlobalCommitmentControllerUpdateError, OptionsLegacyParser<GlobalCommitmentControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...globalCommitmentControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const globalCommitmentControllerReadOneQueryKey = (options: OptionsLegacyParser<GlobalCommitmentControllerReadOneData>) => [
    createQueryKey('globalCommitmentControllerReadOne', options)
];
export const globalCommitmentControllerReadOneOptions = <TResponse = GlobalCommitmentControllerReadOneResponse>(options?: OptionsLegacyParser<GlobalCommitmentControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await globalCommitmentControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: globalCommitmentControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useGlobalCommitmentControllerReadOneQuery = <TResponse = GlobalCommitmentControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<GlobalCommitmentControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...globalCommitmentControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};