// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, heroControllerCreate, heroControllerRead, heroControllerUpdate, heroControllerReadOne } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { HeroControllerCreateData, HeroControllerCreateError, HeroControllerCreateResponse, HeroControllerReadData, HeroControllerReadResponse, HeroControllerUpdateData, HeroControllerUpdateError, HeroControllerUpdateResponse, HeroControllerReadOneData, HeroControllerReadOneResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const heroControllerCreateMutation = <TResponse = HeroControllerCreateResponse>(options?: Partial<OptionsLegacyParser<HeroControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, HeroControllerCreateError, OptionsLegacyParser<HeroControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, HeroControllerCreateError, OptionsLegacyParser<HeroControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await heroControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useHeroControllerCreate = <TResponse = HeroControllerCreateResponse>(dataOptions?: OptionsLegacyParser<HeroControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, HeroControllerCreateError, OptionsLegacyParser<HeroControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...heroControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const heroControllerReadQueryKey = (options: OptionsLegacyParser<HeroControllerReadData>) => [
    createQueryKey('heroControllerRead', options)
];
export const heroControllerReadOptions = <TResponse = HeroControllerReadResponse>(options?: OptionsLegacyParser<HeroControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await heroControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: heroControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useHeroControllerReadQuery = <TResponse = HeroControllerReadResponse>(dataOptions?: OptionsLegacyParser<HeroControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...heroControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const heroControllerUpdateMutation = <TResponse = HeroControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<HeroControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, HeroControllerUpdateError, OptionsLegacyParser<HeroControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, HeroControllerUpdateError, OptionsLegacyParser<HeroControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await heroControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useHeroControllerUpdate = <TResponse = HeroControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<HeroControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, HeroControllerUpdateError, OptionsLegacyParser<HeroControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...heroControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const heroControllerReadOneQueryKey = (options: OptionsLegacyParser<HeroControllerReadOneData>) => [
    createQueryKey('heroControllerReadOne', options)
];
export const heroControllerReadOneOptions = <TResponse = HeroControllerReadOneResponse>(options?: OptionsLegacyParser<HeroControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await heroControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: heroControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useHeroControllerReadOneQuery = <TResponse = HeroControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<HeroControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...heroControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};