// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, homeAwardsControllerCreate, homeAwardsControllerRead, homeAwardsControllerReadOne, homeAwardsControllerUpdate } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { HomeAwardsControllerCreateData, HomeAwardsControllerCreateError, HomeAwardsControllerCreateResponse, HomeAwardsControllerReadData, HomeAwardsControllerReadResponse, HomeAwardsControllerReadOneData, HomeAwardsControllerReadOneResponse, HomeAwardsControllerUpdateData, HomeAwardsControllerUpdateError, HomeAwardsControllerUpdateResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const homeAwardsControllerCreateMutation = <TResponse = HomeAwardsControllerCreateResponse>(options?: Partial<OptionsLegacyParser<HomeAwardsControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, HomeAwardsControllerCreateError, OptionsLegacyParser<HomeAwardsControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, HomeAwardsControllerCreateError, OptionsLegacyParser<HomeAwardsControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await homeAwardsControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useHomeAwardsControllerCreate = <TResponse = HomeAwardsControllerCreateResponse>(dataOptions?: OptionsLegacyParser<HomeAwardsControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, HomeAwardsControllerCreateError, OptionsLegacyParser<HomeAwardsControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...homeAwardsControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const homeAwardsControllerReadQueryKey = (options: OptionsLegacyParser<HomeAwardsControllerReadData>) => [
    createQueryKey('homeAwardsControllerRead', options)
];
export const homeAwardsControllerReadOptions = <TResponse = HomeAwardsControllerReadResponse>(options?: OptionsLegacyParser<HomeAwardsControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await homeAwardsControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: homeAwardsControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useHomeAwardsControllerReadQuery = <TResponse = HomeAwardsControllerReadResponse>(dataOptions?: OptionsLegacyParser<HomeAwardsControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...homeAwardsControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const homeAwardsControllerReadOneQueryKey = (options: OptionsLegacyParser<HomeAwardsControllerReadOneData>) => [
    createQueryKey('homeAwardsControllerReadOne', options)
];
export const homeAwardsControllerReadOneOptions = <TResponse = HomeAwardsControllerReadOneResponse>(options?: OptionsLegacyParser<HomeAwardsControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await homeAwardsControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: homeAwardsControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useHomeAwardsControllerReadOneQuery = <TResponse = HomeAwardsControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<HomeAwardsControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...homeAwardsControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};
export const homeAwardsControllerUpdateMutation = <TResponse = HomeAwardsControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<HomeAwardsControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, HomeAwardsControllerUpdateError, OptionsLegacyParser<HomeAwardsControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, HomeAwardsControllerUpdateError, OptionsLegacyParser<HomeAwardsControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await homeAwardsControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useHomeAwardsControllerUpdate = <TResponse = HomeAwardsControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<HomeAwardsControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, HomeAwardsControllerUpdateError, OptionsLegacyParser<HomeAwardsControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...homeAwardsControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};