// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, industriesControllerCreate, industriesControllerRead, industriesControllerUpdate, industriesControllerReadOne, industriesControllerDelete } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { IndustriesControllerCreateData, IndustriesControllerCreateError, IndustriesControllerCreateResponse, IndustriesControllerReadData, IndustriesControllerReadResponse, IndustriesControllerUpdateData, IndustriesControllerUpdateError, IndustriesControllerUpdateResponse, IndustriesControllerReadOneData, IndustriesControllerReadOneResponse, IndustriesControllerDeleteData, IndustriesControllerDeleteError, IndustriesControllerDeleteResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const industriesControllerCreateMutation = <TResponse = IndustriesControllerCreateResponse>(options?: Partial<OptionsLegacyParser<IndustriesControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, IndustriesControllerCreateError, OptionsLegacyParser<IndustriesControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, IndustriesControllerCreateError, OptionsLegacyParser<IndustriesControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await industriesControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useIndustriesControllerCreate = <TResponse = IndustriesControllerCreateResponse>(dataOptions?: OptionsLegacyParser<IndustriesControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, IndustriesControllerCreateError, OptionsLegacyParser<IndustriesControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...industriesControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const industriesControllerReadQueryKey = (options: OptionsLegacyParser<IndustriesControllerReadData>) => [
    createQueryKey('industriesControllerRead', options)
];
export const industriesControllerReadOptions = <TResponse = IndustriesControllerReadResponse>(options?: OptionsLegacyParser<IndustriesControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await industriesControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: industriesControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useIndustriesControllerReadQuery = <TResponse = IndustriesControllerReadResponse>(dataOptions?: OptionsLegacyParser<IndustriesControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...industriesControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const industriesControllerUpdateMutation = <TResponse = IndustriesControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<IndustriesControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, IndustriesControllerUpdateError, OptionsLegacyParser<IndustriesControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, IndustriesControllerUpdateError, OptionsLegacyParser<IndustriesControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await industriesControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useIndustriesControllerUpdate = <TResponse = IndustriesControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<IndustriesControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, IndustriesControllerUpdateError, OptionsLegacyParser<IndustriesControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...industriesControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const industriesControllerReadOneQueryKey = (options: OptionsLegacyParser<IndustriesControllerReadOneData>) => [
    createQueryKey('industriesControllerReadOne', options)
];
export const industriesControllerReadOneOptions = <TResponse = IndustriesControllerReadOneResponse>(options?: OptionsLegacyParser<IndustriesControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await industriesControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: industriesControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useIndustriesControllerReadOneQuery = <TResponse = IndustriesControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<IndustriesControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...industriesControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};
export const industriesControllerDeleteMutation = <TResponse = IndustriesControllerDeleteResponse>(options?: Partial<OptionsLegacyParser<IndustriesControllerDeleteData>>, hookOptions?: Omit<MutationOptions<TResponse, IndustriesControllerDeleteError, OptionsLegacyParser<IndustriesControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, IndustriesControllerDeleteError, OptionsLegacyParser<IndustriesControllerDeleteData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await industriesControllerDelete({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useIndustriesControllerDelete = <TResponse = IndustriesControllerDeleteResponse>(dataOptions?: OptionsLegacyParser<IndustriesControllerDeleteData>, hookOptions?: Omit<MutationOptions<TResponse, IndustriesControllerDeleteError, OptionsLegacyParser<IndustriesControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...industriesControllerDeleteMutation(dataOptions ?? {}, hookOptions)
    });
};