// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, itInfrastructureHeroControllerCreate, itInfrastructureHeroControllerRead, itInfrastructureHeroControllerUpdate, itInfrastructureHeroControllerReadOne } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { ItInfrastructureHeroControllerCreateData, ItInfrastructureHeroControllerCreateError, ItInfrastructureHeroControllerCreateResponse, ItInfrastructureHeroControllerReadData, ItInfrastructureHeroControllerReadResponse, ItInfrastructureHeroControllerUpdateData, ItInfrastructureHeroControllerUpdateError, ItInfrastructureHeroControllerUpdateResponse, ItInfrastructureHeroControllerReadOneData, ItInfrastructureHeroControllerReadOneResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const itInfrastructureHeroControllerCreateMutation = <TResponse = ItInfrastructureHeroControllerCreateResponse>(options?: Partial<OptionsLegacyParser<ItInfrastructureHeroControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, ItInfrastructureHeroControllerCreateError, OptionsLegacyParser<ItInfrastructureHeroControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, ItInfrastructureHeroControllerCreateError, OptionsLegacyParser<ItInfrastructureHeroControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await itInfrastructureHeroControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useItInfrastructureHeroControllerCreate = <TResponse = ItInfrastructureHeroControllerCreateResponse>(dataOptions?: OptionsLegacyParser<ItInfrastructureHeroControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, ItInfrastructureHeroControllerCreateError, OptionsLegacyParser<ItInfrastructureHeroControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...itInfrastructureHeroControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const itInfrastructureHeroControllerReadQueryKey = (options: OptionsLegacyParser<ItInfrastructureHeroControllerReadData>) => [
    createQueryKey('itInfrastructureHeroControllerRead', options)
];
export const itInfrastructureHeroControllerReadOptions = <TResponse = ItInfrastructureHeroControllerReadResponse>(options?: OptionsLegacyParser<ItInfrastructureHeroControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await itInfrastructureHeroControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: itInfrastructureHeroControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useItInfrastructureHeroControllerReadQuery = <TResponse = ItInfrastructureHeroControllerReadResponse>(dataOptions?: OptionsLegacyParser<ItInfrastructureHeroControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...itInfrastructureHeroControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const itInfrastructureHeroControllerUpdateMutation = <TResponse = ItInfrastructureHeroControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<ItInfrastructureHeroControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, ItInfrastructureHeroControllerUpdateError, OptionsLegacyParser<ItInfrastructureHeroControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, ItInfrastructureHeroControllerUpdateError, OptionsLegacyParser<ItInfrastructureHeroControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await itInfrastructureHeroControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useItInfrastructureHeroControllerUpdate = <TResponse = ItInfrastructureHeroControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<ItInfrastructureHeroControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, ItInfrastructureHeroControllerUpdateError, OptionsLegacyParser<ItInfrastructureHeroControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...itInfrastructureHeroControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const itInfrastructureHeroControllerReadOneQueryKey = (options: OptionsLegacyParser<ItInfrastructureHeroControllerReadOneData>) => [
    createQueryKey('itInfrastructureHeroControllerReadOne', options)
];
export const itInfrastructureHeroControllerReadOneOptions = <TResponse = ItInfrastructureHeroControllerReadOneResponse>(options?: OptionsLegacyParser<ItInfrastructureHeroControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await itInfrastructureHeroControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: itInfrastructureHeroControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useItInfrastructureHeroControllerReadOneQuery = <TResponse = ItInfrastructureHeroControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<ItInfrastructureHeroControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...itInfrastructureHeroControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};