// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, leadershipExecutiveTeamControllerCreate, leadershipExecutiveTeamControllerRead, leadershipExecutiveTeamControllerReadOne, leadershipExecutiveTeamControllerUpdate } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { LeadershipExecutiveTeamControllerCreateData, LeadershipExecutiveTeamControllerCreateError, LeadershipExecutiveTeamControllerCreateResponse, LeadershipExecutiveTeamControllerReadData, LeadershipExecutiveTeamControllerReadResponse, LeadershipExecutiveTeamControllerReadOneData, LeadershipExecutiveTeamControllerReadOneResponse, LeadershipExecutiveTeamControllerUpdateData, LeadershipExecutiveTeamControllerUpdateError, LeadershipExecutiveTeamControllerUpdateResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const leadershipExecutiveTeamControllerCreateMutation = <TResponse = LeadershipExecutiveTeamControllerCreateResponse>(options?: Partial<OptionsLegacyParser<LeadershipExecutiveTeamControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, LeadershipExecutiveTeamControllerCreateError, OptionsLegacyParser<LeadershipExecutiveTeamControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, LeadershipExecutiveTeamControllerCreateError, OptionsLegacyParser<LeadershipExecutiveTeamControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await leadershipExecutiveTeamControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useLeadershipExecutiveTeamControllerCreate = <TResponse = LeadershipExecutiveTeamControllerCreateResponse>(dataOptions?: OptionsLegacyParser<LeadershipExecutiveTeamControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, LeadershipExecutiveTeamControllerCreateError, OptionsLegacyParser<LeadershipExecutiveTeamControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...leadershipExecutiveTeamControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const leadershipExecutiveTeamControllerReadQueryKey = (options: OptionsLegacyParser<LeadershipExecutiveTeamControllerReadData>) => [
    createQueryKey('leadershipExecutiveTeamControllerRead', options)
];
export const leadershipExecutiveTeamControllerReadOptions = <TResponse = LeadershipExecutiveTeamControllerReadResponse>(options?: OptionsLegacyParser<LeadershipExecutiveTeamControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await leadershipExecutiveTeamControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: leadershipExecutiveTeamControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useLeadershipExecutiveTeamControllerReadQuery = <TResponse = LeadershipExecutiveTeamControllerReadResponse>(dataOptions?: OptionsLegacyParser<LeadershipExecutiveTeamControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...leadershipExecutiveTeamControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const leadershipExecutiveTeamControllerReadOneQueryKey = (options: OptionsLegacyParser<LeadershipExecutiveTeamControllerReadOneData>) => [
    createQueryKey('leadershipExecutiveTeamControllerReadOne', options)
];
export const leadershipExecutiveTeamControllerReadOneOptions = <TResponse = LeadershipExecutiveTeamControllerReadOneResponse>(options?: OptionsLegacyParser<LeadershipExecutiveTeamControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await leadershipExecutiveTeamControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: leadershipExecutiveTeamControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useLeadershipExecutiveTeamControllerReadOneQuery = <TResponse = LeadershipExecutiveTeamControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<LeadershipExecutiveTeamControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...leadershipExecutiveTeamControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};
export const leadershipExecutiveTeamControllerUpdateMutation = <TResponse = LeadershipExecutiveTeamControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<LeadershipExecutiveTeamControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, LeadershipExecutiveTeamControllerUpdateError, OptionsLegacyParser<LeadershipExecutiveTeamControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, LeadershipExecutiveTeamControllerUpdateError, OptionsLegacyParser<LeadershipExecutiveTeamControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await leadershipExecutiveTeamControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useLeadershipExecutiveTeamControllerUpdate = <TResponse = LeadershipExecutiveTeamControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<LeadershipExecutiveTeamControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, LeadershipExecutiveTeamControllerUpdateError, OptionsLegacyParser<LeadershipExecutiveTeamControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...leadershipExecutiveTeamControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};