// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, leadershipTeamControllerCreate, leadershipTeamControllerFindAll, leadershipTeamControllerFindOne, leadershipTeamControllerUpdate } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { LeadershipTeamControllerCreateData, LeadershipTeamControllerCreateError, LeadershipTeamControllerCreateResponse, LeadershipTeamControllerFindAllData, LeadershipTeamControllerFindAllResponse, LeadershipTeamControllerFindOneData, LeadershipTeamControllerFindOneResponse, LeadershipTeamControllerUpdateData, LeadershipTeamControllerUpdateError, LeadershipTeamControllerUpdateResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const leadershipTeamControllerCreateMutation = <TResponse = LeadershipTeamControllerCreateResponse>(options?: Partial<OptionsLegacyParser<LeadershipTeamControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, LeadershipTeamControllerCreateError, OptionsLegacyParser<LeadershipTeamControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, LeadershipTeamControllerCreateError, OptionsLegacyParser<LeadershipTeamControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await leadershipTeamControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useLeadershipTeamControllerCreate = <TResponse = LeadershipTeamControllerCreateResponse>(dataOptions?: OptionsLegacyParser<LeadershipTeamControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, LeadershipTeamControllerCreateError, OptionsLegacyParser<LeadershipTeamControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...leadershipTeamControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const leadershipTeamControllerFindAllQueryKey = (options: OptionsLegacyParser<LeadershipTeamControllerFindAllData>) => [
    createQueryKey('leadershipTeamControllerFindAll', options)
];
export const leadershipTeamControllerFindAllOptions = <TResponse = LeadershipTeamControllerFindAllResponse>(options?: OptionsLegacyParser<LeadershipTeamControllerFindAllData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await leadershipTeamControllerFindAll({
                ...options ?? {}
            });
            return data;
        },
        queryKey: leadershipTeamControllerFindAllQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useLeadershipTeamControllerFindAllQuery = <TResponse = LeadershipTeamControllerFindAllResponse>(dataOptions?: OptionsLegacyParser<LeadershipTeamControllerFindAllData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...leadershipTeamControllerFindAllOptions(dataOptions ?? {}, hookOptions)
    });
};
export const leadershipTeamControllerFindOneQueryKey = (options: OptionsLegacyParser<LeadershipTeamControllerFindOneData>) => [
    createQueryKey('leadershipTeamControllerFindOne', options)
];
export const leadershipTeamControllerFindOneOptions = <TResponse = LeadershipTeamControllerFindOneResponse>(options?: OptionsLegacyParser<LeadershipTeamControllerFindOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await leadershipTeamControllerFindOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: leadershipTeamControllerFindOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useLeadershipTeamControllerFindOneQuery = <TResponse = LeadershipTeamControllerFindOneResponse>(dataOptions?: OptionsLegacyParser<LeadershipTeamControllerFindOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...leadershipTeamControllerFindOneOptions(dataOptions ?? {}, hookOptions)
    });
};
export const leadershipTeamControllerUpdateMutation = <TResponse = LeadershipTeamControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<LeadershipTeamControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, LeadershipTeamControllerUpdateError, OptionsLegacyParser<LeadershipTeamControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, LeadershipTeamControllerUpdateError, OptionsLegacyParser<LeadershipTeamControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await leadershipTeamControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useLeadershipTeamControllerUpdate = <TResponse = LeadershipTeamControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<LeadershipTeamControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, LeadershipTeamControllerUpdateError, OptionsLegacyParser<LeadershipTeamControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...leadershipTeamControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};