// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, mainSocialControllerCreate, mainSocialControllerRead, mainSocialControllerUpdate, mainSocialControllerReadOne } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { MainSocialControllerCreateData, MainSocialControllerCreateError, MainSocialControllerCreateResponse, MainSocialControllerReadData, MainSocialControllerReadResponse, MainSocialControllerUpdateData, MainSocialControllerUpdateError, MainSocialControllerUpdateResponse, MainSocialControllerReadOneData, MainSocialControllerReadOneResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const mainSocialControllerCreateMutation = <TResponse = MainSocialControllerCreateResponse>(options?: Partial<OptionsLegacyParser<MainSocialControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, MainSocialControllerCreateError, OptionsLegacyParser<MainSocialControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, MainSocialControllerCreateError, OptionsLegacyParser<MainSocialControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await mainSocialControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useMainSocialControllerCreate = <TResponse = MainSocialControllerCreateResponse>(dataOptions?: OptionsLegacyParser<MainSocialControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, MainSocialControllerCreateError, OptionsLegacyParser<MainSocialControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...mainSocialControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const mainSocialControllerReadQueryKey = (options: OptionsLegacyParser<MainSocialControllerReadData>) => [
    createQueryKey('mainSocialControllerRead', options)
];
export const mainSocialControllerReadOptions = <TResponse = MainSocialControllerReadResponse>(options?: OptionsLegacyParser<MainSocialControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await mainSocialControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: mainSocialControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useMainSocialControllerReadQuery = <TResponse = MainSocialControllerReadResponse>(dataOptions?: OptionsLegacyParser<MainSocialControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...mainSocialControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const mainSocialControllerUpdateMutation = <TResponse = MainSocialControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<MainSocialControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, MainSocialControllerUpdateError, OptionsLegacyParser<MainSocialControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, MainSocialControllerUpdateError, OptionsLegacyParser<MainSocialControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await mainSocialControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useMainSocialControllerUpdate = <TResponse = MainSocialControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<MainSocialControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, MainSocialControllerUpdateError, OptionsLegacyParser<MainSocialControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...mainSocialControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const mainSocialControllerReadOneQueryKey = (options: OptionsLegacyParser<MainSocialControllerReadOneData>) => [
    createQueryKey('mainSocialControllerReadOne', options)
];
export const mainSocialControllerReadOneOptions = <TResponse = MainSocialControllerReadOneResponse>(options?: OptionsLegacyParser<MainSocialControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await mainSocialControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: mainSocialControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useMainSocialControllerReadOneQuery = <TResponse = MainSocialControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<MainSocialControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...mainSocialControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};