// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, managedServiceCardsControllerCreate, managedServiceCardsControllerFindAll, managedServiceCardsControllerFindOne, managedServiceCardsControllerUpdate, managedServiceCardsControllerRemove } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { ManagedServiceCardsControllerCreateData, ManagedServiceCardsControllerCreateError, ManagedServiceCardsControllerCreateResponse, ManagedServiceCardsControllerFindAllData, ManagedServiceCardsControllerFindAllResponse, ManagedServiceCardsControllerFindOneData, ManagedServiceCardsControllerFindOneResponse, ManagedServiceCardsControllerUpdateData, ManagedServiceCardsControllerUpdateError, ManagedServiceCardsControllerUpdateResponse, ManagedServiceCardsControllerRemoveData, ManagedServiceCardsControllerRemoveError, ManagedServiceCardsControllerRemoveResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const managedServiceCardsControllerCreateMutation = <TResponse = ManagedServiceCardsControllerCreateResponse>(options?: Partial<OptionsLegacyParser<ManagedServiceCardsControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, ManagedServiceCardsControllerCreateError, OptionsLegacyParser<ManagedServiceCardsControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, ManagedServiceCardsControllerCreateError, OptionsLegacyParser<ManagedServiceCardsControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await managedServiceCardsControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useManagedServiceCardsControllerCreate = <TResponse = ManagedServiceCardsControllerCreateResponse>(dataOptions?: OptionsLegacyParser<ManagedServiceCardsControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, ManagedServiceCardsControllerCreateError, OptionsLegacyParser<ManagedServiceCardsControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...managedServiceCardsControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const managedServiceCardsControllerFindAllQueryKey = (options: OptionsLegacyParser<ManagedServiceCardsControllerFindAllData>) => [
    createQueryKey('managedServiceCardsControllerFindAll', options)
];
export const managedServiceCardsControllerFindAllOptions = <TResponse = ManagedServiceCardsControllerFindAllResponse>(options?: OptionsLegacyParser<ManagedServiceCardsControllerFindAllData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await managedServiceCardsControllerFindAll({
                ...options ?? {}
            });
            return data;
        },
        queryKey: managedServiceCardsControllerFindAllQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useManagedServiceCardsControllerFindAllQuery = <TResponse = ManagedServiceCardsControllerFindAllResponse>(dataOptions?: OptionsLegacyParser<ManagedServiceCardsControllerFindAllData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...managedServiceCardsControllerFindAllOptions(dataOptions ?? {}, hookOptions)
    });
};
export const managedServiceCardsControllerFindOneQueryKey = (options: OptionsLegacyParser<ManagedServiceCardsControllerFindOneData>) => [
    createQueryKey('managedServiceCardsControllerFindOne', options)
];
export const managedServiceCardsControllerFindOneOptions = <TResponse = ManagedServiceCardsControllerFindOneResponse>(options?: OptionsLegacyParser<ManagedServiceCardsControllerFindOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await managedServiceCardsControllerFindOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: managedServiceCardsControllerFindOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useManagedServiceCardsControllerFindOneQuery = <TResponse = ManagedServiceCardsControllerFindOneResponse>(dataOptions?: OptionsLegacyParser<ManagedServiceCardsControllerFindOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...managedServiceCardsControllerFindOneOptions(dataOptions ?? {}, hookOptions)
    });
};
export const managedServiceCardsControllerUpdateMutation = <TResponse = ManagedServiceCardsControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<ManagedServiceCardsControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, ManagedServiceCardsControllerUpdateError, OptionsLegacyParser<ManagedServiceCardsControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, ManagedServiceCardsControllerUpdateError, OptionsLegacyParser<ManagedServiceCardsControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await managedServiceCardsControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useManagedServiceCardsControllerUpdate = <TResponse = ManagedServiceCardsControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<ManagedServiceCardsControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, ManagedServiceCardsControllerUpdateError, OptionsLegacyParser<ManagedServiceCardsControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...managedServiceCardsControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const managedServiceCardsControllerRemoveMutation = <TResponse = ManagedServiceCardsControllerRemoveResponse>(options?: Partial<OptionsLegacyParser<ManagedServiceCardsControllerRemoveData>>, hookOptions?: Omit<MutationOptions<TResponse, ManagedServiceCardsControllerRemoveError, OptionsLegacyParser<ManagedServiceCardsControllerRemoveData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, ManagedServiceCardsControllerRemoveError, OptionsLegacyParser<ManagedServiceCardsControllerRemoveData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await managedServiceCardsControllerRemove({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useManagedServiceCardsControllerRemove = <TResponse = ManagedServiceCardsControllerRemoveResponse>(dataOptions?: OptionsLegacyParser<ManagedServiceCardsControllerRemoveData>, hookOptions?: Omit<MutationOptions<TResponse, ManagedServiceCardsControllerRemoveError, OptionsLegacyParser<ManagedServiceCardsControllerRemoveData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...managedServiceCardsControllerRemoveMutation(dataOptions ?? {}, hookOptions)
    });
};