// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, managedGrcServicesDetailsControllerCreate, managedGrcServicesDetailsControllerFindAll, managedGrcServicesDetailsControllerFindOne, managedGrcServicesDetailsControllerUpdate, managedGrcServicesDetailsControllerRemove } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { ManagedGrcServicesDetailsControllerCreateData, ManagedGrcServicesDetailsControllerCreateError, ManagedGrcServicesDetailsControllerCreateResponse, ManagedGrcServicesDetailsControllerFindAllData, ManagedGrcServicesDetailsControllerFindAllResponse, ManagedGrcServicesDetailsControllerFindOneData, ManagedGrcServicesDetailsControllerFindOneResponse, ManagedGrcServicesDetailsControllerUpdateData, ManagedGrcServicesDetailsControllerUpdateError, ManagedGrcServicesDetailsControllerUpdateResponse, ManagedGrcServicesDetailsControllerRemoveData, ManagedGrcServicesDetailsControllerRemoveError, ManagedGrcServicesDetailsControllerRemoveResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const managedGrcServicesDetailsControllerCreateMutation = <TResponse = ManagedGrcServicesDetailsControllerCreateResponse>(options?: Partial<OptionsLegacyParser<ManagedGrcServicesDetailsControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, ManagedGrcServicesDetailsControllerCreateError, OptionsLegacyParser<ManagedGrcServicesDetailsControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, ManagedGrcServicesDetailsControllerCreateError, OptionsLegacyParser<ManagedGrcServicesDetailsControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await managedGrcServicesDetailsControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useManagedGrcServicesDetailsControllerCreate = <TResponse = ManagedGrcServicesDetailsControllerCreateResponse>(dataOptions?: OptionsLegacyParser<ManagedGrcServicesDetailsControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, ManagedGrcServicesDetailsControllerCreateError, OptionsLegacyParser<ManagedGrcServicesDetailsControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...managedGrcServicesDetailsControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const managedGrcServicesDetailsControllerFindAllQueryKey = (options: OptionsLegacyParser<ManagedGrcServicesDetailsControllerFindAllData>) => [
    createQueryKey('managedGrcServicesDetailsControllerFindAll', options)
];
export const managedGrcServicesDetailsControllerFindAllOptions = <TResponse = ManagedGrcServicesDetailsControllerFindAllResponse>(options?: OptionsLegacyParser<ManagedGrcServicesDetailsControllerFindAllData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await managedGrcServicesDetailsControllerFindAll({
                ...options ?? {}
            });
            return data;
        },
        queryKey: managedGrcServicesDetailsControllerFindAllQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useManagedGrcServicesDetailsControllerFindAllQuery = <TResponse = ManagedGrcServicesDetailsControllerFindAllResponse>(dataOptions?: OptionsLegacyParser<ManagedGrcServicesDetailsControllerFindAllData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...managedGrcServicesDetailsControllerFindAllOptions(dataOptions ?? {}, hookOptions)
    });
};
export const managedGrcServicesDetailsControllerFindOneQueryKey = (options: OptionsLegacyParser<ManagedGrcServicesDetailsControllerFindOneData>) => [
    createQueryKey('managedGrcServicesDetailsControllerFindOne', options)
];
export const managedGrcServicesDetailsControllerFindOneOptions = <TResponse = ManagedGrcServicesDetailsControllerFindOneResponse>(options?: OptionsLegacyParser<ManagedGrcServicesDetailsControllerFindOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await managedGrcServicesDetailsControllerFindOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: managedGrcServicesDetailsControllerFindOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useManagedGrcServicesDetailsControllerFindOneQuery = <TResponse = ManagedGrcServicesDetailsControllerFindOneResponse>(dataOptions?: OptionsLegacyParser<ManagedGrcServicesDetailsControllerFindOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...managedGrcServicesDetailsControllerFindOneOptions(dataOptions ?? {}, hookOptions)
    });
};
export const managedGrcServicesDetailsControllerUpdateMutation = <TResponse = ManagedGrcServicesDetailsControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<ManagedGrcServicesDetailsControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, ManagedGrcServicesDetailsControllerUpdateError, OptionsLegacyParser<ManagedGrcServicesDetailsControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, ManagedGrcServicesDetailsControllerUpdateError, OptionsLegacyParser<ManagedGrcServicesDetailsControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await managedGrcServicesDetailsControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useManagedGrcServicesDetailsControllerUpdate = <TResponse = ManagedGrcServicesDetailsControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<ManagedGrcServicesDetailsControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, ManagedGrcServicesDetailsControllerUpdateError, OptionsLegacyParser<ManagedGrcServicesDetailsControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...managedGrcServicesDetailsControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const managedGrcServicesDetailsControllerRemoveMutation = <TResponse = ManagedGrcServicesDetailsControllerRemoveResponse>(options?: Partial<OptionsLegacyParser<ManagedGrcServicesDetailsControllerRemoveData>>, hookOptions?: Omit<MutationOptions<TResponse, ManagedGrcServicesDetailsControllerRemoveError, OptionsLegacyParser<ManagedGrcServicesDetailsControllerRemoveData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, ManagedGrcServicesDetailsControllerRemoveError, OptionsLegacyParser<ManagedGrcServicesDetailsControllerRemoveData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await managedGrcServicesDetailsControllerRemove({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useManagedGrcServicesDetailsControllerRemove = <TResponse = ManagedGrcServicesDetailsControllerRemoveResponse>(dataOptions?: OptionsLegacyParser<ManagedGrcServicesDetailsControllerRemoveData>, hookOptions?: Omit<MutationOptions<TResponse, ManagedGrcServicesDetailsControllerRemoveError, OptionsLegacyParser<ManagedGrcServicesDetailsControllerRemoveData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...managedGrcServicesDetailsControllerRemoveMutation(dataOptions ?? {}, hookOptions)
    });
};