// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, mobilityControllerCreate, mobilityControllerRead, mobilityControllerReadOne, mobilityControllerUpdate } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { MobilityControllerCreateData, MobilityControllerCreateError, MobilityControllerCreateResponse, MobilityControllerReadData, MobilityControllerReadResponse, MobilityControllerReadOneData, MobilityControllerReadOneResponse, MobilityControllerUpdateData, MobilityControllerUpdateError, MobilityControllerUpdateResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const mobilityControllerCreateMutation = <TResponse = MobilityControllerCreateResponse>(options?: Partial<OptionsLegacyParser<MobilityControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, MobilityControllerCreateError, OptionsLegacyParser<MobilityControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, MobilityControllerCreateError, OptionsLegacyParser<MobilityControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await mobilityControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useMobilityControllerCreate = <TResponse = MobilityControllerCreateResponse>(dataOptions?: OptionsLegacyParser<MobilityControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, MobilityControllerCreateError, OptionsLegacyParser<MobilityControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...mobilityControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const mobilityControllerReadQueryKey = (options: OptionsLegacyParser<MobilityControllerReadData>) => [
    createQueryKey('mobilityControllerRead', options)
];
export const mobilityControllerReadOptions = <TResponse = MobilityControllerReadResponse>(options?: OptionsLegacyParser<MobilityControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await mobilityControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: mobilityControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useMobilityControllerReadQuery = <TResponse = MobilityControllerReadResponse>(dataOptions?: OptionsLegacyParser<MobilityControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...mobilityControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const mobilityControllerReadOneQueryKey = (options: OptionsLegacyParser<MobilityControllerReadOneData>) => [
    createQueryKey('mobilityControllerReadOne', options)
];
export const mobilityControllerReadOneOptions = <TResponse = MobilityControllerReadOneResponse>(options?: OptionsLegacyParser<MobilityControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await mobilityControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: mobilityControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useMobilityControllerReadOneQuery = <TResponse = MobilityControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<MobilityControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...mobilityControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};
export const mobilityControllerUpdateMutation = <TResponse = MobilityControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<MobilityControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, MobilityControllerUpdateError, OptionsLegacyParser<MobilityControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, MobilityControllerUpdateError, OptionsLegacyParser<MobilityControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await mobilityControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useMobilityControllerUpdate = <TResponse = MobilityControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<MobilityControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, MobilityControllerUpdateError, OptionsLegacyParser<MobilityControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...mobilityControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};