// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, newsroomCategoryControllerCreate, newsroomCategoryControllerRead, newsroomCategoryControllerUpdate, newsroomCategoryControllerReadOne, newsroomCategoryControllerDelete } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { NewsroomCategoryControllerCreateData, NewsroomCategoryControllerCreateError, NewsroomCategoryControllerCreateResponse, NewsroomCategoryControllerReadData, NewsroomCategoryControllerReadResponse, NewsroomCategoryControllerUpdateData, NewsroomCategoryControllerUpdateError, NewsroomCategoryControllerUpdateResponse, NewsroomCategoryControllerReadOneData, NewsroomCategoryControllerReadOneResponse, NewsroomCategoryControllerDeleteData, NewsroomCategoryControllerDeleteError, NewsroomCategoryControllerDeleteResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const newsroomCategoryControllerCreateMutation = <TResponse = NewsroomCategoryControllerCreateResponse>(options?: Partial<OptionsLegacyParser<NewsroomCategoryControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, NewsroomCategoryControllerCreateError, OptionsLegacyParser<NewsroomCategoryControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, NewsroomCategoryControllerCreateError, OptionsLegacyParser<NewsroomCategoryControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await newsroomCategoryControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useNewsroomCategoryControllerCreate = <TResponse = NewsroomCategoryControllerCreateResponse>(dataOptions?: OptionsLegacyParser<NewsroomCategoryControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, NewsroomCategoryControllerCreateError, OptionsLegacyParser<NewsroomCategoryControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...newsroomCategoryControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const newsroomCategoryControllerReadQueryKey = (options: OptionsLegacyParser<NewsroomCategoryControllerReadData>) => [
    createQueryKey('newsroomCategoryControllerRead', options)
];
export const newsroomCategoryControllerReadOptions = <TResponse = NewsroomCategoryControllerReadResponse>(options?: OptionsLegacyParser<NewsroomCategoryControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await newsroomCategoryControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: newsroomCategoryControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useNewsroomCategoryControllerReadQuery = <TResponse = NewsroomCategoryControllerReadResponse>(dataOptions?: OptionsLegacyParser<NewsroomCategoryControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...newsroomCategoryControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const newsroomCategoryControllerUpdateMutation = <TResponse = NewsroomCategoryControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<NewsroomCategoryControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, NewsroomCategoryControllerUpdateError, OptionsLegacyParser<NewsroomCategoryControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, NewsroomCategoryControllerUpdateError, OptionsLegacyParser<NewsroomCategoryControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await newsroomCategoryControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useNewsroomCategoryControllerUpdate = <TResponse = NewsroomCategoryControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<NewsroomCategoryControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, NewsroomCategoryControllerUpdateError, OptionsLegacyParser<NewsroomCategoryControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...newsroomCategoryControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const newsroomCategoryControllerReadOneQueryKey = (options: OptionsLegacyParser<NewsroomCategoryControllerReadOneData>) => [
    createQueryKey('newsroomCategoryControllerReadOne', options)
];
export const newsroomCategoryControllerReadOneOptions = <TResponse = NewsroomCategoryControllerReadOneResponse>(options?: OptionsLegacyParser<NewsroomCategoryControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await newsroomCategoryControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: newsroomCategoryControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useNewsroomCategoryControllerReadOneQuery = <TResponse = NewsroomCategoryControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<NewsroomCategoryControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...newsroomCategoryControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};
export const newsroomCategoryControllerDeleteMutation = <TResponse = NewsroomCategoryControllerDeleteResponse>(options?: Partial<OptionsLegacyParser<NewsroomCategoryControllerDeleteData>>, hookOptions?: Omit<MutationOptions<TResponse, NewsroomCategoryControllerDeleteError, OptionsLegacyParser<NewsroomCategoryControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, NewsroomCategoryControllerDeleteError, OptionsLegacyParser<NewsroomCategoryControllerDeleteData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await newsroomCategoryControllerDelete({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useNewsroomCategoryControllerDelete = <TResponse = NewsroomCategoryControllerDeleteResponse>(dataOptions?: OptionsLegacyParser<NewsroomCategoryControllerDeleteData>, hookOptions?: Omit<MutationOptions<TResponse, NewsroomCategoryControllerDeleteError, OptionsLegacyParser<NewsroomCategoryControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...newsroomCategoryControllerDeleteMutation(dataOptions ?? {}, hookOptions)
    });
};