// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, newsroomHeroControllerCreate, newsroomHeroControllerRead, newsroomHeroControllerUpdate, newsroomHeroControllerReadOne } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { NewsroomHeroControllerCreateData, NewsroomHeroControllerCreateError, NewsroomHeroControllerCreateResponse, NewsroomHeroControllerReadData, NewsroomHeroControllerReadResponse, NewsroomHeroControllerUpdateData, NewsroomHeroControllerUpdateError, NewsroomHeroControllerUpdateResponse, NewsroomHeroControllerReadOneData, NewsroomHeroControllerReadOneResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const newsroomHeroControllerCreateMutation = <TResponse = NewsroomHeroControllerCreateResponse>(options?: Partial<OptionsLegacyParser<NewsroomHeroControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, NewsroomHeroControllerCreateError, OptionsLegacyParser<NewsroomHeroControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, NewsroomHeroControllerCreateError, OptionsLegacyParser<NewsroomHeroControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await newsroomHeroControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useNewsroomHeroControllerCreate = <TResponse = NewsroomHeroControllerCreateResponse>(dataOptions?: OptionsLegacyParser<NewsroomHeroControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, NewsroomHeroControllerCreateError, OptionsLegacyParser<NewsroomHeroControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...newsroomHeroControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const newsroomHeroControllerReadQueryKey = (options: OptionsLegacyParser<NewsroomHeroControllerReadData>) => [
    createQueryKey('newsroomHeroControllerRead', options)
];
export const newsroomHeroControllerReadOptions = <TResponse = NewsroomHeroControllerReadResponse>(options?: OptionsLegacyParser<NewsroomHeroControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await newsroomHeroControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: newsroomHeroControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useNewsroomHeroControllerReadQuery = <TResponse = NewsroomHeroControllerReadResponse>(dataOptions?: OptionsLegacyParser<NewsroomHeroControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...newsroomHeroControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const newsroomHeroControllerUpdateMutation = <TResponse = NewsroomHeroControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<NewsroomHeroControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, NewsroomHeroControllerUpdateError, OptionsLegacyParser<NewsroomHeroControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, NewsroomHeroControllerUpdateError, OptionsLegacyParser<NewsroomHeroControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await newsroomHeroControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useNewsroomHeroControllerUpdate = <TResponse = NewsroomHeroControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<NewsroomHeroControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, NewsroomHeroControllerUpdateError, OptionsLegacyParser<NewsroomHeroControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...newsroomHeroControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const newsroomHeroControllerReadOneQueryKey = (options: OptionsLegacyParser<NewsroomHeroControllerReadOneData>) => [
    createQueryKey('newsroomHeroControllerReadOne', options)
];
export const newsroomHeroControllerReadOneOptions = <TResponse = NewsroomHeroControllerReadOneResponse>(options?: OptionsLegacyParser<NewsroomHeroControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await newsroomHeroControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: newsroomHeroControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useNewsroomHeroControllerReadOneQuery = <TResponse = NewsroomHeroControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<NewsroomHeroControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...newsroomHeroControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};