// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import { client, newsroomCardsControllerCreate, newsroomCardsControllerRead, newsroomCardsControllerUpdate, newsroomCardsControllerReadOne, newsroomCardsControllerDelete } from '../sdk.gen';
import { type UseMutationOptions, useMutation, type MutationOptions, queryOptions, useQuery, type QueryOptions } from '@tanstack/react-query';
import type { NewsroomCardsControllerCreateData, NewsroomCardsControllerCreateError, NewsroomCardsControllerCreateResponse, NewsroomCardsControllerReadData, NewsroomCardsControllerReadResponse, NewsroomCardsControllerUpdateData, NewsroomCardsControllerUpdateError, NewsroomCardsControllerUpdateResponse, NewsroomCardsControllerReadOneData, NewsroomCardsControllerReadOneResponse, NewsroomCardsControllerDeleteData, NewsroomCardsControllerDeleteError, NewsroomCardsControllerDeleteResponse } from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};
export const newsroomCardsControllerCreateMutation = <TResponse = NewsroomCardsControllerCreateResponse>(options?: Partial<OptionsLegacyParser<NewsroomCardsControllerCreateData>>, hookOptions?: Omit<MutationOptions<TResponse, NewsroomCardsControllerCreateError, OptionsLegacyParser<NewsroomCardsControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, NewsroomCardsControllerCreateError, OptionsLegacyParser<NewsroomCardsControllerCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await newsroomCardsControllerCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useNewsroomCardsControllerCreate = <TResponse = NewsroomCardsControllerCreateResponse>(dataOptions?: OptionsLegacyParser<NewsroomCardsControllerCreateData>, hookOptions?: Omit<MutationOptions<TResponse, NewsroomCardsControllerCreateError, OptionsLegacyParser<NewsroomCardsControllerCreateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...newsroomCardsControllerCreateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const newsroomCardsControllerReadQueryKey = (options: OptionsLegacyParser<NewsroomCardsControllerReadData>) => [
    createQueryKey('newsroomCardsControllerRead', options)
];
export const newsroomCardsControllerReadOptions = <TResponse = NewsroomCardsControllerReadResponse>(options?: OptionsLegacyParser<NewsroomCardsControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await newsroomCardsControllerRead({
                ...options ?? {}
            });
            return data;
        },
        queryKey: newsroomCardsControllerReadQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useNewsroomCardsControllerReadQuery = <TResponse = NewsroomCardsControllerReadResponse>(dataOptions?: OptionsLegacyParser<NewsroomCardsControllerReadData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...newsroomCardsControllerReadOptions(dataOptions ?? {}, hookOptions)
    });
};
export const newsroomCardsControllerUpdateMutation = <TResponse = NewsroomCardsControllerUpdateResponse>(options?: Partial<OptionsLegacyParser<NewsroomCardsControllerUpdateData>>, hookOptions?: Omit<MutationOptions<TResponse, NewsroomCardsControllerUpdateError, OptionsLegacyParser<NewsroomCardsControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, NewsroomCardsControllerUpdateError, OptionsLegacyParser<NewsroomCardsControllerUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await newsroomCardsControllerUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useNewsroomCardsControllerUpdate = <TResponse = NewsroomCardsControllerUpdateResponse>(dataOptions?: OptionsLegacyParser<NewsroomCardsControllerUpdateData>, hookOptions?: Omit<MutationOptions<TResponse, NewsroomCardsControllerUpdateError, OptionsLegacyParser<NewsroomCardsControllerUpdateData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...newsroomCardsControllerUpdateMutation(dataOptions ?? {}, hookOptions)
    });
};
export const newsroomCardsControllerReadOneQueryKey = (options: OptionsLegacyParser<NewsroomCardsControllerReadOneData>) => [
    createQueryKey('newsroomCardsControllerReadOne', options)
];
export const newsroomCardsControllerReadOneOptions = <TResponse = NewsroomCardsControllerReadOneResponse>(options?: OptionsLegacyParser<NewsroomCardsControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return queryOptions({
        queryFn: async () => {
            const { data } = await newsroomCardsControllerReadOne({
                ...options ?? {}
            });
            return data;
        },
        queryKey: newsroomCardsControllerReadOneQueryKey(options ?? {}),
        ...hookOptions
    });
};
export const useNewsroomCardsControllerReadOneQuery = <TResponse = NewsroomCardsControllerReadOneResponse>(dataOptions?: OptionsLegacyParser<NewsroomCardsControllerReadOneData>, hookOptions?: Omit<QueryOptions<TResponse | undefined>, 'queryKey' | 'queryFn'>) => {
    return useQuery({
        ...newsroomCardsControllerReadOneOptions(dataOptions ?? {}, hookOptions)
    });
};
export const newsroomCardsControllerDeleteMutation = <TResponse = NewsroomCardsControllerDeleteResponse>(options?: Partial<OptionsLegacyParser<NewsroomCardsControllerDeleteData>>, hookOptions?: Omit<MutationOptions<TResponse, NewsroomCardsControllerDeleteError, OptionsLegacyParser<NewsroomCardsControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    const mutationOptions: UseMutationOptions<TResponse, NewsroomCardsControllerDeleteError, OptionsLegacyParser<NewsroomCardsControllerDeleteData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await newsroomCardsControllerDelete({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        },
        ...hookOptions
    };
    return mutationOptions;
};
export const useNewsroomCardsControllerDelete = <TResponse = NewsroomCardsControllerDeleteResponse>(dataOptions?: OptionsLegacyParser<NewsroomCardsControllerDeleteData>, hookOptions?: Omit<MutationOptions<TResponse, NewsroomCardsControllerDeleteError, OptionsLegacyParser<NewsroomCardsControllerDeleteData>>, 'mutationKey' | 'mutationFn'>) => {
    return useMutation({
        ...newsroomCardsControllerDeleteMutation(dataOptions ?? {}, hookOptions)
    });
};