// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  aboutBarqHeroControllerCreate,
  aboutBarqHeroControllerRead,
  aboutBarqHeroControllerReadOne,
  aboutBarqHeroControllerUpdate,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  AboutBarqHeroControllerCreateData,
  AboutBarqHeroControllerCreateError,
  AboutBarqHeroControllerCreateResponse,
  AboutBarqHeroControllerReadData,
  AboutBarqHeroControllerReadResponse,
  AboutBarqHeroControllerReadOneData,
  AboutBarqHeroControllerReadOneResponse,
  AboutBarqHeroControllerUpdateData,
  AboutBarqHeroControllerUpdateError,
  AboutBarqHeroControllerUpdateResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const aboutBarqHeroControllerCreateMutation = <
  TResponse = AboutBarqHeroControllerCreateResponse,
>(
  options?: Partial<OptionsLegacyParser<AboutBarqHeroControllerCreateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      AboutBarqHeroControllerCreateError,
      OptionsLegacyParser<AboutBarqHeroControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    AboutBarqHeroControllerCreateError,
    OptionsLegacyParser<AboutBarqHeroControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await aboutBarqHeroControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useAboutBarqHeroControllerCreate = <
  TResponse = AboutBarqHeroControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<AboutBarqHeroControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      AboutBarqHeroControllerCreateError,
      OptionsLegacyParser<AboutBarqHeroControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...aboutBarqHeroControllerCreateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const aboutBarqHeroControllerReadQueryKey = (
  options: OptionsLegacyParser<AboutBarqHeroControllerReadData>
) => [createQueryKey('aboutBarqHeroControllerRead', options)];
export const aboutBarqHeroControllerReadOptions = <
  TResponse = AboutBarqHeroControllerReadResponse,
>(
  options?: OptionsLegacyParser<AboutBarqHeroControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await aboutBarqHeroControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: aboutBarqHeroControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useAboutBarqHeroControllerReadQuery = <
  TResponse = AboutBarqHeroControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<AboutBarqHeroControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...aboutBarqHeroControllerReadOptions(dataOptions ?? {}, hookOptions),
  });
};
export const aboutBarqHeroControllerReadOneQueryKey = (
  options: OptionsLegacyParser<AboutBarqHeroControllerReadOneData>
) => [createQueryKey('aboutBarqHeroControllerReadOne', options)];
export const aboutBarqHeroControllerReadOneOptions = <
  TResponse = AboutBarqHeroControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<AboutBarqHeroControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await aboutBarqHeroControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: aboutBarqHeroControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useAboutBarqHeroControllerReadOneQuery = <
  TResponse = AboutBarqHeroControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<AboutBarqHeroControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...aboutBarqHeroControllerReadOneOptions(dataOptions ?? {}, hookOptions),
  });
};
export const aboutBarqHeroControllerUpdateMutation = <
  TResponse = AboutBarqHeroControllerUpdateResponse,
>(
  options?: Partial<OptionsLegacyParser<AboutBarqHeroControllerUpdateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      AboutBarqHeroControllerUpdateError,
      OptionsLegacyParser<AboutBarqHeroControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    AboutBarqHeroControllerUpdateError,
    OptionsLegacyParser<AboutBarqHeroControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await aboutBarqHeroControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useAboutBarqHeroControllerUpdate = <
  TResponse = AboutBarqHeroControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<AboutBarqHeroControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      AboutBarqHeroControllerUpdateError,
      OptionsLegacyParser<AboutBarqHeroControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...aboutBarqHeroControllerUpdateMutation(dataOptions ?? {}, hookOptions),
  });
};
