// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  applicationDataControllerCreate,
  applicationDataControllerRead,
  applicationDataControllerReadOne,
  applicationDataControllerUpdate,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  ApplicationDataControllerCreateData,
  ApplicationDataControllerCreateError,
  ApplicationDataControllerCreateResponse,
  ApplicationDataControllerReadData,
  ApplicationDataControllerReadResponse,
  ApplicationDataControllerReadOneData,
  ApplicationDataControllerReadOneResponse,
  ApplicationDataControllerUpdateData,
  ApplicationDataControllerUpdateError,
  ApplicationDataControllerUpdateResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const applicationDataControllerCreateMutation = <
  TResponse = ApplicationDataControllerCreateResponse,
>(
  options?: Partial<OptionsLegacyParser<ApplicationDataControllerCreateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ApplicationDataControllerCreateError,
      OptionsLegacyParser<ApplicationDataControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    ApplicationDataControllerCreateError,
    OptionsLegacyParser<ApplicationDataControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await applicationDataControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useApplicationDataControllerCreate = <
  TResponse = ApplicationDataControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<ApplicationDataControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ApplicationDataControllerCreateError,
      OptionsLegacyParser<ApplicationDataControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...applicationDataControllerCreateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const applicationDataControllerReadQueryKey = (
  options: OptionsLegacyParser<ApplicationDataControllerReadData>
) => [createQueryKey('applicationDataControllerRead', options)];
export const applicationDataControllerReadOptions = <
  TResponse = ApplicationDataControllerReadResponse,
>(
  options?: OptionsLegacyParser<ApplicationDataControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await applicationDataControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: applicationDataControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useApplicationDataControllerReadQuery = <
  TResponse = ApplicationDataControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<ApplicationDataControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...applicationDataControllerReadOptions(dataOptions ?? {}, hookOptions),
  });
};
export const applicationDataControllerReadOneQueryKey = (
  options: OptionsLegacyParser<ApplicationDataControllerReadOneData>
) => [createQueryKey('applicationDataControllerReadOne', options)];
export const applicationDataControllerReadOneOptions = <
  TResponse = ApplicationDataControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<ApplicationDataControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await applicationDataControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: applicationDataControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useApplicationDataControllerReadOneQuery = <
  TResponse = ApplicationDataControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<ApplicationDataControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...applicationDataControllerReadOneOptions(dataOptions ?? {}, hookOptions),
  });
};
export const applicationDataControllerUpdateMutation = <
  TResponse = ApplicationDataControllerUpdateResponse,
>(
  options?: Partial<OptionsLegacyParser<ApplicationDataControllerUpdateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ApplicationDataControllerUpdateError,
      OptionsLegacyParser<ApplicationDataControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    ApplicationDataControllerUpdateError,
    OptionsLegacyParser<ApplicationDataControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await applicationDataControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useApplicationDataControllerUpdate = <
  TResponse = ApplicationDataControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<ApplicationDataControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ApplicationDataControllerUpdateError,
      OptionsLegacyParser<ApplicationDataControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...applicationDataControllerUpdateMutation(dataOptions ?? {}, hookOptions),
  });
};
