// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  automationHeroControllerCreate,
  automationHeroControllerRead,
  automationHeroControllerUpdate,
  automationHeroControllerReadOne,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  AutomationHeroControllerCreateData,
  AutomationHeroControllerCreateError,
  AutomationHeroControllerCreateResponse,
  AutomationHeroControllerReadData,
  AutomationHeroControllerReadResponse,
  AutomationHeroControllerUpdateData,
  AutomationHeroControllerUpdateError,
  AutomationHeroControllerUpdateResponse,
  AutomationHeroControllerReadOneData,
  AutomationHeroControllerReadOneResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const automationHeroControllerCreateMutation = <
  TResponse = AutomationHeroControllerCreateResponse,
>(
  options?: Partial<OptionsLegacyParser<AutomationHeroControllerCreateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      AutomationHeroControllerCreateError,
      OptionsLegacyParser<AutomationHeroControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    AutomationHeroControllerCreateError,
    OptionsLegacyParser<AutomationHeroControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await automationHeroControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useAutomationHeroControllerCreate = <
  TResponse = AutomationHeroControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<AutomationHeroControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      AutomationHeroControllerCreateError,
      OptionsLegacyParser<AutomationHeroControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...automationHeroControllerCreateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const automationHeroControllerReadQueryKey = (
  options: OptionsLegacyParser<AutomationHeroControllerReadData>
) => [createQueryKey('automationHeroControllerRead', options)];
export const automationHeroControllerReadOptions = <
  TResponse = AutomationHeroControllerReadResponse,
>(
  options?: OptionsLegacyParser<AutomationHeroControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await automationHeroControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: automationHeroControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useAutomationHeroControllerReadQuery = <
  TResponse = AutomationHeroControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<AutomationHeroControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...automationHeroControllerReadOptions(dataOptions ?? {}, hookOptions),
  });
};
export const automationHeroControllerUpdateMutation = <
  TResponse = AutomationHeroControllerUpdateResponse,
>(
  options?: Partial<OptionsLegacyParser<AutomationHeroControllerUpdateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      AutomationHeroControllerUpdateError,
      OptionsLegacyParser<AutomationHeroControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    AutomationHeroControllerUpdateError,
    OptionsLegacyParser<AutomationHeroControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await automationHeroControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useAutomationHeroControllerUpdate = <
  TResponse = AutomationHeroControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<AutomationHeroControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      AutomationHeroControllerUpdateError,
      OptionsLegacyParser<AutomationHeroControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...automationHeroControllerUpdateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const automationHeroControllerReadOneQueryKey = (
  options: OptionsLegacyParser<AutomationHeroControllerReadOneData>
) => [createQueryKey('automationHeroControllerReadOne', options)];
export const automationHeroControllerReadOneOptions = <
  TResponse = AutomationHeroControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<AutomationHeroControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await automationHeroControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: automationHeroControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useAutomationHeroControllerReadOneQuery = <
  TResponse = AutomationHeroControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<AutomationHeroControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...automationHeroControllerReadOneOptions(dataOptions ?? {}, hookOptions),
  });
};
