// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  barqAcademyProgramsOpportunitiesInternshipControllerCreate,
  barqAcademyProgramsOpportunitiesInternshipControllerRead,
  barqAcademyProgramsOpportunitiesInternshipControllerReadOne,
  barqAcademyProgramsOpportunitiesInternshipControllerUpdate,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  BarqAcademyProgramsOpportunitiesInternshipControllerCreateData,
  BarqAcademyProgramsOpportunitiesInternshipControllerCreateError,
  BarqAcademyProgramsOpportunitiesInternshipControllerCreateResponse,
  BarqAcademyProgramsOpportunitiesInternshipControllerReadData,
  BarqAcademyProgramsOpportunitiesInternshipControllerReadResponse,
  BarqAcademyProgramsOpportunitiesInternshipControllerReadOneData,
  BarqAcademyProgramsOpportunitiesInternshipControllerReadOneResponse,
  BarqAcademyProgramsOpportunitiesInternshipControllerUpdateData,
  BarqAcademyProgramsOpportunitiesInternshipControllerUpdateError,
  BarqAcademyProgramsOpportunitiesInternshipControllerUpdateResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const barqAcademyProgramsOpportunitiesInternshipControllerCreateMutation =
  <
    TResponse = BarqAcademyProgramsOpportunitiesInternshipControllerCreateResponse,
  >(
    options?: Partial<
      OptionsLegacyParser<BarqAcademyProgramsOpportunitiesInternshipControllerCreateData>
    >,
    hookOptions?: Omit<
      MutationOptions<
        TResponse,
        BarqAcademyProgramsOpportunitiesInternshipControllerCreateError,
        OptionsLegacyParser<BarqAcademyProgramsOpportunitiesInternshipControllerCreateData>
      >,
      'mutationKey' | 'mutationFn'
    >
  ) => {
    const mutationOptions: UseMutationOptions<
      TResponse,
      BarqAcademyProgramsOpportunitiesInternshipControllerCreateError,
      OptionsLegacyParser<BarqAcademyProgramsOpportunitiesInternshipControllerCreateData>
    > = {
      mutationFn: async localOptions => {
        const { data } =
          await barqAcademyProgramsOpportunitiesInternshipControllerCreate({
            ...options,
            ...localOptions,
            throwOnError: true,
          });
        return data;
      },
      ...hookOptions,
    };
    return mutationOptions;
  };
export const useBarqAcademyProgramsOpportunitiesInternshipControllerCreate = <
  TResponse = BarqAcademyProgramsOpportunitiesInternshipControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<BarqAcademyProgramsOpportunitiesInternshipControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      BarqAcademyProgramsOpportunitiesInternshipControllerCreateError,
      OptionsLegacyParser<BarqAcademyProgramsOpportunitiesInternshipControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...barqAcademyProgramsOpportunitiesInternshipControllerCreateMutation(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const barqAcademyProgramsOpportunitiesInternshipControllerReadQueryKey =
  (
    options: OptionsLegacyParser<BarqAcademyProgramsOpportunitiesInternshipControllerReadData>
  ) => [
    createQueryKey(
      'barqAcademyProgramsOpportunitiesInternshipControllerRead',
      options
    ),
  ];
export const barqAcademyProgramsOpportunitiesInternshipControllerReadOptions = <
  TResponse = BarqAcademyProgramsOpportunitiesInternshipControllerReadResponse,
>(
  options?: OptionsLegacyParser<BarqAcademyProgramsOpportunitiesInternshipControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } =
        await barqAcademyProgramsOpportunitiesInternshipControllerRead({
          ...(options ?? {}),
        });
      return data;
    },
    queryKey: barqAcademyProgramsOpportunitiesInternshipControllerReadQueryKey(
      options ?? {}
    ),
    ...hookOptions,
  });
};
export const useBarqAcademyProgramsOpportunitiesInternshipControllerReadQuery =
  <
    TResponse = BarqAcademyProgramsOpportunitiesInternshipControllerReadResponse,
  >(
    dataOptions?: OptionsLegacyParser<BarqAcademyProgramsOpportunitiesInternshipControllerReadData>,
    hookOptions?: Omit<
      QueryOptions<TResponse | undefined>,
      'queryKey' | 'queryFn'
    >
  ) => {
    return useQuery({
      ...barqAcademyProgramsOpportunitiesInternshipControllerReadOptions(
        dataOptions ?? {},
        hookOptions
      ),
    });
  };
export const barqAcademyProgramsOpportunitiesInternshipControllerReadOneQueryKey =
  (
    options: OptionsLegacyParser<BarqAcademyProgramsOpportunitiesInternshipControllerReadOneData>
  ) => [
    createQueryKey(
      'barqAcademyProgramsOpportunitiesInternshipControllerReadOne',
      options
    ),
  ];
export const barqAcademyProgramsOpportunitiesInternshipControllerReadOneOptions =
  <
    TResponse = BarqAcademyProgramsOpportunitiesInternshipControllerReadOneResponse,
  >(
    options?: OptionsLegacyParser<BarqAcademyProgramsOpportunitiesInternshipControllerReadOneData>,
    hookOptions?: Omit<
      QueryOptions<TResponse | undefined>,
      'queryKey' | 'queryFn'
    >
  ) => {
    return queryOptions({
      queryFn: async () => {
        const { data } =
          await barqAcademyProgramsOpportunitiesInternshipControllerReadOne({
            ...(options ?? {}),
          });
        return data;
      },
      queryKey:
        barqAcademyProgramsOpportunitiesInternshipControllerReadOneQueryKey(
          options ?? {}
        ),
      ...hookOptions,
    });
  };
export const useBarqAcademyProgramsOpportunitiesInternshipControllerReadOneQuery =
  <
    TResponse = BarqAcademyProgramsOpportunitiesInternshipControllerReadOneResponse,
  >(
    dataOptions?: OptionsLegacyParser<BarqAcademyProgramsOpportunitiesInternshipControllerReadOneData>,
    hookOptions?: Omit<
      QueryOptions<TResponse | undefined>,
      'queryKey' | 'queryFn'
    >
  ) => {
    return useQuery({
      ...barqAcademyProgramsOpportunitiesInternshipControllerReadOneOptions(
        dataOptions ?? {},
        hookOptions
      ),
    });
  };
export const barqAcademyProgramsOpportunitiesInternshipControllerUpdateMutation =
  <
    TResponse = BarqAcademyProgramsOpportunitiesInternshipControllerUpdateResponse,
  >(
    options?: Partial<
      OptionsLegacyParser<BarqAcademyProgramsOpportunitiesInternshipControllerUpdateData>
    >,
    hookOptions?: Omit<
      MutationOptions<
        TResponse,
        BarqAcademyProgramsOpportunitiesInternshipControllerUpdateError,
        OptionsLegacyParser<BarqAcademyProgramsOpportunitiesInternshipControllerUpdateData>
      >,
      'mutationKey' | 'mutationFn'
    >
  ) => {
    const mutationOptions: UseMutationOptions<
      TResponse,
      BarqAcademyProgramsOpportunitiesInternshipControllerUpdateError,
      OptionsLegacyParser<BarqAcademyProgramsOpportunitiesInternshipControllerUpdateData>
    > = {
      mutationFn: async localOptions => {
        const { data } =
          await barqAcademyProgramsOpportunitiesInternshipControllerUpdate({
            ...options,
            ...localOptions,
            throwOnError: true,
          });
        return data;
      },
      ...hookOptions,
    };
    return mutationOptions;
  };
export const useBarqAcademyProgramsOpportunitiesInternshipControllerUpdate = <
  TResponse = BarqAcademyProgramsOpportunitiesInternshipControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<BarqAcademyProgramsOpportunitiesInternshipControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      BarqAcademyProgramsOpportunitiesInternshipControllerUpdateError,
      OptionsLegacyParser<BarqAcademyProgramsOpportunitiesInternshipControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...barqAcademyProgramsOpportunitiesInternshipControllerUpdateMutation(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
