// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  barqExternalApiControllerGetEvents,
  barqExternalApiControllerSyncEvents,
  barqExternalApiControllerSyncCampaigns,
  barqExternalApiControllerReadOneEvent,
  barqExternalApiControllerReadEvents,
} from '../sdk.gen';
import {
  queryOptions,
  useQuery,
  type QueryOptions,
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
} from '@tanstack/react-query';
import type {
  BarqExternalApiControllerGetEventsResponse,
  BarqExternalApiControllerSyncEventsError,
  BarqExternalApiControllerSyncEventsResponse,
  BarqExternalApiControllerSyncCampaignsError,
  BarqExternalApiControllerSyncCampaignsResponse,
  BarqExternalApiControllerReadOneEventData,
  BarqExternalApiControllerReadOneEventResponse,
  BarqExternalApiControllerReadEventsData,
  BarqExternalApiControllerReadEventsResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const barqExternalApiControllerGetEventsQueryKey = (
  options?: OptionsLegacyParser
) => [createQueryKey('barqExternalApiControllerGetEvents', options)];
export const barqExternalApiControllerGetEventsOptions = <
  TResponse = BarqExternalApiControllerGetEventsResponse,
>(
  options?: OptionsLegacyParser,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await barqExternalApiControllerGetEvents({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: barqExternalApiControllerGetEventsQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useBarqExternalApiControllerGetEventsQuery = <
  TResponse = BarqExternalApiControllerGetEventsResponse,
>(
  dataOptions?: OptionsLegacyParser,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...barqExternalApiControllerGetEventsOptions(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const barqExternalApiControllerSyncEventsMutation = <
  TResponse = BarqExternalApiControllerSyncEventsResponse,
>(
  options?: Partial<OptionsLegacyParser>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      BarqExternalApiControllerSyncEventsError,
      OptionsLegacyParser
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    BarqExternalApiControllerSyncEventsError,
    OptionsLegacyParser
  > = {
    mutationFn: async localOptions => {
      const { data } = await barqExternalApiControllerSyncEvents({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useBarqExternalApiControllerSyncEvents = <
  TResponse = BarqExternalApiControllerSyncEventsResponse,
>(
  dataOptions?: OptionsLegacyParser,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      BarqExternalApiControllerSyncEventsError,
      OptionsLegacyParser
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...barqExternalApiControllerSyncEventsMutation(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const barqExternalApiControllerSyncCampaignsMutation = <
  TResponse = BarqExternalApiControllerSyncCampaignsResponse,
>(
  options?: Partial<OptionsLegacyParser>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      BarqExternalApiControllerSyncCampaignsError,
      OptionsLegacyParser
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    BarqExternalApiControllerSyncCampaignsError,
    OptionsLegacyParser
  > = {
    mutationFn: async localOptions => {
      const { data } = await barqExternalApiControllerSyncCampaigns({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useBarqExternalApiControllerSyncCampaigns = <
  TResponse = BarqExternalApiControllerSyncCampaignsResponse,
>(
  dataOptions?: OptionsLegacyParser,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      BarqExternalApiControllerSyncCampaignsError,
      OptionsLegacyParser
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...barqExternalApiControllerSyncCampaignsMutation(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const barqExternalApiControllerReadOneEventQueryKey = (
  options: OptionsLegacyParser<BarqExternalApiControllerReadOneEventData>
) => [createQueryKey('barqExternalApiControllerReadOneEvent', options)];
export const barqExternalApiControllerReadOneEventOptions = <
  TResponse = BarqExternalApiControllerReadOneEventResponse,
>(
  options?: OptionsLegacyParser<BarqExternalApiControllerReadOneEventData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await barqExternalApiControllerReadOneEvent({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: barqExternalApiControllerReadOneEventQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useBarqExternalApiControllerReadOneEventQuery = <
  TResponse = BarqExternalApiControllerReadOneEventResponse,
>(
  dataOptions?: OptionsLegacyParser<BarqExternalApiControllerReadOneEventData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...barqExternalApiControllerReadOneEventOptions(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const barqExternalApiControllerReadEventsQueryKey = (
  options?: OptionsLegacyParser<BarqExternalApiControllerReadEventsData>
) => [createQueryKey('barqExternalApiControllerReadEvents', options)];
export const barqExternalApiControllerReadEventsOptions = <
  TResponse = BarqExternalApiControllerReadEventsResponse,
>(
  options?: OptionsLegacyParser<BarqExternalApiControllerReadEventsData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await barqExternalApiControllerReadEvents({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: barqExternalApiControllerReadEventsQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useBarqExternalApiControllerReadEventsQuery = <
  TResponse = BarqExternalApiControllerReadEventsResponse,
>(
  dataOptions?: OptionsLegacyParser<BarqExternalApiControllerReadEventsData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...barqExternalApiControllerReadEventsOptions(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
