// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  campaignLayoutThreeSectionTwoControllerCreate,
  campaignLayoutThreeSectionTwoControllerRead,
  campaignLayoutThreeSectionTwoControllerReadOne,
  campaignLayoutThreeSectionTwoControllerUpdate,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  CampaignLayoutThreeSectionTwoControllerCreateData,
  CampaignLayoutThreeSectionTwoControllerCreateError,
  CampaignLayoutThreeSectionTwoControllerCreateResponse,
  CampaignLayoutThreeSectionTwoControllerReadData,
  CampaignLayoutThreeSectionTwoControllerReadResponse,
  CampaignLayoutThreeSectionTwoControllerReadOneData,
  CampaignLayoutThreeSectionTwoControllerReadOneResponse,
  CampaignLayoutThreeSectionTwoControllerUpdateData,
  CampaignLayoutThreeSectionTwoControllerUpdateError,
  CampaignLayoutThreeSectionTwoControllerUpdateResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const campaignLayoutThreeSectionTwoControllerCreateMutation = <
  TResponse = CampaignLayoutThreeSectionTwoControllerCreateResponse,
>(
  options?: Partial<
    OptionsLegacyParser<CampaignLayoutThreeSectionTwoControllerCreateData>
  >,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CampaignLayoutThreeSectionTwoControllerCreateError,
      OptionsLegacyParser<CampaignLayoutThreeSectionTwoControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    CampaignLayoutThreeSectionTwoControllerCreateError,
    OptionsLegacyParser<CampaignLayoutThreeSectionTwoControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await campaignLayoutThreeSectionTwoControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useCampaignLayoutThreeSectionTwoControllerCreate = <
  TResponse = CampaignLayoutThreeSectionTwoControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<CampaignLayoutThreeSectionTwoControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CampaignLayoutThreeSectionTwoControllerCreateError,
      OptionsLegacyParser<CampaignLayoutThreeSectionTwoControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...campaignLayoutThreeSectionTwoControllerCreateMutation(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const campaignLayoutThreeSectionTwoControllerReadQueryKey = (
  options: OptionsLegacyParser<CampaignLayoutThreeSectionTwoControllerReadData>
) => [createQueryKey('campaignLayoutThreeSectionTwoControllerRead', options)];
export const campaignLayoutThreeSectionTwoControllerReadOptions = <
  TResponse = CampaignLayoutThreeSectionTwoControllerReadResponse,
>(
  options?: OptionsLegacyParser<CampaignLayoutThreeSectionTwoControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await campaignLayoutThreeSectionTwoControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: campaignLayoutThreeSectionTwoControllerReadQueryKey(
      options ?? {}
    ),
    ...hookOptions,
  });
};
export const useCampaignLayoutThreeSectionTwoControllerReadQuery = <
  TResponse = CampaignLayoutThreeSectionTwoControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<CampaignLayoutThreeSectionTwoControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...campaignLayoutThreeSectionTwoControllerReadOptions(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const campaignLayoutThreeSectionTwoControllerReadOneQueryKey = (
  options: OptionsLegacyParser<CampaignLayoutThreeSectionTwoControllerReadOneData>
) => [
  createQueryKey('campaignLayoutThreeSectionTwoControllerReadOne', options),
];
export const campaignLayoutThreeSectionTwoControllerReadOneOptions = <
  TResponse = CampaignLayoutThreeSectionTwoControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<CampaignLayoutThreeSectionTwoControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await campaignLayoutThreeSectionTwoControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: campaignLayoutThreeSectionTwoControllerReadOneQueryKey(
      options ?? {}
    ),
    ...hookOptions,
  });
};
export const useCampaignLayoutThreeSectionTwoControllerReadOneQuery = <
  TResponse = CampaignLayoutThreeSectionTwoControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<CampaignLayoutThreeSectionTwoControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...campaignLayoutThreeSectionTwoControllerReadOneOptions(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const campaignLayoutThreeSectionTwoControllerUpdateMutation = <
  TResponse = CampaignLayoutThreeSectionTwoControllerUpdateResponse,
>(
  options?: Partial<
    OptionsLegacyParser<CampaignLayoutThreeSectionTwoControllerUpdateData>
  >,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CampaignLayoutThreeSectionTwoControllerUpdateError,
      OptionsLegacyParser<CampaignLayoutThreeSectionTwoControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    CampaignLayoutThreeSectionTwoControllerUpdateError,
    OptionsLegacyParser<CampaignLayoutThreeSectionTwoControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await campaignLayoutThreeSectionTwoControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useCampaignLayoutThreeSectionTwoControllerUpdate = <
  TResponse = CampaignLayoutThreeSectionTwoControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<CampaignLayoutThreeSectionTwoControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CampaignLayoutThreeSectionTwoControllerUpdateError,
      OptionsLegacyParser<CampaignLayoutThreeSectionTwoControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...campaignLayoutThreeSectionTwoControllerUpdateMutation(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
