// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  campaignFormControllerCreate,
  campaignFormControllerRead,
  campaignFormControllerUpdate,
  campaignFormControllerReadOne,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  CampaignFormControllerCreateData,
  CampaignFormControllerCreateError,
  CampaignFormControllerCreateResponse,
  CampaignFormControllerReadData,
  CampaignFormControllerReadResponse,
  CampaignFormControllerUpdateData,
  CampaignFormControllerUpdateError,
  CampaignFormControllerUpdateResponse,
  CampaignFormControllerReadOneData,
  CampaignFormControllerReadOneResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const campaignFormControllerCreateMutation = <
  TResponse = CampaignFormControllerCreateResponse,
>(
  options?: Partial<OptionsLegacyParser<CampaignFormControllerCreateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CampaignFormControllerCreateError,
      OptionsLegacyParser<CampaignFormControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    CampaignFormControllerCreateError,
    OptionsLegacyParser<CampaignFormControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await campaignFormControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useCampaignFormControllerCreate = <
  TResponse = CampaignFormControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<CampaignFormControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CampaignFormControllerCreateError,
      OptionsLegacyParser<CampaignFormControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...campaignFormControllerCreateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const campaignFormControllerReadQueryKey = (
  options: OptionsLegacyParser<CampaignFormControllerReadData>
) => [createQueryKey('campaignFormControllerRead', options)];
export const campaignFormControllerReadOptions = <
  TResponse = CampaignFormControllerReadResponse,
>(
  options?: OptionsLegacyParser<CampaignFormControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await campaignFormControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: campaignFormControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useCampaignFormControllerReadQuery = <
  TResponse = CampaignFormControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<CampaignFormControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...campaignFormControllerReadOptions(dataOptions ?? {}, hookOptions),
  });
};
export const campaignFormControllerUpdateMutation = <
  TResponse = CampaignFormControllerUpdateResponse,
>(
  options?: Partial<OptionsLegacyParser<CampaignFormControllerUpdateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CampaignFormControllerUpdateError,
      OptionsLegacyParser<CampaignFormControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    CampaignFormControllerUpdateError,
    OptionsLegacyParser<CampaignFormControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await campaignFormControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useCampaignFormControllerUpdate = <
  TResponse = CampaignFormControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<CampaignFormControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CampaignFormControllerUpdateError,
      OptionsLegacyParser<CampaignFormControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...campaignFormControllerUpdateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const campaignFormControllerReadOneQueryKey = (
  options: OptionsLegacyParser<CampaignFormControllerReadOneData>
) => [createQueryKey('campaignFormControllerReadOne', options)];
export const campaignFormControllerReadOneOptions = <
  TResponse = CampaignFormControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<CampaignFormControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await campaignFormControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: campaignFormControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useCampaignFormControllerReadOneQuery = <
  TResponse = CampaignFormControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<CampaignFormControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...campaignFormControllerReadOneOptions(dataOptions ?? {}, hookOptions),
  });
};
