// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  campaignLayoutTwoControllerCreate,
  campaignLayoutTwoControllerRead,
  campaignLayoutTwoControllerUpdate,
  campaignLayoutTwoControllerReadOne,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  CampaignLayoutTwoControllerCreateData,
  CampaignLayoutTwoControllerCreateError,
  CampaignLayoutTwoControllerCreateResponse,
  CampaignLayoutTwoControllerReadData,
  CampaignLayoutTwoControllerReadResponse,
  CampaignLayoutTwoControllerUpdateData,
  CampaignLayoutTwoControllerUpdateError,
  CampaignLayoutTwoControllerUpdateResponse,
  CampaignLayoutTwoControllerReadOneData,
  CampaignLayoutTwoControllerReadOneResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const campaignLayoutTwoControllerCreateMutation = <
  TResponse = CampaignLayoutTwoControllerCreateResponse,
>(
  options?: Partial<OptionsLegacyParser<CampaignLayoutTwoControllerCreateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CampaignLayoutTwoControllerCreateError,
      OptionsLegacyParser<CampaignLayoutTwoControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    CampaignLayoutTwoControllerCreateError,
    OptionsLegacyParser<CampaignLayoutTwoControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await campaignLayoutTwoControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useCampaignLayoutTwoControllerCreate = <
  TResponse = CampaignLayoutTwoControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<CampaignLayoutTwoControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CampaignLayoutTwoControllerCreateError,
      OptionsLegacyParser<CampaignLayoutTwoControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...campaignLayoutTwoControllerCreateMutation(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const campaignLayoutTwoControllerReadQueryKey = (
  options: OptionsLegacyParser<CampaignLayoutTwoControllerReadData>
) => [createQueryKey('campaignLayoutTwoControllerRead', options)];
export const campaignLayoutTwoControllerReadOptions = <
  TResponse = CampaignLayoutTwoControllerReadResponse,
>(
  options?: OptionsLegacyParser<CampaignLayoutTwoControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await campaignLayoutTwoControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: campaignLayoutTwoControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useCampaignLayoutTwoControllerReadQuery = <
  TResponse = CampaignLayoutTwoControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<CampaignLayoutTwoControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...campaignLayoutTwoControllerReadOptions(dataOptions ?? {}, hookOptions),
  });
};
export const campaignLayoutTwoControllerUpdateMutation = <
  TResponse = CampaignLayoutTwoControllerUpdateResponse,
>(
  options?: Partial<OptionsLegacyParser<CampaignLayoutTwoControllerUpdateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CampaignLayoutTwoControllerUpdateError,
      OptionsLegacyParser<CampaignLayoutTwoControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    CampaignLayoutTwoControllerUpdateError,
    OptionsLegacyParser<CampaignLayoutTwoControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await campaignLayoutTwoControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useCampaignLayoutTwoControllerUpdate = <
  TResponse = CampaignLayoutTwoControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<CampaignLayoutTwoControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CampaignLayoutTwoControllerUpdateError,
      OptionsLegacyParser<CampaignLayoutTwoControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...campaignLayoutTwoControllerUpdateMutation(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const campaignLayoutTwoControllerReadOneQueryKey = (
  options: OptionsLegacyParser<CampaignLayoutTwoControllerReadOneData>
) => [createQueryKey('campaignLayoutTwoControllerReadOne', options)];
export const campaignLayoutTwoControllerReadOneOptions = <
  TResponse = CampaignLayoutTwoControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<CampaignLayoutTwoControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await campaignLayoutTwoControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: campaignLayoutTwoControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useCampaignLayoutTwoControllerReadOneQuery = <
  TResponse = CampaignLayoutTwoControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<CampaignLayoutTwoControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...campaignLayoutTwoControllerReadOneOptions(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
