// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  campaignControllerRead,
  campaignControllerReadOne,
  campaignControllerUpdate,
} from '../sdk.gen';
import {
  queryOptions,
  useQuery,
  type QueryOptions,
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
} from '@tanstack/react-query';
import type {
  CampaignControllerReadData,
  CampaignControllerReadResponse,
  CampaignControllerReadOneData,
  CampaignControllerReadOneResponse,
  CampaignControllerUpdateData,
  CampaignControllerUpdateError,
  CampaignControllerUpdateResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const campaignControllerReadQueryKey = (
  options?: OptionsLegacyParser<CampaignControllerReadData>
) => [createQueryKey('campaignControllerRead', options)];
export const campaignControllerReadOptions = <
  TResponse = CampaignControllerReadResponse,
>(
  options?: OptionsLegacyParser<CampaignControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await campaignControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: campaignControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useCampaignControllerReadQuery = <
  TResponse = CampaignControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<CampaignControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...campaignControllerReadOptions(dataOptions ?? {}, hookOptions),
  });
};
export const campaignControllerReadOneQueryKey = (
  options: OptionsLegacyParser<CampaignControllerReadOneData>
) => [createQueryKey('campaignControllerReadOne', options)];
export const campaignControllerReadOneOptions = <
  TResponse = CampaignControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<CampaignControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await campaignControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: campaignControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useCampaignControllerReadOneQuery = <
  TResponse = CampaignControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<CampaignControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...campaignControllerReadOneOptions(dataOptions ?? {}, hookOptions),
  });
};
export const campaignControllerUpdateMutation = <
  TResponse = CampaignControllerUpdateResponse,
>(
  options?: Partial<OptionsLegacyParser<CampaignControllerUpdateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CampaignControllerUpdateError,
      OptionsLegacyParser<CampaignControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    CampaignControllerUpdateError,
    OptionsLegacyParser<CampaignControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await campaignControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useCampaignControllerUpdate = <
  TResponse = CampaignControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<CampaignControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CampaignControllerUpdateError,
      OptionsLegacyParser<CampaignControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...campaignControllerUpdateMutation(dataOptions ?? {}, hookOptions),
  });
};
