// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  cardSocialControllerCreate,
  cardSocialControllerRead,
  cardSocialControllerUpdate,
  cardSocialControllerReadOne,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  CardSocialControllerCreateData,
  CardSocialControllerCreateError,
  CardSocialControllerCreateResponse,
  CardSocialControllerReadData,
  CardSocialControllerReadResponse,
  CardSocialControllerUpdateData,
  CardSocialControllerUpdateError,
  CardSocialControllerUpdateResponse,
  CardSocialControllerReadOneData,
  CardSocialControllerReadOneResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const cardSocialControllerCreateMutation = <
  TResponse = CardSocialControllerCreateResponse,
>(
  options?: Partial<OptionsLegacyParser<CardSocialControllerCreateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CardSocialControllerCreateError,
      OptionsLegacyParser<CardSocialControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    CardSocialControllerCreateError,
    OptionsLegacyParser<CardSocialControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await cardSocialControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useCardSocialControllerCreate = <
  TResponse = CardSocialControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<CardSocialControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CardSocialControllerCreateError,
      OptionsLegacyParser<CardSocialControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...cardSocialControllerCreateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const cardSocialControllerReadQueryKey = (
  options: OptionsLegacyParser<CardSocialControllerReadData>
) => [createQueryKey('cardSocialControllerRead', options)];
export const cardSocialControllerReadOptions = <
  TResponse = CardSocialControllerReadResponse,
>(
  options?: OptionsLegacyParser<CardSocialControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await cardSocialControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: cardSocialControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useCardSocialControllerReadQuery = <
  TResponse = CardSocialControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<CardSocialControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...cardSocialControllerReadOptions(dataOptions ?? {}, hookOptions),
  });
};
export const cardSocialControllerUpdateMutation = <
  TResponse = CardSocialControllerUpdateResponse,
>(
  options?: Partial<OptionsLegacyParser<CardSocialControllerUpdateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CardSocialControllerUpdateError,
      OptionsLegacyParser<CardSocialControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    CardSocialControllerUpdateError,
    OptionsLegacyParser<CardSocialControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await cardSocialControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useCardSocialControllerUpdate = <
  TResponse = CardSocialControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<CardSocialControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CardSocialControllerUpdateError,
      OptionsLegacyParser<CardSocialControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...cardSocialControllerUpdateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const cardSocialControllerReadOneQueryKey = (
  options: OptionsLegacyParser<CardSocialControllerReadOneData>
) => [createQueryKey('cardSocialControllerReadOne', options)];
export const cardSocialControllerReadOneOptions = <
  TResponse = CardSocialControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<CardSocialControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await cardSocialControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: cardSocialControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useCardSocialControllerReadOneQuery = <
  TResponse = CardSocialControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<CardSocialControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...cardSocialControllerReadOneOptions(dataOptions ?? {}, hookOptions),
  });
};
