// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  careerJobDetailControllerCreate,
  careerJobDetailControllerRead,
  careerJobDetailControllerUpdate,
  careerJobDetailControllerReadOne,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  CareerJobDetailControllerCreateData,
  CareerJobDetailControllerCreateError,
  CareerJobDetailControllerCreateResponse,
  CareerJobDetailControllerReadData,
  CareerJobDetailControllerReadResponse,
  CareerJobDetailControllerUpdateData,
  CareerJobDetailControllerUpdateError,
  CareerJobDetailControllerUpdateResponse,
  CareerJobDetailControllerReadOneData,
  CareerJobDetailControllerReadOneResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const careerJobDetailControllerCreateMutation = <
  TResponse = CareerJobDetailControllerCreateResponse,
>(
  options?: Partial<OptionsLegacyParser<CareerJobDetailControllerCreateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CareerJobDetailControllerCreateError,
      OptionsLegacyParser<CareerJobDetailControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    CareerJobDetailControllerCreateError,
    OptionsLegacyParser<CareerJobDetailControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await careerJobDetailControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useCareerJobDetailControllerCreate = <
  TResponse = CareerJobDetailControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<CareerJobDetailControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CareerJobDetailControllerCreateError,
      OptionsLegacyParser<CareerJobDetailControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...careerJobDetailControllerCreateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const careerJobDetailControllerReadQueryKey = (
  options: OptionsLegacyParser<CareerJobDetailControllerReadData>
) => [createQueryKey('careerJobDetailControllerRead', options)];
export const careerJobDetailControllerReadOptions = <
  TResponse = CareerJobDetailControllerReadResponse,
>(
  options?: OptionsLegacyParser<CareerJobDetailControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await careerJobDetailControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: careerJobDetailControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useCareerJobDetailControllerReadQuery = <
  TResponse = CareerJobDetailControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<CareerJobDetailControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...careerJobDetailControllerReadOptions(dataOptions ?? {}, hookOptions),
  });
};
export const careerJobDetailControllerUpdateMutation = <
  TResponse = CareerJobDetailControllerUpdateResponse,
>(
  options?: Partial<OptionsLegacyParser<CareerJobDetailControllerUpdateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CareerJobDetailControllerUpdateError,
      OptionsLegacyParser<CareerJobDetailControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    CareerJobDetailControllerUpdateError,
    OptionsLegacyParser<CareerJobDetailControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await careerJobDetailControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useCareerJobDetailControllerUpdate = <
  TResponse = CareerJobDetailControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<CareerJobDetailControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CareerJobDetailControllerUpdateError,
      OptionsLegacyParser<CareerJobDetailControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...careerJobDetailControllerUpdateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const careerJobDetailControllerReadOneQueryKey = (
  options: OptionsLegacyParser<CareerJobDetailControllerReadOneData>
) => [createQueryKey('careerJobDetailControllerReadOne', options)];
export const careerJobDetailControllerReadOneOptions = <
  TResponse = CareerJobDetailControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<CareerJobDetailControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await careerJobDetailControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: careerJobDetailControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useCareerJobDetailControllerReadOneQuery = <
  TResponse = CareerJobDetailControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<CareerJobDetailControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...careerJobDetailControllerReadOneOptions(dataOptions ?? {}, hookOptions),
  });
};
