// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  careerApplicationFormControllerCreate,
  careerApplicationFormControllerRead,
  careerApplicationFormControllerUpdate,
  careerApplicationFormControllerReadOne,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  CareerApplicationFormControllerCreateData,
  CareerApplicationFormControllerCreateError,
  CareerApplicationFormControllerCreateResponse,
  CareerApplicationFormControllerReadData,
  CareerApplicationFormControllerReadResponse,
  CareerApplicationFormControllerUpdateData,
  CareerApplicationFormControllerUpdateError,
  CareerApplicationFormControllerUpdateResponse,
  CareerApplicationFormControllerReadOneData,
  CareerApplicationFormControllerReadOneResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const careerApplicationFormControllerCreateMutation = <
  TResponse = CareerApplicationFormControllerCreateResponse,
>(
  options?: Partial<
    OptionsLegacyParser<CareerApplicationFormControllerCreateData>
  >,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CareerApplicationFormControllerCreateError,
      OptionsLegacyParser<CareerApplicationFormControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    CareerApplicationFormControllerCreateError,
    OptionsLegacyParser<CareerApplicationFormControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await careerApplicationFormControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useCareerApplicationFormControllerCreate = <
  TResponse = CareerApplicationFormControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<CareerApplicationFormControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CareerApplicationFormControllerCreateError,
      OptionsLegacyParser<CareerApplicationFormControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...careerApplicationFormControllerCreateMutation(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const careerApplicationFormControllerReadQueryKey = (
  options: OptionsLegacyParser<CareerApplicationFormControllerReadData>
) => [createQueryKey('careerApplicationFormControllerRead', options)];
export const careerApplicationFormControllerReadOptions = <
  TResponse = CareerApplicationFormControllerReadResponse,
>(
  options?: OptionsLegacyParser<CareerApplicationFormControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await careerApplicationFormControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: careerApplicationFormControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useCareerApplicationFormControllerReadQuery = <
  TResponse = CareerApplicationFormControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<CareerApplicationFormControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...careerApplicationFormControllerReadOptions(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const careerApplicationFormControllerUpdateMutation = <
  TResponse = CareerApplicationFormControllerUpdateResponse,
>(
  options?: Partial<
    OptionsLegacyParser<CareerApplicationFormControllerUpdateData>
  >,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CareerApplicationFormControllerUpdateError,
      OptionsLegacyParser<CareerApplicationFormControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    CareerApplicationFormControllerUpdateError,
    OptionsLegacyParser<CareerApplicationFormControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await careerApplicationFormControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useCareerApplicationFormControllerUpdate = <
  TResponse = CareerApplicationFormControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<CareerApplicationFormControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CareerApplicationFormControllerUpdateError,
      OptionsLegacyParser<CareerApplicationFormControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...careerApplicationFormControllerUpdateMutation(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const careerApplicationFormControllerReadOneQueryKey = (
  options: OptionsLegacyParser<CareerApplicationFormControllerReadOneData>
) => [createQueryKey('careerApplicationFormControllerReadOne', options)];
export const careerApplicationFormControllerReadOneOptions = <
  TResponse = CareerApplicationFormControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<CareerApplicationFormControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await careerApplicationFormControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: careerApplicationFormControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useCareerApplicationFormControllerReadOneQuery = <
  TResponse = CareerApplicationFormControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<CareerApplicationFormControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...careerApplicationFormControllerReadOneOptions(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
