// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  contactUsHeroControllerCreate,
  contactUsHeroControllerRead,
  contactUsHeroControllerUpdate,
  contactUsHeroControllerReadOne,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  ContactUsHeroControllerCreateData,
  ContactUsHeroControllerCreateError,
  ContactUsHeroControllerCreateResponse,
  ContactUsHeroControllerReadData,
  ContactUsHeroControllerReadResponse,
  ContactUsHeroControllerUpdateData,
  ContactUsHeroControllerUpdateError,
  ContactUsHeroControllerUpdateResponse,
  ContactUsHeroControllerReadOneData,
  ContactUsHeroControllerReadOneResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const contactUsHeroControllerCreateMutation = <
  TResponse = ContactUsHeroControllerCreateResponse,
>(
  options?: Partial<OptionsLegacyParser<ContactUsHeroControllerCreateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ContactUsHeroControllerCreateError,
      OptionsLegacyParser<ContactUsHeroControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    ContactUsHeroControllerCreateError,
    OptionsLegacyParser<ContactUsHeroControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await contactUsHeroControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useContactUsHeroControllerCreate = <
  TResponse = ContactUsHeroControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<ContactUsHeroControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ContactUsHeroControllerCreateError,
      OptionsLegacyParser<ContactUsHeroControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...contactUsHeroControllerCreateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const contactUsHeroControllerReadQueryKey = (
  options: OptionsLegacyParser<ContactUsHeroControllerReadData>
) => [createQueryKey('contactUsHeroControllerRead', options)];
export const contactUsHeroControllerReadOptions = <
  TResponse = ContactUsHeroControllerReadResponse,
>(
  options?: OptionsLegacyParser<ContactUsHeroControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await contactUsHeroControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: contactUsHeroControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useContactUsHeroControllerReadQuery = <
  TResponse = ContactUsHeroControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<ContactUsHeroControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...contactUsHeroControllerReadOptions(dataOptions ?? {}, hookOptions),
  });
};
export const contactUsHeroControllerUpdateMutation = <
  TResponse = ContactUsHeroControllerUpdateResponse,
>(
  options?: Partial<OptionsLegacyParser<ContactUsHeroControllerUpdateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ContactUsHeroControllerUpdateError,
      OptionsLegacyParser<ContactUsHeroControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    ContactUsHeroControllerUpdateError,
    OptionsLegacyParser<ContactUsHeroControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await contactUsHeroControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useContactUsHeroControllerUpdate = <
  TResponse = ContactUsHeroControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<ContactUsHeroControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ContactUsHeroControllerUpdateError,
      OptionsLegacyParser<ContactUsHeroControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...contactUsHeroControllerUpdateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const contactUsHeroControllerReadOneQueryKey = (
  options: OptionsLegacyParser<ContactUsHeroControllerReadOneData>
) => [createQueryKey('contactUsHeroControllerReadOne', options)];
export const contactUsHeroControllerReadOneOptions = <
  TResponse = ContactUsHeroControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<ContactUsHeroControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await contactUsHeroControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: contactUsHeroControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useContactUsHeroControllerReadOneQuery = <
  TResponse = ContactUsHeroControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<ContactUsHeroControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...contactUsHeroControllerReadOneOptions(dataOptions ?? {}, hookOptions),
  });
};
