// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  contactUsControllerCreate,
  contactUsControllerRead,
  contactUsControllerUpdate,
  contactUsControllerReadOne,
  contactUsControllerDelete,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  ContactUsControllerCreateData,
  ContactUsControllerCreateError,
  ContactUsControllerCreateResponse,
  ContactUsControllerReadData,
  ContactUsControllerReadResponse,
  ContactUsControllerUpdateData,
  ContactUsControllerUpdateError,
  ContactUsControllerUpdateResponse,
  ContactUsControllerReadOneData,
  ContactUsControllerReadOneResponse,
  ContactUsControllerDeleteData,
  ContactUsControllerDeleteError,
  ContactUsControllerDeleteResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const contactUsControllerCreateMutation = <
  TResponse = ContactUsControllerCreateResponse,
>(
  options?: Partial<OptionsLegacyParser<ContactUsControllerCreateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ContactUsControllerCreateError,
      OptionsLegacyParser<ContactUsControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    ContactUsControllerCreateError,
    OptionsLegacyParser<ContactUsControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await contactUsControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useContactUsControllerCreate = <
  TResponse = ContactUsControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<ContactUsControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ContactUsControllerCreateError,
      OptionsLegacyParser<ContactUsControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...contactUsControllerCreateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const contactUsControllerReadQueryKey = (
  options: OptionsLegacyParser<ContactUsControllerReadData>
) => [createQueryKey('contactUsControllerRead', options)];
export const contactUsControllerReadOptions = <
  TResponse = ContactUsControllerReadResponse,
>(
  options?: OptionsLegacyParser<ContactUsControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await contactUsControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: contactUsControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useContactUsControllerReadQuery = <
  TResponse = ContactUsControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<ContactUsControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...contactUsControllerReadOptions(dataOptions ?? {}, hookOptions),
  });
};
export const contactUsControllerUpdateMutation = <
  TResponse = ContactUsControllerUpdateResponse,
>(
  options?: Partial<OptionsLegacyParser<ContactUsControllerUpdateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ContactUsControllerUpdateError,
      OptionsLegacyParser<ContactUsControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    ContactUsControllerUpdateError,
    OptionsLegacyParser<ContactUsControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await contactUsControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useContactUsControllerUpdate = <
  TResponse = ContactUsControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<ContactUsControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ContactUsControllerUpdateError,
      OptionsLegacyParser<ContactUsControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...contactUsControllerUpdateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const contactUsControllerReadOneQueryKey = (
  options: OptionsLegacyParser<ContactUsControllerReadOneData>
) => [createQueryKey('contactUsControllerReadOne', options)];
export const contactUsControllerReadOneOptions = <
  TResponse = ContactUsControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<ContactUsControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await contactUsControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: contactUsControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useContactUsControllerReadOneQuery = <
  TResponse = ContactUsControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<ContactUsControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...contactUsControllerReadOneOptions(dataOptions ?? {}, hookOptions),
  });
};
export const contactUsControllerDeleteMutation = <
  TResponse = ContactUsControllerDeleteResponse,
>(
  options?: Partial<OptionsLegacyParser<ContactUsControllerDeleteData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ContactUsControllerDeleteError,
      OptionsLegacyParser<ContactUsControllerDeleteData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    ContactUsControllerDeleteError,
    OptionsLegacyParser<ContactUsControllerDeleteData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await contactUsControllerDelete({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useContactUsControllerDelete = <
  TResponse = ContactUsControllerDeleteResponse,
>(
  dataOptions?: OptionsLegacyParser<ContactUsControllerDeleteData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ContactUsControllerDeleteError,
      OptionsLegacyParser<ContactUsControllerDeleteData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...contactUsControllerDeleteMutation(dataOptions ?? {}, hookOptions),
  });
};
