// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  cybersecurityHeroControllerCreate,
  cybersecurityHeroControllerRead,
  cybersecurityHeroControllerReadOne,
  cybersecurityHeroControllerUpdate,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  CybersecurityHeroControllerCreateData,
  CybersecurityHeroControllerCreateError,
  CybersecurityHeroControllerCreateResponse,
  CybersecurityHeroControllerReadData,
  CybersecurityHeroControllerReadResponse,
  CybersecurityHeroControllerReadOneData,
  CybersecurityHeroControllerReadOneResponse,
  CybersecurityHeroControllerUpdateData,
  CybersecurityHeroControllerUpdateError,
  CybersecurityHeroControllerUpdateResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const cybersecurityHeroControllerCreateMutation = <
  TResponse = CybersecurityHeroControllerCreateResponse,
>(
  options?: Partial<OptionsLegacyParser<CybersecurityHeroControllerCreateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CybersecurityHeroControllerCreateError,
      OptionsLegacyParser<CybersecurityHeroControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    CybersecurityHeroControllerCreateError,
    OptionsLegacyParser<CybersecurityHeroControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await cybersecurityHeroControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useCybersecurityHeroControllerCreate = <
  TResponse = CybersecurityHeroControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<CybersecurityHeroControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CybersecurityHeroControllerCreateError,
      OptionsLegacyParser<CybersecurityHeroControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...cybersecurityHeroControllerCreateMutation(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const cybersecurityHeroControllerReadQueryKey = (
  options: OptionsLegacyParser<CybersecurityHeroControllerReadData>
) => [createQueryKey('cybersecurityHeroControllerRead', options)];
export const cybersecurityHeroControllerReadOptions = <
  TResponse = CybersecurityHeroControllerReadResponse,
>(
  options?: OptionsLegacyParser<CybersecurityHeroControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await cybersecurityHeroControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: cybersecurityHeroControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useCybersecurityHeroControllerReadQuery = <
  TResponse = CybersecurityHeroControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<CybersecurityHeroControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...cybersecurityHeroControllerReadOptions(dataOptions ?? {}, hookOptions),
  });
};
export const cybersecurityHeroControllerReadOneQueryKey = (
  options: OptionsLegacyParser<CybersecurityHeroControllerReadOneData>
) => [createQueryKey('cybersecurityHeroControllerReadOne', options)];
export const cybersecurityHeroControllerReadOneOptions = <
  TResponse = CybersecurityHeroControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<CybersecurityHeroControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await cybersecurityHeroControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: cybersecurityHeroControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useCybersecurityHeroControllerReadOneQuery = <
  TResponse = CybersecurityHeroControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<CybersecurityHeroControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...cybersecurityHeroControllerReadOneOptions(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const cybersecurityHeroControllerUpdateMutation = <
  TResponse = CybersecurityHeroControllerUpdateResponse,
>(
  options?: Partial<OptionsLegacyParser<CybersecurityHeroControllerUpdateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CybersecurityHeroControllerUpdateError,
      OptionsLegacyParser<CybersecurityHeroControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    CybersecurityHeroControllerUpdateError,
    OptionsLegacyParser<CybersecurityHeroControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await cybersecurityHeroControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useCybersecurityHeroControllerUpdate = <
  TResponse = CybersecurityHeroControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<CybersecurityHeroControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      CybersecurityHeroControllerUpdateError,
      OptionsLegacyParser<CybersecurityHeroControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...cybersecurityHeroControllerUpdateMutation(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
