// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  dataManagementControllerCreate,
  dataManagementControllerRead,
  dataManagementControllerUpdate,
  dataManagementControllerReadOne,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  DataManagementControllerCreateData,
  DataManagementControllerCreateError,
  DataManagementControllerCreateResponse,
  DataManagementControllerReadData,
  DataManagementControllerReadResponse,
  DataManagementControllerUpdateData,
  DataManagementControllerUpdateError,
  DataManagementControllerUpdateResponse,
  DataManagementControllerReadOneData,
  DataManagementControllerReadOneResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const dataManagementControllerCreateMutation = <
  TResponse = DataManagementControllerCreateResponse,
>(
  options?: Partial<OptionsLegacyParser<DataManagementControllerCreateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      DataManagementControllerCreateError,
      OptionsLegacyParser<DataManagementControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    DataManagementControllerCreateError,
    OptionsLegacyParser<DataManagementControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await dataManagementControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useDataManagementControllerCreate = <
  TResponse = DataManagementControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<DataManagementControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      DataManagementControllerCreateError,
      OptionsLegacyParser<DataManagementControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...dataManagementControllerCreateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const dataManagementControllerReadQueryKey = (
  options: OptionsLegacyParser<DataManagementControllerReadData>
) => [createQueryKey('dataManagementControllerRead', options)];
export const dataManagementControllerReadOptions = <
  TResponse = DataManagementControllerReadResponse,
>(
  options?: OptionsLegacyParser<DataManagementControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await dataManagementControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: dataManagementControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useDataManagementControllerReadQuery = <
  TResponse = DataManagementControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<DataManagementControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...dataManagementControllerReadOptions(dataOptions ?? {}, hookOptions),
  });
};
export const dataManagementControllerUpdateMutation = <
  TResponse = DataManagementControllerUpdateResponse,
>(
  options?: Partial<OptionsLegacyParser<DataManagementControllerUpdateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      DataManagementControllerUpdateError,
      OptionsLegacyParser<DataManagementControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    DataManagementControllerUpdateError,
    OptionsLegacyParser<DataManagementControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await dataManagementControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useDataManagementControllerUpdate = <
  TResponse = DataManagementControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<DataManagementControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      DataManagementControllerUpdateError,
      OptionsLegacyParser<DataManagementControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...dataManagementControllerUpdateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const dataManagementControllerReadOneQueryKey = (
  options: OptionsLegacyParser<DataManagementControllerReadOneData>
) => [createQueryKey('dataManagementControllerReadOne', options)];
export const dataManagementControllerReadOneOptions = <
  TResponse = DataManagementControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<DataManagementControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await dataManagementControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: dataManagementControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useDataManagementControllerReadOneQuery = <
  TResponse = DataManagementControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<DataManagementControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...dataManagementControllerReadOneOptions(dataOptions ?? {}, hookOptions),
  });
};
