// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  environmentalSustainabilityControllerCreate,
  environmentalSustainabilityControllerRead,
  environmentalSustainabilityControllerUpdate,
  environmentalSustainabilityControllerReadOne,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  EnvironmentalSustainabilityControllerCreateData,
  EnvironmentalSustainabilityControllerCreateError,
  EnvironmentalSustainabilityControllerCreateResponse,
  EnvironmentalSustainabilityControllerReadData,
  EnvironmentalSustainabilityControllerReadResponse,
  EnvironmentalSustainabilityControllerUpdateData,
  EnvironmentalSustainabilityControllerUpdateError,
  EnvironmentalSustainabilityControllerUpdateResponse,
  EnvironmentalSustainabilityControllerReadOneData,
  EnvironmentalSustainabilityControllerReadOneResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const environmentalSustainabilityControllerCreateMutation = <
  TResponse = EnvironmentalSustainabilityControllerCreateResponse,
>(
  options?: Partial<
    OptionsLegacyParser<EnvironmentalSustainabilityControllerCreateData>
  >,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      EnvironmentalSustainabilityControllerCreateError,
      OptionsLegacyParser<EnvironmentalSustainabilityControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    EnvironmentalSustainabilityControllerCreateError,
    OptionsLegacyParser<EnvironmentalSustainabilityControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await environmentalSustainabilityControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useEnvironmentalSustainabilityControllerCreate = <
  TResponse = EnvironmentalSustainabilityControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<EnvironmentalSustainabilityControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      EnvironmentalSustainabilityControllerCreateError,
      OptionsLegacyParser<EnvironmentalSustainabilityControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...environmentalSustainabilityControllerCreateMutation(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const environmentalSustainabilityControllerReadQueryKey = (
  options: OptionsLegacyParser<EnvironmentalSustainabilityControllerReadData>
) => [createQueryKey('environmentalSustainabilityControllerRead', options)];
export const environmentalSustainabilityControllerReadOptions = <
  TResponse = EnvironmentalSustainabilityControllerReadResponse,
>(
  options?: OptionsLegacyParser<EnvironmentalSustainabilityControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await environmentalSustainabilityControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: environmentalSustainabilityControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useEnvironmentalSustainabilityControllerReadQuery = <
  TResponse = EnvironmentalSustainabilityControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<EnvironmentalSustainabilityControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...environmentalSustainabilityControllerReadOptions(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const environmentalSustainabilityControllerUpdateMutation = <
  TResponse = EnvironmentalSustainabilityControllerUpdateResponse,
>(
  options?: Partial<
    OptionsLegacyParser<EnvironmentalSustainabilityControllerUpdateData>
  >,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      EnvironmentalSustainabilityControllerUpdateError,
      OptionsLegacyParser<EnvironmentalSustainabilityControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    EnvironmentalSustainabilityControllerUpdateError,
    OptionsLegacyParser<EnvironmentalSustainabilityControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await environmentalSustainabilityControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useEnvironmentalSustainabilityControllerUpdate = <
  TResponse = EnvironmentalSustainabilityControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<EnvironmentalSustainabilityControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      EnvironmentalSustainabilityControllerUpdateError,
      OptionsLegacyParser<EnvironmentalSustainabilityControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...environmentalSustainabilityControllerUpdateMutation(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const environmentalSustainabilityControllerReadOneQueryKey = (
  options: OptionsLegacyParser<EnvironmentalSustainabilityControllerReadOneData>
) => [createQueryKey('environmentalSustainabilityControllerReadOne', options)];
export const environmentalSustainabilityControllerReadOneOptions = <
  TResponse = EnvironmentalSustainabilityControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<EnvironmentalSustainabilityControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await environmentalSustainabilityControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: environmentalSustainabilityControllerReadOneQueryKey(
      options ?? {}
    ),
    ...hookOptions,
  });
};
export const useEnvironmentalSustainabilityControllerReadOneQuery = <
  TResponse = EnvironmentalSustainabilityControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<EnvironmentalSustainabilityControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...environmentalSustainabilityControllerReadOneOptions(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
