// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  eventsPartnerControllerCreate,
  eventsPartnerControllerRead,
  eventsPartnerControllerUpdate,
  eventsPartnerControllerReadOne,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  EventsPartnerControllerCreateData,
  EventsPartnerControllerCreateError,
  EventsPartnerControllerCreateResponse,
  EventsPartnerControllerReadData,
  EventsPartnerControllerReadResponse,
  EventsPartnerControllerUpdateData,
  EventsPartnerControllerUpdateError,
  EventsPartnerControllerUpdateResponse,
  EventsPartnerControllerReadOneData,
  EventsPartnerControllerReadOneResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const eventsPartnerControllerCreateMutation = <
  TResponse = EventsPartnerControllerCreateResponse,
>(
  options?: Partial<OptionsLegacyParser<EventsPartnerControllerCreateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      EventsPartnerControllerCreateError,
      OptionsLegacyParser<EventsPartnerControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    EventsPartnerControllerCreateError,
    OptionsLegacyParser<EventsPartnerControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await eventsPartnerControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useEventsPartnerControllerCreate = <
  TResponse = EventsPartnerControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<EventsPartnerControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      EventsPartnerControllerCreateError,
      OptionsLegacyParser<EventsPartnerControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...eventsPartnerControllerCreateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const eventsPartnerControllerReadQueryKey = (
  options: OptionsLegacyParser<EventsPartnerControllerReadData>
) => [createQueryKey('eventsPartnerControllerRead', options)];
export const eventsPartnerControllerReadOptions = <
  TResponse = EventsPartnerControllerReadResponse,
>(
  options?: OptionsLegacyParser<EventsPartnerControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await eventsPartnerControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: eventsPartnerControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useEventsPartnerControllerReadQuery = <
  TResponse = EventsPartnerControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<EventsPartnerControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...eventsPartnerControllerReadOptions(dataOptions ?? {}, hookOptions),
  });
};
export const eventsPartnerControllerUpdateMutation = <
  TResponse = EventsPartnerControllerUpdateResponse,
>(
  options?: Partial<OptionsLegacyParser<EventsPartnerControllerUpdateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      EventsPartnerControllerUpdateError,
      OptionsLegacyParser<EventsPartnerControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    EventsPartnerControllerUpdateError,
    OptionsLegacyParser<EventsPartnerControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await eventsPartnerControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useEventsPartnerControllerUpdate = <
  TResponse = EventsPartnerControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<EventsPartnerControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      EventsPartnerControllerUpdateError,
      OptionsLegacyParser<EventsPartnerControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...eventsPartnerControllerUpdateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const eventsPartnerControllerReadOneQueryKey = (
  options: OptionsLegacyParser<EventsPartnerControllerReadOneData>
) => [createQueryKey('eventsPartnerControllerReadOne', options)];
export const eventsPartnerControllerReadOneOptions = <
  TResponse = EventsPartnerControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<EventsPartnerControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await eventsPartnerControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: eventsPartnerControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useEventsPartnerControllerReadOneQuery = <
  TResponse = EventsPartnerControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<EventsPartnerControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...eventsPartnerControllerReadOneOptions(dataOptions ?? {}, hookOptions),
  });
};
