// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  footerContactsControllerCreate,
  footerContactsControllerRead,
  footerContactsControllerUpdate,
  footerContactsControllerReadOne,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  FooterContactsControllerCreateData,
  FooterContactsControllerCreateError,
  FooterContactsControllerCreateResponse,
  FooterContactsControllerReadData,
  FooterContactsControllerReadResponse,
  FooterContactsControllerUpdateData,
  FooterContactsControllerUpdateError,
  FooterContactsControllerUpdateResponse,
  FooterContactsControllerReadOneData,
  FooterContactsControllerReadOneResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const footerContactsControllerCreateMutation = <
  TResponse = FooterContactsControllerCreateResponse,
>(
  options?: Partial<OptionsLegacyParser<FooterContactsControllerCreateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      FooterContactsControllerCreateError,
      OptionsLegacyParser<FooterContactsControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    FooterContactsControllerCreateError,
    OptionsLegacyParser<FooterContactsControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await footerContactsControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useFooterContactsControllerCreate = <
  TResponse = FooterContactsControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<FooterContactsControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      FooterContactsControllerCreateError,
      OptionsLegacyParser<FooterContactsControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...footerContactsControllerCreateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const footerContactsControllerReadQueryKey = (
  options: OptionsLegacyParser<FooterContactsControllerReadData>
) => [createQueryKey('footerContactsControllerRead', options)];
export const footerContactsControllerReadOptions = <
  TResponse = FooterContactsControllerReadResponse,
>(
  options?: OptionsLegacyParser<FooterContactsControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await footerContactsControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: footerContactsControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useFooterContactsControllerReadQuery = <
  TResponse = FooterContactsControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<FooterContactsControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...footerContactsControllerReadOptions(dataOptions ?? {}, hookOptions),
  });
};
export const footerContactsControllerUpdateMutation = <
  TResponse = FooterContactsControllerUpdateResponse,
>(
  options?: Partial<OptionsLegacyParser<FooterContactsControllerUpdateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      FooterContactsControllerUpdateError,
      OptionsLegacyParser<FooterContactsControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    FooterContactsControllerUpdateError,
    OptionsLegacyParser<FooterContactsControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await footerContactsControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useFooterContactsControllerUpdate = <
  TResponse = FooterContactsControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<FooterContactsControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      FooterContactsControllerUpdateError,
      OptionsLegacyParser<FooterContactsControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...footerContactsControllerUpdateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const footerContactsControllerReadOneQueryKey = (
  options: OptionsLegacyParser<FooterContactsControllerReadOneData>
) => [createQueryKey('footerContactsControllerReadOne', options)];
export const footerContactsControllerReadOneOptions = <
  TResponse = FooterContactsControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<FooterContactsControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await footerContactsControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: footerContactsControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useFooterContactsControllerReadOneQuery = <
  TResponse = FooterContactsControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<FooterContactsControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...footerContactsControllerReadOneOptions(dataOptions ?? {}, hookOptions),
  });
};
