// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  identityManagementControllerCreate,
  identityManagementControllerRead,
  identityManagementControllerReadOne,
  identityManagementControllerUpdate,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  IdentityManagementControllerCreateData,
  IdentityManagementControllerCreateError,
  IdentityManagementControllerCreateResponse,
  IdentityManagementControllerReadData,
  IdentityManagementControllerReadResponse,
  IdentityManagementControllerReadOneData,
  IdentityManagementControllerReadOneResponse,
  IdentityManagementControllerUpdateData,
  IdentityManagementControllerUpdateError,
  IdentityManagementControllerUpdateResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const identityManagementControllerCreateMutation = <
  TResponse = IdentityManagementControllerCreateResponse,
>(
  options?: Partial<
    OptionsLegacyParser<IdentityManagementControllerCreateData>
  >,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      IdentityManagementControllerCreateError,
      OptionsLegacyParser<IdentityManagementControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    IdentityManagementControllerCreateError,
    OptionsLegacyParser<IdentityManagementControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await identityManagementControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useIdentityManagementControllerCreate = <
  TResponse = IdentityManagementControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<IdentityManagementControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      IdentityManagementControllerCreateError,
      OptionsLegacyParser<IdentityManagementControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...identityManagementControllerCreateMutation(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const identityManagementControllerReadQueryKey = (
  options: OptionsLegacyParser<IdentityManagementControllerReadData>
) => [createQueryKey('identityManagementControllerRead', options)];
export const identityManagementControllerReadOptions = <
  TResponse = IdentityManagementControllerReadResponse,
>(
  options?: OptionsLegacyParser<IdentityManagementControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await identityManagementControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: identityManagementControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useIdentityManagementControllerReadQuery = <
  TResponse = IdentityManagementControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<IdentityManagementControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...identityManagementControllerReadOptions(dataOptions ?? {}, hookOptions),
  });
};
export const identityManagementControllerReadOneQueryKey = (
  options: OptionsLegacyParser<IdentityManagementControllerReadOneData>
) => [createQueryKey('identityManagementControllerReadOne', options)];
export const identityManagementControllerReadOneOptions = <
  TResponse = IdentityManagementControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<IdentityManagementControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await identityManagementControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: identityManagementControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useIdentityManagementControllerReadOneQuery = <
  TResponse = IdentityManagementControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<IdentityManagementControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...identityManagementControllerReadOneOptions(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const identityManagementControllerUpdateMutation = <
  TResponse = IdentityManagementControllerUpdateResponse,
>(
  options?: Partial<
    OptionsLegacyParser<IdentityManagementControllerUpdateData>
  >,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      IdentityManagementControllerUpdateError,
      OptionsLegacyParser<IdentityManagementControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    IdentityManagementControllerUpdateError,
    OptionsLegacyParser<IdentityManagementControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await identityManagementControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useIdentityManagementControllerUpdate = <
  TResponse = IdentityManagementControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<IdentityManagementControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      IdentityManagementControllerUpdateError,
      OptionsLegacyParser<IdentityManagementControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...identityManagementControllerUpdateMutation(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
