// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  leadershipControllerCreate,
  leadershipControllerRead,
  leadershipControllerUpdate,
  leadershipControllerReadOne,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  LeadershipControllerCreateData,
  LeadershipControllerCreateError,
  LeadershipControllerCreateResponse,
  LeadershipControllerReadData,
  LeadershipControllerReadResponse,
  LeadershipControllerUpdateData,
  LeadershipControllerUpdateError,
  LeadershipControllerUpdateResponse,
  LeadershipControllerReadOneData,
  LeadershipControllerReadOneResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const leadershipControllerCreateMutation = <
  TResponse = LeadershipControllerCreateResponse,
>(
  options?: Partial<OptionsLegacyParser<LeadershipControllerCreateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      LeadershipControllerCreateError,
      OptionsLegacyParser<LeadershipControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    LeadershipControllerCreateError,
    OptionsLegacyParser<LeadershipControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await leadershipControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useLeadershipControllerCreate = <
  TResponse = LeadershipControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<LeadershipControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      LeadershipControllerCreateError,
      OptionsLegacyParser<LeadershipControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...leadershipControllerCreateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const leadershipControllerReadQueryKey = (
  options: OptionsLegacyParser<LeadershipControllerReadData>
) => [createQueryKey('leadershipControllerRead', options)];
export const leadershipControllerReadOptions = <
  TResponse = LeadershipControllerReadResponse,
>(
  options?: OptionsLegacyParser<LeadershipControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await leadershipControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: leadershipControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useLeadershipControllerReadQuery = <
  TResponse = LeadershipControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<LeadershipControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...leadershipControllerReadOptions(dataOptions ?? {}, hookOptions),
  });
};
export const leadershipControllerUpdateMutation = <
  TResponse = LeadershipControllerUpdateResponse,
>(
  options?: Partial<OptionsLegacyParser<LeadershipControllerUpdateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      LeadershipControllerUpdateError,
      OptionsLegacyParser<LeadershipControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    LeadershipControllerUpdateError,
    OptionsLegacyParser<LeadershipControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await leadershipControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useLeadershipControllerUpdate = <
  TResponse = LeadershipControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<LeadershipControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      LeadershipControllerUpdateError,
      OptionsLegacyParser<LeadershipControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...leadershipControllerUpdateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const leadershipControllerReadOneQueryKey = (
  options: OptionsLegacyParser<LeadershipControllerReadOneData>
) => [createQueryKey('leadershipControllerReadOne', options)];
export const leadershipControllerReadOneOptions = <
  TResponse = LeadershipControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<LeadershipControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await leadershipControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: leadershipControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useLeadershipControllerReadOneQuery = <
  TResponse = LeadershipControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<LeadershipControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...leadershipControllerReadOneOptions(dataOptions ?? {}, hookOptions),
  });
};
