// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  managedSocServicesDetailsControllerCreate,
  managedSocServicesDetailsControllerRead,
  managedSocServicesDetailsControllerUpdate,
  managedSocServicesDetailsControllerReadOne,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  ManagedSocServicesDetailsControllerCreateData,
  ManagedSocServicesDetailsControllerCreateError,
  ManagedSocServicesDetailsControllerCreateResponse,
  ManagedSocServicesDetailsControllerReadData,
  ManagedSocServicesDetailsControllerReadResponse,
  ManagedSocServicesDetailsControllerUpdateData,
  ManagedSocServicesDetailsControllerUpdateError,
  ManagedSocServicesDetailsControllerUpdateResponse,
  ManagedSocServicesDetailsControllerReadOneData,
  ManagedSocServicesDetailsControllerReadOneResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const managedSocServicesDetailsControllerCreateMutation = <
  TResponse = ManagedSocServicesDetailsControllerCreateResponse,
>(
  options?: Partial<
    OptionsLegacyParser<ManagedSocServicesDetailsControllerCreateData>
  >,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ManagedSocServicesDetailsControllerCreateError,
      OptionsLegacyParser<ManagedSocServicesDetailsControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    ManagedSocServicesDetailsControllerCreateError,
    OptionsLegacyParser<ManagedSocServicesDetailsControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await managedSocServicesDetailsControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useManagedSocServicesDetailsControllerCreate = <
  TResponse = ManagedSocServicesDetailsControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<ManagedSocServicesDetailsControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ManagedSocServicesDetailsControllerCreateError,
      OptionsLegacyParser<ManagedSocServicesDetailsControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...managedSocServicesDetailsControllerCreateMutation(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const managedSocServicesDetailsControllerReadQueryKey = (
  options: OptionsLegacyParser<ManagedSocServicesDetailsControllerReadData>
) => [createQueryKey('managedSocServicesDetailsControllerRead', options)];
export const managedSocServicesDetailsControllerReadOptions = <
  TResponse = ManagedSocServicesDetailsControllerReadResponse,
>(
  options?: OptionsLegacyParser<ManagedSocServicesDetailsControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await managedSocServicesDetailsControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: managedSocServicesDetailsControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useManagedSocServicesDetailsControllerReadQuery = <
  TResponse = ManagedSocServicesDetailsControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<ManagedSocServicesDetailsControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...managedSocServicesDetailsControllerReadOptions(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const managedSocServicesDetailsControllerUpdateMutation = <
  TResponse = ManagedSocServicesDetailsControllerUpdateResponse,
>(
  options?: Partial<
    OptionsLegacyParser<ManagedSocServicesDetailsControllerUpdateData>
  >,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ManagedSocServicesDetailsControllerUpdateError,
      OptionsLegacyParser<ManagedSocServicesDetailsControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    ManagedSocServicesDetailsControllerUpdateError,
    OptionsLegacyParser<ManagedSocServicesDetailsControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await managedSocServicesDetailsControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useManagedSocServicesDetailsControllerUpdate = <
  TResponse = ManagedSocServicesDetailsControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<ManagedSocServicesDetailsControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ManagedSocServicesDetailsControllerUpdateError,
      OptionsLegacyParser<ManagedSocServicesDetailsControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...managedSocServicesDetailsControllerUpdateMutation(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const managedSocServicesDetailsControllerReadOneQueryKey = (
  options: OptionsLegacyParser<ManagedSocServicesDetailsControllerReadOneData>
) => [createQueryKey('managedSocServicesDetailsControllerReadOne', options)];
export const managedSocServicesDetailsControllerReadOneOptions = <
  TResponse = ManagedSocServicesDetailsControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<ManagedSocServicesDetailsControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await managedSocServicesDetailsControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: managedSocServicesDetailsControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useManagedSocServicesDetailsControllerReadOneQuery = <
  TResponse = ManagedSocServicesDetailsControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<ManagedSocServicesDetailsControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...managedSocServicesDetailsControllerReadOneOptions(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
