// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  managedServiceHeroControllerCreate,
  managedServiceHeroControllerRead,
  managedServiceHeroControllerUpdate,
  managedServiceHeroControllerReadOne,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  ManagedServiceHeroControllerCreateData,
  ManagedServiceHeroControllerCreateError,
  ManagedServiceHeroControllerCreateResponse,
  ManagedServiceHeroControllerReadData,
  ManagedServiceHeroControllerReadResponse,
  ManagedServiceHeroControllerUpdateData,
  ManagedServiceHeroControllerUpdateError,
  ManagedServiceHeroControllerUpdateResponse,
  ManagedServiceHeroControllerReadOneData,
  ManagedServiceHeroControllerReadOneResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const managedServiceHeroControllerCreateMutation = <
  TResponse = ManagedServiceHeroControllerCreateResponse,
>(
  options?: Partial<
    OptionsLegacyParser<ManagedServiceHeroControllerCreateData>
  >,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ManagedServiceHeroControllerCreateError,
      OptionsLegacyParser<ManagedServiceHeroControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    ManagedServiceHeroControllerCreateError,
    OptionsLegacyParser<ManagedServiceHeroControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await managedServiceHeroControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useManagedServiceHeroControllerCreate = <
  TResponse = ManagedServiceHeroControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<ManagedServiceHeroControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ManagedServiceHeroControllerCreateError,
      OptionsLegacyParser<ManagedServiceHeroControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...managedServiceHeroControllerCreateMutation(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const managedServiceHeroControllerReadQueryKey = (
  options: OptionsLegacyParser<ManagedServiceHeroControllerReadData>
) => [createQueryKey('managedServiceHeroControllerRead', options)];
export const managedServiceHeroControllerReadOptions = <
  TResponse = ManagedServiceHeroControllerReadResponse,
>(
  options?: OptionsLegacyParser<ManagedServiceHeroControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await managedServiceHeroControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: managedServiceHeroControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useManagedServiceHeroControllerReadQuery = <
  TResponse = ManagedServiceHeroControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<ManagedServiceHeroControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...managedServiceHeroControllerReadOptions(dataOptions ?? {}, hookOptions),
  });
};
export const managedServiceHeroControllerUpdateMutation = <
  TResponse = ManagedServiceHeroControllerUpdateResponse,
>(
  options?: Partial<
    OptionsLegacyParser<ManagedServiceHeroControllerUpdateData>
  >,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ManagedServiceHeroControllerUpdateError,
      OptionsLegacyParser<ManagedServiceHeroControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    ManagedServiceHeroControllerUpdateError,
    OptionsLegacyParser<ManagedServiceHeroControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await managedServiceHeroControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useManagedServiceHeroControllerUpdate = <
  TResponse = ManagedServiceHeroControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<ManagedServiceHeroControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ManagedServiceHeroControllerUpdateError,
      OptionsLegacyParser<ManagedServiceHeroControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...managedServiceHeroControllerUpdateMutation(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
export const managedServiceHeroControllerReadOneQueryKey = (
  options: OptionsLegacyParser<ManagedServiceHeroControllerReadOneData>
) => [createQueryKey('managedServiceHeroControllerReadOne', options)];
export const managedServiceHeroControllerReadOneOptions = <
  TResponse = ManagedServiceHeroControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<ManagedServiceHeroControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await managedServiceHeroControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: managedServiceHeroControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useManagedServiceHeroControllerReadOneQuery = <
  TResponse = ManagedServiceHeroControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<ManagedServiceHeroControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...managedServiceHeroControllerReadOneOptions(
      dataOptions ?? {},
      hookOptions
    ),
  });
};
