// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  permissionsControllerUpdate,
  permissionsControllerReadOne,
  permissionsControllerRead,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  PermissionsControllerUpdateData,
  PermissionsControllerUpdateError,
  PermissionsControllerUpdateResponse,
  PermissionsControllerReadOneData,
  PermissionsControllerReadOneResponse,
  PermissionsControllerReadData,
  PermissionsControllerReadResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const permissionsControllerUpdateMutation = <
  TResponse = PermissionsControllerUpdateResponse,
>(
  options?: Partial<OptionsLegacyParser<PermissionsControllerUpdateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      PermissionsControllerUpdateError,
      OptionsLegacyParser<PermissionsControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    PermissionsControllerUpdateError,
    OptionsLegacyParser<PermissionsControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await permissionsControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const usePermissionsControllerUpdate = <
  TResponse = PermissionsControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<PermissionsControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      PermissionsControllerUpdateError,
      OptionsLegacyParser<PermissionsControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...permissionsControllerUpdateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const permissionsControllerReadOneQueryKey = (
  options: OptionsLegacyParser<PermissionsControllerReadOneData>
) => [createQueryKey('permissionsControllerReadOne', options)];
export const permissionsControllerReadOneOptions = <
  TResponse = PermissionsControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<PermissionsControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await permissionsControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: permissionsControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const usePermissionsControllerReadOneQuery = <
  TResponse = PermissionsControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<PermissionsControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...permissionsControllerReadOneOptions(dataOptions ?? {}, hookOptions),
  });
};
export const permissionsControllerReadQueryKey = (
  options: OptionsLegacyParser<PermissionsControllerReadData>
) => [createQueryKey('permissionsControllerRead', options)];
export const permissionsControllerReadOptions = <
  TResponse = PermissionsControllerReadResponse,
>(
  options?: OptionsLegacyParser<PermissionsControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await permissionsControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: permissionsControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const usePermissionsControllerReadQuery = <
  TResponse = PermissionsControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<PermissionsControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...permissionsControllerReadOptions(dataOptions ?? {}, hookOptions),
  });
};
