// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  resourceHeroControllerCreate,
  resourceHeroControllerRead,
  resourceHeroControllerUpdate,
  resourceHeroControllerReadOne,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  ResourceHeroControllerCreateData,
  ResourceHeroControllerCreateError,
  ResourceHeroControllerCreateResponse,
  ResourceHeroControllerReadData,
  ResourceHeroControllerReadResponse,
  ResourceHeroControllerUpdateData,
  ResourceHeroControllerUpdateError,
  ResourceHeroControllerUpdateResponse,
  ResourceHeroControllerReadOneData,
  ResourceHeroControllerReadOneResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const resourceHeroControllerCreateMutation = <
  TResponse = ResourceHeroControllerCreateResponse,
>(
  options?: Partial<OptionsLegacyParser<ResourceHeroControllerCreateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ResourceHeroControllerCreateError,
      OptionsLegacyParser<ResourceHeroControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    ResourceHeroControllerCreateError,
    OptionsLegacyParser<ResourceHeroControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await resourceHeroControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useResourceHeroControllerCreate = <
  TResponse = ResourceHeroControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<ResourceHeroControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ResourceHeroControllerCreateError,
      OptionsLegacyParser<ResourceHeroControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...resourceHeroControllerCreateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const resourceHeroControllerReadQueryKey = (
  options: OptionsLegacyParser<ResourceHeroControllerReadData>
) => [createQueryKey('resourceHeroControllerRead', options)];
export const resourceHeroControllerReadOptions = <
  TResponse = ResourceHeroControllerReadResponse,
>(
  options?: OptionsLegacyParser<ResourceHeroControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await resourceHeroControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: resourceHeroControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useResourceHeroControllerReadQuery = <
  TResponse = ResourceHeroControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<ResourceHeroControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...resourceHeroControllerReadOptions(dataOptions ?? {}, hookOptions),
  });
};
export const resourceHeroControllerUpdateMutation = <
  TResponse = ResourceHeroControllerUpdateResponse,
>(
  options?: Partial<OptionsLegacyParser<ResourceHeroControllerUpdateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ResourceHeroControllerUpdateError,
      OptionsLegacyParser<ResourceHeroControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    ResourceHeroControllerUpdateError,
    OptionsLegacyParser<ResourceHeroControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await resourceHeroControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useResourceHeroControllerUpdate = <
  TResponse = ResourceHeroControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<ResourceHeroControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      ResourceHeroControllerUpdateError,
      OptionsLegacyParser<ResourceHeroControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...resourceHeroControllerUpdateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const resourceHeroControllerReadOneQueryKey = (
  options: OptionsLegacyParser<ResourceHeroControllerReadOneData>
) => [createQueryKey('resourceHeroControllerReadOne', options)];
export const resourceHeroControllerReadOneOptions = <
  TResponse = ResourceHeroControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<ResourceHeroControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await resourceHeroControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: resourceHeroControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useResourceHeroControllerReadOneQuery = <
  TResponse = ResourceHeroControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<ResourceHeroControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...resourceHeroControllerReadOneOptions(dataOptions ?? {}, hookOptions),
  });
};
