// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  rolesControllerCreate,
  rolesControllerRead,
  rolesControllerUpdate,
  rolesControllerDelete,
  rolesControllerReadOne,
  rolesControllerSoftDelete,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  RolesControllerCreateData,
  RolesControllerCreateError,
  RolesControllerCreateResponse,
  RolesControllerReadData,
  RolesControllerReadResponse,
  RolesControllerUpdateData,
  RolesControllerUpdateError,
  RolesControllerUpdateResponse,
  RolesControllerDeleteError,
  RolesControllerDeleteResponse,
  RolesControllerReadOneData,
  RolesControllerReadOneResponse,
  RolesControllerSoftDeleteError,
  RolesControllerSoftDeleteResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const rolesControllerCreateMutation = <
  TResponse = RolesControllerCreateResponse,
>(
  options?: Partial<OptionsLegacyParser<RolesControllerCreateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      RolesControllerCreateError,
      OptionsLegacyParser<RolesControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    RolesControllerCreateError,
    OptionsLegacyParser<RolesControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await rolesControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useRolesControllerCreate = <
  TResponse = RolesControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<RolesControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      RolesControllerCreateError,
      OptionsLegacyParser<RolesControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...rolesControllerCreateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const rolesControllerReadQueryKey = (
  options: OptionsLegacyParser<RolesControllerReadData>
) => [createQueryKey('rolesControllerRead', options)];
export const rolesControllerReadOptions = <
  TResponse = RolesControllerReadResponse,
>(
  options?: OptionsLegacyParser<RolesControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await rolesControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: rolesControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useRolesControllerReadQuery = <
  TResponse = RolesControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<RolesControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...rolesControllerReadOptions(dataOptions ?? {}, hookOptions),
  });
};
export const rolesControllerUpdateMutation = <
  TResponse = RolesControllerUpdateResponse,
>(
  options?: Partial<OptionsLegacyParser<RolesControllerUpdateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      RolesControllerUpdateError,
      OptionsLegacyParser<RolesControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    RolesControllerUpdateError,
    OptionsLegacyParser<RolesControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await rolesControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useRolesControllerUpdate = <
  TResponse = RolesControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<RolesControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      RolesControllerUpdateError,
      OptionsLegacyParser<RolesControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...rolesControllerUpdateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const rolesControllerDeleteMutation = <
  TResponse = RolesControllerDeleteResponse,
>(
  options?: Partial<OptionsLegacyParser>,
  hookOptions?: Omit<
    MutationOptions<TResponse, RolesControllerDeleteError, OptionsLegacyParser>,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    RolesControllerDeleteError,
    OptionsLegacyParser
  > = {
    mutationFn: async localOptions => {
      const { data } = await rolesControllerDelete({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useRolesControllerDelete = <
  TResponse = RolesControllerDeleteResponse,
>(
  dataOptions?: OptionsLegacyParser,
  hookOptions?: Omit<
    MutationOptions<TResponse, RolesControllerDeleteError, OptionsLegacyParser>,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...rolesControllerDeleteMutation(dataOptions ?? {}, hookOptions),
  });
};
export const rolesControllerReadOneQueryKey = (
  options: OptionsLegacyParser<RolesControllerReadOneData>
) => [createQueryKey('rolesControllerReadOne', options)];
export const rolesControllerReadOneOptions = <
  TResponse = RolesControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<RolesControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await rolesControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: rolesControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useRolesControllerReadOneQuery = <
  TResponse = RolesControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<RolesControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...rolesControllerReadOneOptions(dataOptions ?? {}, hookOptions),
  });
};
export const rolesControllerSoftDeleteMutation = <
  TResponse = RolesControllerSoftDeleteResponse,
>(
  options?: Partial<OptionsLegacyParser>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      RolesControllerSoftDeleteError,
      OptionsLegacyParser
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    RolesControllerSoftDeleteError,
    OptionsLegacyParser
  > = {
    mutationFn: async localOptions => {
      const { data } = await rolesControllerSoftDelete({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useRolesControllerSoftDelete = <
  TResponse = RolesControllerSoftDeleteResponse,
>(
  dataOptions?: OptionsLegacyParser,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      RolesControllerSoftDeleteError,
      OptionsLegacyParser
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...rolesControllerSoftDeleteMutation(dataOptions ?? {}, hookOptions),
  });
};
