// @ts-nocheck
// This file is auto-generated by @ts-sdk-gen/openapi-ts and should not be edited manually.
import type { OptionsLegacyParser } from '@ts-sdk-gen/client-fetch';
import {
  client,
  usersControllerCreate,
  usersControllerRead,
  usersControllerUpdate,
  usersControllerReadOne,
  usersControllerUpdateProfile,
  usersControllerReadMe,
  usersControllerSoftDelete,
} from '../sdk.gen';
import {
  type UseMutationOptions,
  useMutation,
  type MutationOptions,
  queryOptions,
  useQuery,
  type QueryOptions,
} from '@tanstack/react-query';
import type {
  UsersControllerCreateData,
  UsersControllerCreateError,
  UsersControllerCreateResponse,
  UsersControllerReadData,
  UsersControllerReadResponse,
  UsersControllerUpdateData,
  UsersControllerUpdateError,
  UsersControllerUpdateResponse,
  UsersControllerReadOneData,
  UsersControllerReadOneResponse,
  UsersControllerUpdateProfileData,
  UsersControllerUpdateProfileError,
  UsersControllerUpdateProfileResponse,
  UsersControllerReadMeData,
  UsersControllerReadMeResponse,
  UsersControllerSoftDeleteData,
  UsersControllerSoftDeleteError,
  UsersControllerSoftDeleteResponse,
} from '../types.gen';
type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];
const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};
export const usersControllerCreateMutation = <
  TResponse = UsersControllerCreateResponse,
>(
  options?: Partial<OptionsLegacyParser<UsersControllerCreateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      UsersControllerCreateError,
      OptionsLegacyParser<UsersControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    UsersControllerCreateError,
    OptionsLegacyParser<UsersControllerCreateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersControllerCreate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useUsersControllerCreate = <
  TResponse = UsersControllerCreateResponse,
>(
  dataOptions?: OptionsLegacyParser<UsersControllerCreateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      UsersControllerCreateError,
      OptionsLegacyParser<UsersControllerCreateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...usersControllerCreateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const usersControllerReadQueryKey = (
  options: OptionsLegacyParser<UsersControllerReadData>
) => [createQueryKey('usersControllerRead', options)];
export const usersControllerReadOptions = <
  TResponse = UsersControllerReadResponse,
>(
  options?: OptionsLegacyParser<UsersControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await usersControllerRead({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: usersControllerReadQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useUsersControllerReadQuery = <
  TResponse = UsersControllerReadResponse,
>(
  dataOptions?: OptionsLegacyParser<UsersControllerReadData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...usersControllerReadOptions(dataOptions ?? {}, hookOptions),
  });
};
export const usersControllerUpdateMutation = <
  TResponse = UsersControllerUpdateResponse,
>(
  options?: Partial<OptionsLegacyParser<UsersControllerUpdateData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      UsersControllerUpdateError,
      OptionsLegacyParser<UsersControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    UsersControllerUpdateError,
    OptionsLegacyParser<UsersControllerUpdateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersControllerUpdate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useUsersControllerUpdate = <
  TResponse = UsersControllerUpdateResponse,
>(
  dataOptions?: OptionsLegacyParser<UsersControllerUpdateData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      UsersControllerUpdateError,
      OptionsLegacyParser<UsersControllerUpdateData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...usersControllerUpdateMutation(dataOptions ?? {}, hookOptions),
  });
};
export const usersControllerReadOneQueryKey = (
  options: OptionsLegacyParser<UsersControllerReadOneData>
) => [createQueryKey('usersControllerReadOne', options)];
export const usersControllerReadOneOptions = <
  TResponse = UsersControllerReadOneResponse,
>(
  options?: OptionsLegacyParser<UsersControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await usersControllerReadOne({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: usersControllerReadOneQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useUsersControllerReadOneQuery = <
  TResponse = UsersControllerReadOneResponse,
>(
  dataOptions?: OptionsLegacyParser<UsersControllerReadOneData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...usersControllerReadOneOptions(dataOptions ?? {}, hookOptions),
  });
};
export const usersControllerUpdateProfileMutation = <
  TResponse = UsersControllerUpdateProfileResponse,
>(
  options?: Partial<OptionsLegacyParser<UsersControllerUpdateProfileData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      UsersControllerUpdateProfileError,
      OptionsLegacyParser<UsersControllerUpdateProfileData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    UsersControllerUpdateProfileError,
    OptionsLegacyParser<UsersControllerUpdateProfileData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersControllerUpdateProfile({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useUsersControllerUpdateProfile = <
  TResponse = UsersControllerUpdateProfileResponse,
>(
  dataOptions?: OptionsLegacyParser<UsersControllerUpdateProfileData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      UsersControllerUpdateProfileError,
      OptionsLegacyParser<UsersControllerUpdateProfileData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...usersControllerUpdateProfileMutation(dataOptions ?? {}, hookOptions),
  });
};
export const usersControllerReadMeQueryKey = (
  options: OptionsLegacyParser<UsersControllerReadMeData>
) => [createQueryKey('usersControllerReadMe', options)];
export const usersControllerReadMeOptions = <
  TResponse = UsersControllerReadMeResponse,
>(
  options?: OptionsLegacyParser<UsersControllerReadMeData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return queryOptions({
    queryFn: async () => {
      const { data } = await usersControllerReadMe({
        ...(options ?? {}),
      });
      return data;
    },
    queryKey: usersControllerReadMeQueryKey(options ?? {}),
    ...hookOptions,
  });
};
export const useUsersControllerReadMeQuery = <
  TResponse = UsersControllerReadMeResponse,
>(
  dataOptions?: OptionsLegacyParser<UsersControllerReadMeData>,
  hookOptions?: Omit<
    QueryOptions<TResponse | undefined>,
    'queryKey' | 'queryFn'
  >
) => {
  return useQuery({
    ...usersControllerReadMeOptions(dataOptions ?? {}, hookOptions),
  });
};
export const usersControllerSoftDeleteMutation = <
  TResponse = UsersControllerSoftDeleteResponse,
>(
  options?: Partial<OptionsLegacyParser<UsersControllerSoftDeleteData>>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      UsersControllerSoftDeleteError,
      OptionsLegacyParser<UsersControllerSoftDeleteData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  const mutationOptions: UseMutationOptions<
    TResponse,
    UsersControllerSoftDeleteError,
    OptionsLegacyParser<UsersControllerSoftDeleteData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersControllerSoftDelete({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
    ...hookOptions,
  };
  return mutationOptions;
};
export const useUsersControllerSoftDelete = <
  TResponse = UsersControllerSoftDeleteResponse,
>(
  dataOptions?: OptionsLegacyParser<UsersControllerSoftDeleteData>,
  hookOptions?: Omit<
    MutationOptions<
      TResponse,
      UsersControllerSoftDeleteError,
      OptionsLegacyParser<UsersControllerSoftDeleteData>
    >,
    'mutationKey' | 'mutationFn'
  >
) => {
  return useMutation({
    ...usersControllerSoftDeleteMutation(dataOptions ?? {}, hookOptions),
  });
};
